- phidata/infra/aws/resource/ecs/cluster.py
- phidata/infra/aws/resource/ecs/service.py
- scripts/install.sh
- `phi ws patch` should create a new ECS Task definitions
Run: `phi ws patch --env prd --config aws --name td`
Update task definition:
> Update ecs task definition using phi ws phi 110

- phidata/infra/aws/resource/eks/node_group.py
phi ws patch should update the EKS node group resource
run `phi ws patch --env prd --config aws --name services-ng -d   `
> phi ws patch for eks node group resource

- phi/assistant/assistant.py
- phi/task/llm/llm_task.py
Added an option to include the current datetime in the assistant's instructions in order to give the assistant a sense of time enabling the use of queries using relative time such as today, yesterday, tomorrow.
> Option to include the current date to the prompt

- scripts/create_venv.sh
This commit addresses an issue where folder names containing spaces caused
errors in the create_venv.sh script. Changes were made to properly handle
folder names with spaces by enclosing variable expansions in double quotes
and using double quotes around variable references throughout the script.
This ensures correct interpretation of paths and prevents errors when
dealing with folder names containing spaces.
Modified lines:
- Enclosed variable expansions for CURR_DIR, REPO_ROOT, and VENV_DIR in double quotes.
- Used double quotes around variable references when printing messages or executing commands.
> Fix handling of folder names with spaces in create_venv.sh

- cookbook/tools/duckduckgo.py
- phi/tools/resend.py
This commit adds a new tool class called `ResendTools`. The purpose of this class is to enable the assistant to send emails to users using Resend when provided with a Resend API key and an email address. This enhances the capability of the Assistant by adding communication and user interaction.
> resend-tool-phi-339

- cookbook/knowledge/pdf.py
Added pdf.py where a user can enter "python cook/knowledge/pdf.py" to view an example of using the PDFKnowledgeBase. Additionally I've added comments displaying how the user can view the local database that the assistant is relying upon.
> added cookbook in knowledge to showcase how to use the PDFKnowledgeBase

- cookbook/examples/rag_with_lance_and_sqllite/README.md
- cookbook/examples/rag_with_lance_and_sqllite/assistant.py
- Configured Ollama language model and LanceDb vector database 
- Created PDFUrlKnowledgeBase with LanceDb storage
- Loaded existing knowledge base and set up SQL assistant storage 
- Initialized Assistant with configurations for user interaction 
- Enabled response generation in Markdown format for queries
> Add RAG with LanceDB knowledge and SQLite storage.

- cookbook/assistants/README.md
Fix a small typo in the pip install instructions for pypdf
> Fix typo in pip install instructions (cookbook/assistants)

- cookbook/examples/personalization/requirements.txt
- Personalized Memory & Auto RAG example breaking due to wrong phidata sdk version
> fix: outdated version of phidata in requirements.txt

- phi/tools/yfinance.py
get_historical_stock_prices was not using the input parameters `interval` and `period`. As a result, it was returning only a single datapoint
> fixed get_historical_stock_prices

- phi/tools/sql.py
As we discussed on discord, when using sqltools if you connect it to a MySQL server it gives error when trying to serialize a datetime field and this could be easily avoided by giving a default when serializing the results to json.
```py
return json.dumps(self.run_sql(sql=query, limit=limit), default=str)
```
> [SQLtools] fix exception "Object of type datetime is not JSON serializable" with MySQL server

- phi/storage/assistant/sqllite.py
`SqlAssistantStorage` is great for developers who just need to create native applications.
HHowever, when I tested it, I found that the current SqlAssistantStorage doesn't successfully save data into SQlite because changes made to the database are **not committed** when using SQLAlchemy ORM.
So I added `sess.commit()` to commit the transaction and log an error message if an exception is caught. If OperationalError occurs, it will try to create the form and re-execute the operation. Other types of exceptions will be caught and the transaction will be rolled back after logging the error message.
Hope this helps!
> Fix a bug SqlAssistantStorage can't save data

- cookbook/examples/scraping/app.py
- phi/tools/__init__.py
- phi/tools/jina_tools.py
- phi/utils/json_schema.py
- tests/tools/test_jina_tools.py
What inside:
- Implement JinaReaderTools (API from https://jina.ai/reader) to fetch and summarize web content
- Add read_url and search_query methods to interact with Jina Reader API
- Truncate content to a maximum length for better readability
- Include tests for JinaReaderTools functionality
The JinaReaderTools toolkit allows the Assistant to retrieve and summarize web content using the Jina Reader API. This enables the Assistant to search the web and provide relevant information to users.
> feat(tools): add JinaReaderTools for web content retrieval

- cookbook/assistants/langchain_retriever.py
- Replace '__file__' string with __file__ identifier to correctly initialize Path object.
- This change ensures that the Path object uses the actual file location rather than the string '__file__'.
> Fix incorrect path initialization in cookbook_dir

- phi/assistant/assistant.py
Some arguments for the Assistant, such as `prevent_hallucinations` and `prevent_prompt_injection`, are intended to generate instructions for the LLM. However, these arguments have no effect and are never included in the prompt.
The following code snippet explains why:
```py
instructions = self.instructions.copy() if self.instructions is not None else []
if instructions is None:
```
https://github.com/phidatahq/phidata/blob/v2.4.32/phi/assistant/assistant.py#L580-L583
If my understanding is correct, the condition `if instructions is None` will never be met, since `instructions` is either a copy of a list or initialized as an empty list.
Initializing instructions with `None` fixes the issue.
> fix: Some arguments have no effect in the Assistant's LLM Instructions

- cookbook/llms/azure_openai/assistant.py
- cookbook/llms/azure_openai/assistant_stream_off.py
- phi/llm/anthropic/claude.py
- phi/llm/azure/openai_chat.py
Changes:
- Added a custom `invoke_stream` function for `AzureOpenAIChat` as it does not support `stream_options={"include_usage": True},` parameter to get token usage details when streaming
Known bug:
As is does not support this parameter, token usage information for `AzureOpenAIChat` while streaming is not stored.
> fix-azure-openai-streaming-phi-937

- phi/llm/anthropic/claude.py
Bug: Running Anthropic with `search_knowledge=True` yields:
```
Traceback (most recent call last):
File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\phi\llm\anthropic\claude.py", line 405, in response_stream
yield from self.response(messages=messages)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\phi\llm\anthropic\claude.py", line 168, in response
response_content: TextBlock = response.content[0].text  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python …
```
> fix: bad response type in /anthropic/claude.py

- phi/vectordb/pgvector/pgvector2.py
Changes:
- Bug fix to allow `updated_at` column of `Pgvector2` to work as expected. 
Notes:
- `on_conflict_do_update` in the upsert operation modifies the row in the database, but it doesn’t trigger SQLAlchemy’s `onupdate` logic because the database is managing the update internally.
> fix-updated_at-for-pgvector2-upsert-phi-1114

- phi/llm/base.py
When delegating a task to an assistant, the function call is encapsulated in a `Message` object. However, if the assistant utilizes an `output_model`, the validation for the `Message` object fails because the `content` attribute expects a string, but the `output_model` does not meet that requirement.
To resolve this, the `output_model` can be serialized into a JSON string before constructing the `Message` object, ensuring it passes the validation.
> fix: accept assistant with output_model when delegating tasks to a team

- phi/assistant/assistant.py
When using `output_model` with nested objects, an extra `$defs` field is listed in the json fields requested in the output. This field contains the definitions of nested objects, but it should not be included as a top-level field in the output JSON structure.
```md
Provide your output as a JSON containing the following fields:
<json_fields>
["entities", "$defs"] // HERE
</json_fields>
Here are the properties for each field:
<json_field_properties>
{
"entities": {
"description": "The list of entities.",
"items": {
"$ref": "#/$defs/EntityOutput"
},
"type": "array"
},
"$defs": {
"EntityOutput": {
"name": {
"description": "The name of the category as output by the category lookup
tool.",
"type": "string"
}
}
}
}
</json_field_properties>
```
Even if the `$defs` field must be present in the …
> fix: do not request the LLM to provide a $defs field

- phi/agent/agent.py
- phi/playground/playground.py
Changes:
- `model` is now added to `run_response` after `self.update_model()` fn to avoid the edge case when model is not provided by the user
> bug-with-runresponse-model-when-no-model-is-provided-phi-1235

- phi/model/openai/chat.py
Changes:
- Fixed indent of response.usage which was preventing stream metrics from being logged
> fix-openaichat-metrics-streaming-phi-1361

- phi/knowledge/langchain.py
Fixes #1096 
I ran the scripts `format.sh`, `validate.sh` and `test.sh`. There were some formatting changes and type warnings in other files that don't seem related to this change. The tests could not run (or only partially) because I do not have enough OpenAI quota.
This is my first contribution to phidata, so I'm very happy to hear all of your feedback :)
> Relax instance check from `VectorStoreRetriever` to `BaseRetriever`

- cookbook/tools/github_tools.py
- phi/tools/github.py
- Adds GithubToolkit for developers to interact with GitHub repositories, issues, and pull requests via the agent.
- Supports authentication using GitHub Personal Access Tokens, including GitHub Enterprise compatibility.
- Enables repository management: searching, listing, and retrieving detailed information.
- Provides pull request functionalities: listing PRs, fetching PR details, and viewing PR changes.
- Enhances issue management: listing issues (excluding PRs), getting issue details, commenting, closing/reopening, assigning, and labeling issues.
> add ghub tools

- phi/agent/agent.py
- phi/model/base.py
- phi/model/openai/chat.py
- phi/tools/function.py
- phi/utils/json_schema.py
All this is in context of OpenAI models. Because of big test run logs, I am putting them in pastebin and linking them here, else this description becomes too big and github does not allow too big descriptions.
Details:
======
As of now structured output works, but only in case if agent is not given any tools. If we give tools to an agent and also expect it to give structured output, it fails with below error: https://pastebin.com/Ckgi1YCU
Here is the test script: https://pastebin.com/72SgZ00j
When either tools are not provided or below two arguments are not passed (or commented) in call to `Agent()`, the test pass without any issues. 
```
structured_outputs=True,
response_model=ResponseObj,
```
As from error, we can see that OpenAI expects functions to be marked as `"strict": True` when …
> Made changes to support structured output from OpenAI models along with tools calling

- cookbook/knowledge/combined_kb.py
- cookbook/knowledge/csv_kb.py
- cookbook/knowledge/docx_kb.py
I am adding csv, combined, and docx knowledge base cookbook
> Adding knowledge base cookbooks

- phi/embedder/sentence_transformer.py
With this PR users can be able to use SentenceTransformerEmbedder on VectorDB 🚀
```
vector_db = LanceDb(
table_name="blablabla",
uri="lancedb",
search_type=SearchType.keyword,
embedder=SentenceTransformerEmbedder()
)
knowledge_base = JSONKnowledgeBase(
path="./data.json",
vector_db=vector_db,
)
```
> Implements get_embedding_and_usage on SentenceTransformerEmbedder

- cookbook/assistants/integrations/singlestore/README.md
- cookbook/assistants/integrations/singlestore/ai_apps/README.md
- cookbook/integrations/singlestore/README.md
In multiple readme.md file there is broken link of
> For SingleStore
> Note: If using a shared tier, please provide a certificate file for SSL connection [Read more](https://docs.singlestore.com/cloud/connect-to-your-workspace/connect-with-mysql/connect-with-mysql-client/connect-to-singlestore-helios-using-tls-ssl/)
Resolved the broken links and now redirects correctly
> Broken Link in multiple readme.md files

- phi/agent/agent.py
Prevents creation of empty context when no knowledge base is provided. Example: 
```
"context" : {
"query" : "How do I make a Thai curry?",
"time" : 0
}
```
> context-creation-without-knowledge-base-phi-2019

- cookbook/vectordb/lance_db.py
Added an example cookbook on how to use **LanceDB** as your Vectorstore to run your agent.
The Example code follows the same sturcture and style as that of other cookbooks. 
Lmk if there needs to be any change. Thanks. 
cc : @ashpreetbedi @manthanguptaa
> Add: Example on how to use LanceDB as vectorDB.

- cookbook/rag/06_agentic_rag_with_reranking.py
- phi/document/base.py
- phi/reranker/base.py
- phi/reranker/cohere.py
- phi/vectordb/chroma/chromadb.py
- phi/vectordb/lancedb/lance_db.py
- phi/vectordb/pgvector/pgvector.py
- phi/vectordb/pgvector/pgvector2.py
- phi/vectordb/pineconedb/pineconedb.py
- phi/vectordb/qdrant/qdrant.py
- phi/vectordb/singlestore/s2vectordb.py
- phi/vectordb/singlestore/s2vectordb2.py
#1416
This PR introduces a unified reranker implementation within phi.reranker to support reranking functionality across various vectordb instances, not limited to lancedb. It adds the CohereReranker to allow consistent reranking behavior across different vector databases. 
- Implemented a common reranker under phi.reranker to standardize reranking across vectordb instances.
- Added `CohereReranker` to `phi.reranker.cohere.py`, enabling the integration of Cohere’s reranker with any vectordb instance.
- Updated search logic to conditionally apply the reranker, allowing flexible and consistent reranking during searches.
- Added `reranking_score` field to `Document` to store scores used in reranking.
- Added `06_agentic_rag_with_reranking.py` to `cookbook.rag` as an example demonstrating RAG …
> Enable reranking for all vectordb instances in search

- cookbook/vectordb/lance_db.py
- phi/model/ollama/chat.py
Changes:
- Update to Ollama Tool Call Streaming
> Ollama tool streaming update phi 2122

- cookbook/providers/google/audio_agent.py
- cookbook/providers/google/image_agent.py
- cookbook/providers/google/video_agent.py
- cookbook/providers/vertexai/agent.py
- phi/agent/agent.py
- phi/model/google/gemini.py
- phi/model/message.py
Changes:
- Added image input for Gemini
- Added video input for Gemini
- Added audio input for Gemini
Future improvements:
- Upload feature for Images and Audio > 20 mb
- Support for multiple audio files without breaking current integration for Groq and OpenAI.
> Gemini multimodality update phi 2173

- cookbook/agents/46_generate_yt_timestamps.py
- phi/tools/youtube_tools.py
This generates YT timestamps based on captions
> generates timestamp of a youtube video

- cookbook/examples/agents/study_partner.py
- Added agent for Study planner
- Enhances clarity and alignment with user needs for study support.
Added agent for study planner, one stop solution for all the resources related to a particular topic, 
> Use Case : Study Partner

- cookbook/knowledge/youtube_kb.py
- phi/document/reader/youtube_reader.py
- phi/knowledge/youtube.py
- Include Youtube reader logic using Youtube-transcript-api
- Create a YouTube knowledge base useful for Agentic RAG over YouTube video
- Include example usage for YouTube Knowledge Base. 
- Attached screenshot with the result
> Feat: Youtube Knowledge Base Video URLs

- cookbook/examples/agents/07_weekend_planner.py
This agent gives you recommendations for activities and events and helps you plan your weekend
> created a weekend planner agent

- cookbook/providers/ollama/agent.py
- cookbook/providers/ollama/agent_stream.py
- phi/model/ollama/chat.py
- phi/tools/function.py
Ollama requires a specific formatting for JSONschema tools where parameter types can only be a string, never a list of strings (which is actually valid JSONschema). To compensate for this we ensure optional parameters where the type is `['string', 'null']` is transformed to just `'string'` to be compatible. 
This should not have impact, because we provide a list of "required" parameters with function definitions.
Fixes #1584 
> Fix tool parsing for ollama

- cookbook/playground/gemini_agents.py
- phi/model/google/gemini.py
- phi/playground/router.py
- phi/run/response.py
Our run response parsing for the playground was not able to adequately parse `messages` in responses where tool_calls contained unserializable objects from Gemini. This resolves it.
Fixes #1509 
> Fix response parsing to make gemini tool use work

- phi/document/chunking/recursive.py
This pull request fixes an issue encountered when using `RecursiveChunking` with large files. Previously, this could lead to a psycopg.errors.UniqueViolation error due to duplicate key violations during processing large files that more than one chunk, it generated same chunk record `id`.
Fixes #1588
> fix: docs has same id with recursive chucking

- cookbook/workflows/startup_idea_validator.py
This adds an example workflow for validating a new startup idea and doing market research.
> Add a startup idea validator workflow

- cookbook/agents/14_generate_image.py
- cookbook/providers/ollama/agent_set_client.py
- phi/model/ollama/chat.py
- phi/tools/eleven_labs_tools.py
If you set the client manually for Ollama, then there is an issue when the agent model is copied where certain properties can't be pickled. This resolves it.
> Add model_copy to make ollama chat deep copy work with a set client

- cookbook/agents/14_generate_image.py
- cookbook/mysql-init/init.sql
- cookbook/providers/ollama/agent_set_client.py
- cookbook/run_mysql.sh
- cookbook/tools/composio_tools.py
- phi/model/ollama/chat.py
- phi/tools/function.py
- pyproject.toml
This update introduces the Confluence tool for collaboration, improves tool compatibility, and resolves deep copy issues for Ollama chat agents.
**New Features:**
- Confluence Tool: Added a new tool using the Atlassian Confluence SDK, enabling operations such as listing pages in a space, creating and updating pages, retrieving page content by title, and getting space details.
**Improvements:**
- Tool Compatibility: Enhanced older custom functions with manually specified descriptions and parameters to align with the updated tool-building system.
**Bug Fixes:**
- Deep Copy for Ollama Chat Agents: Addressed an issue where manually set clients caused errors during agent model copying, ensuring all properties are properly handled.
> Release 2.7.5

- phi/vectordb/qdrant/qdrant.py
Removes OpenAI embedder as the default embedder for Qdrant 
> fix qdrant default embedder

- cookbook/async/gather_agents.py
- cookbook/workflows/startup_idea_validator.py
This PR adds an example showcasing the use of `asyncio.gather` to run multiple agents concurrently 
> gather agents example

- phi/document/reader/docx.py
There was no proper error handling when `python-docx` lib wasn't installed which caused users issue
> Improvement: Better error handling when python-docx isn't installed

- cookbook/tools/duckduckgo_mod.py
- phi/tools/duckduckgo.py
Adds a simple "modifier" parameter to the DuckDuckGo (DDG) tool that let's users (not exposed to agents) modify the query so that DDG only searches specific sites, e.g "site:redhat.com", search for specific file types (e.g "filetype:pdf") or turn on/off safe search "!safeon"/"!safeoff".
See https://duckduckgo.com/duckduckgo-help-pages/results/syntax/ for more information.
> Add optional ddg modifier

- phi/document/reader/docx.py
- phi/model/google/__init__.py
- phi/tools/duckduckgo.py
- phi/vectordb/cassandra/cassandra.py
- phi/vectordb/cassandra/extra_param_mixin.py
- pyproject.toml
Fixes `openai` not installed error when using Gemini 
> Gemini import fix

- phi/tools/duckduckgo.py
- **Summary of changes**: DDGS provides SSL verification option (with verification enabled by default). Adding it to the DuckDuckGo tool also.
- **Related issues**: N/A
- **Motivation and context**: Experimenting with the introduction example, and ran into SSL issues (cough cough enterprise stuff cough cough)
- **Environment or dependencies**: No changes.
- **Impact on AI/ML components**: (If applicable) N/A
Fixes # N/A
Include any deployment notes, performance implications, or other relevant information: When trying to format, according to the CONTRIBUTING.md, the `ruff` module wasn't installed by default using the create venv script. I can see it's in the dev modules inside the pyproject.toml. Is that expected? Thanks!
> refactor: passing down ssl verification as it's available in DDGS class

- cookbook/agents/47_image_to_image.py
- cookbook/playground/multimodal_agent.py
- cookbook/workflows/startup_idea_validator.py
- phi/tools/fal_tools.py
Image to Image agent that uses Fal tools.
> Image to image agent

- phi/model/google/gemini.py
This PR adds support for tools with input as a list for Gemini 
> Gemini list as tool call param fix phi 2238

- cookbook/tools/spider_tools.py
- phi/tools/spider.py
Hi, member of Spider team here, would love to add these changes to the tool.
- **Summary of changes**: Updated tool to allow passing in custom params when instantiating SpiderTools class. Added a default limit of `10` for crawling, to reduce token waste.
- **Motivation and context**: Allowing custom parameters to be passed allows the developer to handle more use cases or control the scraping ability of a given URL (e.g. turning on proxy etc).
- **Environment or dependencies**: No changes in dependencies or environment configurations required for this update.
> chore(spidertools): Added support for optional API parameters and setting default crawl limit

- cookbook/tools/scrapegraph_tools.py
- phi/tools/scrapegraph_tools.py
- pyproject.toml
Adds integration with ScrapeGraph AI for smart web scraping and markdown conversion capabilities.
- `smartscraper`: Extract structured data from webpages using LLM
- `markdownify`: Convert webpages to markdown format
Get a free API key at [dashboard.scrapegraphai.com](https://dashboard.scrapegraphai.com)
```python
from phi.agent import Agent
from phi.tools.scrapegraph_tools import ScrapeGraphTools
scrapegraph = ScrapeGraphTools(smartscraper=True)
agent = Agent(tools=[scrapegraph], show_tool_calls=True, markdown=True, stream=True)
agent.print_response("""
Use smartscraper to extract the following from https://www.wired.com/category/science/:
- News articles
- Headlines
- Images
- Links
- Author
""")
```
- Requires `scrapegraph-py` package, which is [scrapegraphai official …
> 🕷️ feat: scrapegraph tools integration

- cookbook/assistants/llms/groq/video_summary/app.py
- cookbook/assistants/llms/ollama/video_summary/app.py
- cookbook/assistants/tools/hackernews.py
- cookbook/teams/02_news_reporter.py
- cookbook/tools/hackernews.py
- cookbook/workflows/content_creator_workflow/prompts.py
- phi/agent/agent.py
- phi/assistant/assistant.py
- phi/cli/config.py
- phi/document/chunking/agentic.py
- phi/embedder/fastembed.py
- phi/memory/classifier.py
- phi/memory/manager.py
- phi/memory/summarizer.py
- phi/tools/decorator.py
- phi/tools/github.py
- phi/tools/wikipedia.py
- phi/vectordb/chroma/chromadb.py
- phi/vectordb/milvus/milvus.py
- phi/vectordb/qdrant/qdrant.py
Updated `get_embedding_and_usage` function of `FastEmbedEmbedder`. 
Fixes #1715 
Notes:
`FastEmbedEmbedder` currently does not provide usage information
> fastembedder-fix

- phi/vectordb/lancedb/lance_db.py
Lancedb insert bug fix 
Fixes #1780
> lancedb-fix-phi-2404

- libs/agno/agno/memory/agent.py
This change was breaking memories without a user id. Please test with: `cookbook/models/openai/memory.py`
> agnomemory-folder-cleanup-test-and-refactor-phi-2254

- libs/agno/agno/agent/agent.py
- **Summary of changes**: Clearly describe the key changes in this PR and their purpose.
- **Related issues**: Mention if this PR fixes or is connected to any issues (e.g., "Fixes #123" or "Relates to #456").
- **Impact on AI/ML components**: (If applicable) Describe changes to AI/ML models and include performance metrics (e.g., accuracy, F1-score).
> Fix empty session_id handling

- phi/agent/agent.py
I have been facing the following error: `TypeError: issubclass() arg 1 must be a class`, each time i make the sub agent generate structured output based on BaseModel class, apparently the error occurs because `issubclass()` expects its first argument to be a class, but `member_agent_run_response.content` is an instance of the `response_model`, not the class itself.
To fix the error, i passed the class of the object (not the instance) to `issubclass()`. I used the `type()` function to get the class of the object as follow:
> issubclass(type(member_agent_run_response.content), BaseModel)
No additional notes.
> :bug: fix: checking the class itself instead of it's instance

- phi/tools/slack.py
* Slack Tool fix for when the "user" field is blank or not available. Changed to safer ".get()" method.
* Added additional logic for webhooks/bots/etc, which caused crashes before. Tested in large/diverse Slack instance and after the fix it seems to work perfectly.
* https://github.com/phidatahq/phidata/issues/1753
N/A
> Fix for slack tool crash - caused by webhooks and certain bot messages

- cookbook/providers/azure_openai/knowledge.py
- cookbook/providers/mistral/structured_output.py
- cookbook/teams/01_hn_team.py
- cookbook/tools/reddit_tools.py
- cookbook/tools/trello_tools.py
- phi/agent/agent.py
- phi/document/chunking/semantic.py
- phi/embedder/sentence_transformer.py
- phi/playground/router.py
- phi/run/response.py
- phi/tools/slack.py
- phi/utils/string.py
- pyproject.toml
- tests/unit/utils/test_string.py
Tool calling does not work correctly with response models. This will use the response model if there is one, overriding any tool calling. The tool calls are then displayed separately.
This also solves the issue for teams.
Fixes #1792 
> Fix tool calls with response model

- phi/embedder/google.py
- **Summary of changes**: This pull request updates the GeminiEmbedder class in the phidata library to use the "models/embedding-004" model and sets the default embedding dimensions to 768. Previously, it used the "models/embedding-001" model with no pre-defined dimensions, making it consistent with the official [documentation](https://docs.phidata.com/embedder/gemini#params).
- **Related issues**: This PR addresses inconsistencies between the code and the official documentation.
- **Motivation and context**: The motivation is to ensure that the `GeminiEmbedder` class aligns with the expected behavior and parameters defined in the official documentation, preventing confusion and potential errors for users. The `model` field was being overwritten with the second declaration, and …
> GeminiEmbedder: update defaults

- phi/tools/telegram.py
- pyproject.toml
- RedditTools added with cookbook examples
- TelegramTools added with a cookbook example
- Updates the defaults on the GeminiEmbedder to use a more up-to-date model and incorporate recommendations from their [[docs](https://docs.phidata.com/embedder/gemini#params)](https://docs.phidata.com/embedder/gemini#params).
- Fix imports of `docx` being required for using the playground
- Fix AzureOpenAIEmbedder and AzureOpenAIChat compatibility
- Fix cases where SlackTool threw an exception when the "user" field is blank or not available
- Fix case where Response Models don’t work with show_tool_calls. This will use the response model if there is one, overriding any tool calling.
- Fix issue in Claude where memory blocks were stored in the raw claude format with TextBlock, etc
- Fix cases where …
> Release 2.7.9

- phi/vectordb/lancedb/lance_db.py
**Summary of changes**: 
Modified LanceDB initialization to make Tantivy dependency optional when only using vector search capabilities. The Tantivy import check is now conditional based on the search type being used.
**Related issues**: 
Fixes #1827 - ImportError being raised for vector-only search due to missing Tantivy dependency
> added condition of use_tantivy

- phi/tools/twitter.py
If the user does not provide the parameters while creating an object of Twitter tool, the credentials are fetched from the environment variables. However, when initializing the OAuth1UserHandler, it is being initialized with default parameters, which are set to null. This causes the code to break.
> Fixed the OAuth1UserHandler instance creation in twitter.py

- cookbook/playground/upload_files.py
removed `use_tools` from cookbook/playground/upload_files.py
---
---
---
> remove use-tools param

- CONTRIBUTING.md
- cookbook/examples/apps/agentic_rag/app.py
- cookbook/examples/apps/agentic_rag/utils.py
- cookbook/tools/x_tools.py
- libs/agno/agno/utils/common.py
- **Summary of changes**: This PR adds a point in CONTRIBUTING.md file for installing `uv` when setting up a development environment.
- **Related issues**: This PR is not connected to any issue.
- **Motivation and context**:  I just made a fork of this repo to understand and contribute to this project. When I was setting up development environment from the instructions, the setup was incomplete due to `uv` not being installed in my system.
- **Environment or dependencies**: No changes there
- **Impact on metrics**: NA.
---
---
---
> Updates CONTRIBUTING.md to add installation of uv in development setup

- libs/agno/agno/vectordb/lancedb/lance_db.py
- Added `name_exists` function for LanceDb. 
Fixes #2017
---
---
---
LanceDb natively does not allow `name_exists`. This is a very inefficient workaround. To be updated when native search for a doc name is added by LanceDb. `name_exists` is used by the `WebsiteKnowledgeBase`
> lance-db-name_exists-ag-2655

- cookbook/models/openai/reasoning/reasoning_effort.py
- cookbook/models/perplexity/basic_stream.py
- libs/agno/agno/models/openai/chat.py
- libs/agno/agno/models/perplexity/perplexity.py
- libs/agno/agno/playground/async_router.py
- libs/agno/agno/playground/sync_router.py
- libs/agno/pyproject.toml
- libs/agno/tests/unit/playground/test_image_support_file_upload.py
update.
- added image support in file upload,
- added multiple image support in file upload
---
---
---
> add image support in file upload

- libs/agno/agno/vectordb/pineconedb/pineconedb.py
- **Summary of changes**: Describe the key changes in this PR and their purpose. modified PineconeDb class on searching namespaces to use namespace value from the global variable
- **Related issues**: 
- **Motivation and context**: so user can use pineconedb to search by their defined namespace value instead ( default ) namespace.
- **Environment or dependencies**:
- **Impact on metrics**: 
---
---
---
> fix: pineconedb use namespace value from global variable

- libs/agno/agno/agent/agent.py
- libs/agno/agno/tools/firecrawl.py
Add optional parameter to pass custom api url in firecrawl
Fixed #2093 
---
---
---
> Add optional parameter to pass custom api url in firecrawl

- libs/agno/pyproject.toml
- **Firecrawl Custom API URL**: Allowed users to set a custom API URL for Firecrawl.
- **Gemini embedder update:** Updated the `GeminiEmbedder` to use the new [Google’s genai SDK](https://github.com/googleapis/python-genai). It means the interface has changed slightly:
```python
embeddings = GeminiEmbedder("models/text-embedding-004").get_embedding(
"The quick brown fox jumps over the lazy dog."
)
embeddings = GeminiEmbedder("text-embedding-004").get_embedding(
"The quick brown fox jumps over the lazy dog."
)
```
- Updated the `ModelsLabTools` toolkit constructor (`/libs/agno/tools/models_labs.py`) to accommodate audio generation api call. Its a breaking change since it changes the parameters of the `ModelsLabTools` class.
`url` and `fetch_url` are removed from the parameters. The API …
> Release 1.1.1

- libs/agno/pyproject.toml
- **Reasoning with o3 Models**: Reasoning support added for OpenAI’s o3 models.
- **Gemini embedder update:** Updated the `GeminiEmbedder` to use the new [Google’s genai SDK](https://github.com/googleapis/python-genai). This update introduces a slight change in the interface:
```python
embeddings = GeminiEmbedder("models/text-embedding-004").get_embedding(
"The quick brown fox jumps over the lazy dog."
)
embeddings = GeminiEmbedder("text-embedding-004").get_embedding(
"The quick brown fox jumps over the lazy dog."
)
```
- **Singlestore Fix:** Fixed issue where when querying singlestore the embeddings column was returning in binary format.
- **MongoDB Vectorstore Fix:** MongoDB had multiple issues like creating and dropping the collections twice while initialising. All known issues were …
> Release 1.1.2

- libs/agno/agno/models/openai/chat.py
Add metadata parameter to OpenAIChat's request_params
- #2145 
- Enhance API request tracking capability
- Add metadata-based analysis functionality
- Extend monitoring capabilities
- Add metadata field to base_params dictionary
```python
model = OpenAIChat(
id=model_name,
base_url=os.getenv("LITELLM_BASE_URL"),
api_key=os.getenv("LITELLM_API_KEY"),
metadata={"user_id": "demo_user",
"trace_user_id": "demo_trace_user"},
)
```
> ✨ Add metadata support to OpenAIChat

- libs/agno/agno/agent/agent.py
Users experienced issues where telemetry would be sent regardless of whether they set the telemetry flag or not. 
---
---
---
> Fix issue with telemetry being overwritten

- libs/agno/agno/models/anthropic/claude.py
- **Summary of changes**: handle case where properties of the input schema of a tool doesn't have `type` but uses `anyOf`
- **Motivation and context**: Using Agno, Claude, Composio, and trying to send an email with Gmail, breaks with JSON schema error
---
---
> Fix JSON schema error when using tools with anyOf instead of type

- libs/agno/tests/integration/models/azure/ai_foundry/test_basic.py
- libs/agno/tests/integration/models/azure/ai_foundry/test_multimodal.py
- libs/agno/tests/integration/models/azure/ai_foundry/test_tool_use.py
- libs/agno/tests/integration/models/azure/openai/test_basic.py
- libs/agno/tests/integration/models/azure/openai/test_multimodal.py
- libs/agno/tests/integration/models/azure/openai/test_tool_use.py
Add tests for azure model
---
---
---
> Add tests for azure

- cookbook/models/anthropic/thinking.py
- cookbook/models/anthropic/thinking_stream.py
- libs/agno/agno/models/base.py
Fix: claude thinking when not streaming
> Fix: claude thinking when not streaming

- libs/agno/agno/embedder/ollama.py
This fixes agno-agi/agno#2248, thanks to the reporter in that issue for the fix.
- Fixes the ollama `embedding` param to `embeddings`.
Fixes # (#2248 )
---
> fix: Get embeddings from the correct URI path

- libs/agno/agno/models/azure/openai_chat.py
---
---
---
In Agno you can't specify the `base_url` in the AzureOpenAI client. It is needed when the full URL is constructed differently
And this forces the construction of the URL in this way:
> Added base_url property in AzureOpenAI for non-default URLs

- cookbook/examples/apps/medical_imaging/app.py
- libs/agno/agno/models/base.py
- libs/agno/agno/models/google/gemini.py
- libs/agno/tests/integration/models/google/test_tool_use.py
There is a breaking issue when Gemini makes an incorrect function call.
Fixes #2241
---
---
---
> Fix gemini no function to call

- libs/agno/agno/tools/decorator.py
- **Summary of changes**: Small fix of using Dict instead of dict
- Fixes #2268 
---
---
> Ensure Python 3.8 compatibility by replacing dict[str, Any] with typing.Dict

- libs/agno/agno/agent/agent.py
- libs/agno/agno/playground/async_router.py
- libs/agno/agno/playground/sync_router.py
- libs/agno/agno/tools/decorator.py
- libs/agno/tests/unit/playground/test_image_support_file_upload.py
If a user used the playground app and made non-streaming requests, it would break on serialization.
Fixes this case-> https://discord.com/channels/965734768803192842/1346111375600123945
---
---
---
> Handle playground router non-streaming cases better

- libs/agno/agno/tools/calcom.py
- **Summary of changes**: Fixed the event_type_id initialization logic in CalComTools to properly prioritize the explicitly passed parameter over environment variables. This ensures that when users specify an event_type_id directly, it will be used correctly in API requests.
- **Related issues**: -.
- **Motivation and context**: Previously, when users passed an event_type_id to the CalComTools constructor but had no CALCOM_EVENT_TYPE_ID environment variable set, the passed value would be ignored and the default value of 0 would be used instead.
- **Environment or dependencies**: -.
- **Impact on metrics**: -.
---
---
---
Looking at the test logs, I can see that the integration tests are failing. The error appears to be related to …
> Fix CalComTools event_type_id initialization

- libs/agno/agno/agent/agent.py
Here is a setting that is unintuitive and in my opinion unexpected behavior before this change.
```
agent = Agent(stream=True, ...)
agent.run(...) # This will return a RunResponse
```
I would expect the `agent.run(...)` command to return a generator. The reason is because a default value was set for stream in the `run()` and `arun()) methods. This PR fixes this issue.
N/A
This change was done to enforce expected behavior with the Agent flags
- **Environment or dependencies**: Specify any changes in dependencies or environment configurations …
> Use the overrided stream value when necessary

- libs/agno/agno/media.py
- **Summary of changes**: use a Literal list of allowed MIME types instead of a class attribute, which doesn't work
- **Related issues**: Following up on https://github.com/agno-agi/agno/pull/2325, that introduced file handling for Claude and Gemini
The code currently fails with invalid attribute for `cls.VALID_MIME_TYPES`.
The simplest solution is to use a Literal type and let pydantic validate the value.
Potential but not concrete drawbacks:
* The exception raised changes from ValueError to ValidationError;
* In case someone wants to know which MIME types are supported, they'll have to use something like `typing.get_args(File.mime_type)` instead of `File.VALID_MIME_TYPES`. However, it should be noted that right now this list is not truly reflecting the supported types for a model …
> Fix validation of MIME types for files

- libs/agno/agno/utils/json_schema.py
- libs/agno/pyproject.toml
- libs/agno/tests/integration/agent/test_tool_parsing.py
**Summary of changes**:
The main problem: newish syntax for unions with `|` supported by Python 3.10 are of [type](https://docs.python.org/3.10/library/types.html#types.UnionType) `types.UnionType`, and didn't match `Union`. There's a very recently [completed issue on CPython](https://github.com/python/cpython/issues/105499) that will unify both (apparently for 3.14). See also this [MyPy warning](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#future-annotations-import-pep-563) about evaluating type hints.
Other problems:
- Only unions of two values were properly handled for optional values;
- Unions with more than two values and an optional one would only parse one of the values, dropping the others;
- Some code lines were never true (like `isinstance(arg_json_schema["type"], …
> Fix multiple issues with converting type hints to JSON Schema

- libs/agno/agno/models/openai/chat.py
This PR adds a role mapping compatibility layer in the OpenAI chat implementation to support seamless switching between Google Gemini and OpenAI models. This addresses a critical interoperability issue when migrating between different model providers.
- Added a new entry in the `role_map` dictionary that maps the "model" role to "assistant"
- This ensures that responses from different LLM providers maintain consistent role assignments when switching between providers
- Maintains backward compatibility with existing code
When working with different model providers, role naming conventions can vary. This mapping ensures that applications can switch between Google and OpenAI models without requiring code changes to handle different role terminologies.
The change has been tested with both …
> added a mapping for compatibility for switching between google and openai 

- cookbook/playground/teams_demo.py
- cookbook/teams/modes/route.py
- cookbook/teams/streaming.py
- cookbook/teams/streaming_async.py
- libs/agno/agno/playground/async_router.py
- libs/agno/agno/team/team.py
- libs/agno/pyproject.toml
- **E2B Tools:** Added E2B Tools to run code in E2B Sandbox
- **Teams Tools**: Add `tools` and `tool_call_limit` to `Team`. This means the team leader itself can also have tools provided by the user, so it can act as an agent.
- **Teams Instructions:** Improved instructions around attached images, audio, videos, and files. This should increase success when attaching artifacts to prompts meant for member agents.
- **MCP Include/Exclude Tools**: Expanded `MCPTools` to allow you to specify tools to specifically include or exclude from all the available tools on an MCP server. This is very useful for limiting which tools the model has access to.
- **Tool Decorator Async Support**: The `@tool()` decorator now supports async functions, including async pre and post-hooks.
- **Default …
> Release 1.2.5

- cookbook/models/openai/chat/basic.py
- cookbook/playground/mcp_demo.py
- libs/agno/agno/agent/agent.py
- libs/agno/agno/run/response.py
- libs/agno/agno/team/team.py
**Summary of changes**: 
- Removes history from `RunResponse.extra_data` as the messages are already stored in `RunResponse.messages` with a `from_history` tag. This makes storage of messages leaner
- Changed `num_history_responses` to `num_history_runs` to be more clear regarding the use of the variable. Since we add all messages from the number of runs specified, not just the responses.
Fixes #2500 
---
---
---
> improve-message-history-ag-2922

- libs/agno/agno/agent/agent.py
Sometimes knowledge base fails to deepcopy, but copy succeeds.
---
---
> Remove warning on deepcopy which gets triggered for some async knowledge bases

- cookbook/models/google/gemini/structured_output.py
- libs/agno/agno/models/google/gemini.py
- libs/agno/tests/integration/models/google/test_basic.py
- libs/agno/tests/integration/models/google/test_tool_use.py
Gemini still can't handle native structured outputs and tool calls simultaneously, but it can with JSON mode. 
---
---
> Update Gemini for structured outputs with tools

- libs/agno/agno/embedder/fastembed.py
Modified `FastEmbedEmbedder.get_embedding` to return a flat list of floats instead of a nested list, fixing an `ArrowNotImplementedError` when used with `LanceDb` in `PDFKnowledgeBase`. This ensures compatibility with LanceDB’s vector insertion requirements. Motivated by a runtime error encountered during local testing with `PDFKnowledgeBase`.
---
---
- **Testing**: Manually tested with a script inserting embeddings into `LanceDb` to confirm the fix resolves the `ArrowNotImplementedError`.
> Fix FastEmbedEmbedder to return flat list for LanceDb compatibility

- libs/agno/agno/knowledge/website.py
WebsiteKnowledgeBase doesn't pass chunking strategy to WebsiteReader making it impossible to use any other strategy in WKB.
This PR adds passing WKB strategy to reader ctor.
> Fix WebsiteReader initialization to include chunking strategy

- libs/agno/agno/agent/agent.py
- libs/agno/agno/reasoning/step.py
- libs/agno/agno/team/team.py
- libs/agno/tests/integration/models/openai/responses/test_basic.py
There were various cases where weaker models would have the tools in the run response, but no response content. This makes sure we can handle that.
Fixes #2595 
---
---
> Improve the response parsing from team members

- libs/agno/agno/models/google/gemini.py
Fixes a `TypeError: 'NoneType' object is not iterable` that occurs during streaming response parsing in `agno.models.google.gemini.parse_provider_response_delta`.
The error happens when the Gemini API returns `null` for the `"grounding_chunks"` key within grounding metadata. This PR ensures the `chunks` variable, holding the grounding chunks, is always an iterable list before being used in subsequent list comprehensions or iterations, preventing the error.
This issue is separate from the schema conversion problem addressed in PR #2686.
---
---
**Root Cause:**
This `TypeError` happens when the API response includes grounding metadata where `"grounding_chunks"` has a value of `null`. The current code uses `chunks = grounding_metadata.pop("grounding_chunks", [])`. If the key exists with a …
> Fix(gemini): Prevent TypeError when parsing null grounding_chunks

- libs/agno/agno/agent/agent.py
- send `reasoning_step` in the yield properly for `_run` and `_arun`
- synchronous data for `COT`, `Reasoning/Thinking/KnowledgeTools`
Loom walkthrough- https://www.loom.com/share/d8e02e657dca46d9b114353a84d73e03?sid=808b5ff7-d244-4c46-be4a-a6a3b6048f47
---
---
> fix reasoning event structure

- libs/agno/agno/models/aws/bedrock.py
- libs/agno/agno/models/azure/ai_foundry.py
- libs/agno/agno/models/cohere/chat.py
- libs/agno/agno/models/groq/groq.py
- libs/agno/agno/models/huggingface/huggingface.py
- libs/agno/agno/models/ibm/watsonx.py
- libs/agno/agno/models/litellm/chat.py
- libs/agno/agno/models/mistral/mistral.py
- libs/agno/agno/models/ollama/chat.py
- libs/agno/agno/utils/models/claude.py
Log warning messages when formatting input messages if they contain entities of unsupported format, e.g. video
> feat: log a warning msg when receiving input of unsupported type

- libs/agno/agno/document/reader/url_reader.py
- libs/agno/agno/document/reader/website_reader.py
Introduce `proxy` parameter for `URLReader` class to allow `httpx` to call url with proxy especially for workplace with strict network control.
---
>  feat(URL): add proxy parameter

- libs/agno/agno/document/reader/csv_reader.py
- libs/agno/agno/document/reader/pdf_reader.py
- libs/agno/agno/document/reader/website_reader.py
- libs/agno/agno/utils/http.py
Introduce `proxy` parameter for `PDFUrlReader` class to allow `httpx` to call url with proxy especially for workplace with strict network control.
(Issue number: #2801)
---
> feat(PDF): add proxy parameter

- libs/agno/agno/tools/mcp.py
The `tool.name in self.exclude_tools` check breaks by default as exclude_tools defaults to `None`. Adding a sanity check on `exclude_tools` to avoid
> fix(mcp): handle empty exclude_tools field

- libs/agno/agno/document/reader/website_reader.py
This fixes the problem with website reader where if the content does not have "content" tag the result would be empty. We want instead to return the page as text so that we return at least something. 
---
---
This should not break any existing code.
> Extracting website main content should return content as text if all else fails

- libs/agno/agno/tools/googlecalendar.py
Fixed default value for `send_updates` parameter in GoogleCalendarTools and improved parameter handling. The `send_updates` parameter now explicitly defaults to 'all'. 
---
---
Changes made to GoogleCalendarTools:
1. Fixed `send_updates` parameter to default to 'all' 
These changes improve the robustness of the Google Calendar integration and make the API more user-friendly.
> added option to Send Meeting notification to attendees

- libs/agno/agno/models/message.py
Sometimes the `tool_call_arguments` is already a dict. Pass it thru directly.
Sometime `tool_call_arguments` is already a `dict` - pass it thru directly to prevent json to load it again.
---
> Prevent json from loading dict

- libs/agno/agno/agent/agent.py
- libs/agno/agno/team/team.py
If a run has not yet happened, then the session in memory would not exist, but it could still exist in the DB. This avoids the agent failing.
Fixes #3078 
---
---
> Fix loading of sessions if no run has occurred

- cookbook/observability/weave_op.py
- libs/agno/agno/document/reader/csv_reader.py
- libs/agno/agno/document/reader/docx_reader.py
- libs/agno/agno/document/reader/firecrawl_reader.py
- libs/agno/agno/document/reader/json_reader.py
- libs/agno/agno/document/reader/pdf_reader.py
- libs/agno/agno/document/reader/s3/pdf_reader.py
- libs/agno/agno/document/reader/text_reader.py
- libs/agno/tests/unit/reader/test_csv_reader.py
- libs/agno/tests/unit/reader/test_docx_reader.py
- libs/agno/tests/unit/reader/test_json_reader.py
- libs/agno/tests/unit/reader/test_pdf_reader.py
- libs/agno/tests/unit/reader/test_text_reader.py
Fix for issue- https://github.com/agno-agi/agno/issues/3081 and https://github.com/agno-agi/agno/issues/2887
If in a folder- you have pdf files and lets say two of the files are named like this: `Auksute_Ramanauskaite-Skokauskiene.-.Laisves_deklaracija_ir_jos_signatarai.2009.LT.pdf` and `Auksute_Ramanauskaite-Skokauskiene.-.Partizanu_vadas_generolas_Adolfas_Ramanauskas-Vanagas.2007.LT.pdf`
A part of their names overlap and the pdf reader split them based on `_` so the insertion was happening with same name `Auksute_Ramanauskaite-Skokauskiene` for both files which resulted in the error 
We now use unique id in the readers to make it strict-
```
Document(
name=doc_name,
id=f"{doc_name}_{page_number}_{uuid.uuid4()}",  # Here
meta_data={"page": page_number},
content=page.extract_text(),
)
``` …
> fix: readers set unique id

- .github/workflows/test_on_release.yml
- libs/agno/tests/integration/models/cerebras/test_tool_use.py
> add workflow for cerebras

- .github/workflows/test_on_release.yml
- libs/agno/pyproject.toml
- scripts/model_tests_setup.sh
- scripts/run_model_tests.sh
House keeping:
- For each of the model tests, ensure it works if only the minimal packages are installed. I.e. to prevent that we accidentally require packages for all users.
Run locally- `sh scripts/model_tests_setup.sh <model_name>` for example-
`sh scripts/model_tests_setup.sh openai`
---
---
> chore: add a script to do model specific minimal setup installation on release

- libs/agno/agno/tools/replicate.py
Add support for both single FileOutput and iterable outputs from replicate.run. Improve error handling for unexpected output types.
The issue was:
The `replicate.run` returns a list of FileOutput rather than FileOutput
---
---
> fix(replicate): handle FileOutput and list of FileOutput

- libs/agno/agno/tools/shell.py
Refactored ShellTools.run_shell_command to correctly handle working directory changes by using the cwd parameter of subprocess.run() instead of prepending cd to the shell command. This resolves command execution failures caused by improper shell syntax in argument lists and improves robustness and cross-platform compatibility.
issue number: https://github.com/agno-agi/agno/issues/3218
> fix: use subprocess cwd instead of shell 'cd' to set working directory

- libs/agno/agno/tools/googlecalendar.py
Added conditional Google Meet link creation to the Google Calendar tools. The `create_event` method now accepts an `add_google_meet_link` parameter to optionally add a Google Meet link to calendar events.
---
---
The changes allow for more flexible event creation by making the Google Meet link optional. This maintains backward compatibility while adding new functionality.
> feat(googlecalendar): add conditional Google Meet link creation

- libs/agno/agno/tools/mcp.py
We were effectively ignoring the timeout value set in `SSEClientParms` or `StreamableHTTPClientParams` as we were not considering it when initializing the `ClientSession`. Now both ways to declare the read timeout work:
```python
server_params = SSEClientParams(url=server_url, timeout=10)
async def run_agent(message: str) -> None:
async with MCPTools(server_params=server_params, transport="sse") as mcp_tools:
...
async def run_agent(message: str) -> None:
async with MCPTools(server_params=server_params, transport="sse", timeout_seconds=10) as mcp_tools:
...
```
In case of collision we use the max.
> feat: better MCP timeout handling

- libs/agno/agno/knowledge/wikipedia.py
This way it doesn't change the user's provided topic when you set it to false.  Default is True to not change current behavior.
Added a parameter to WikipediaKnowledgeBase
---
---
> Added a parameter to configure auto_suggest in wikipedia.summary

- cookbook/agent_concepts/knowledge/custom/async_retriever.py
- cookbook/agent_concepts/knowledge/custom/retriever.py
update retriever cookbooks:
- the `knowledge_base` param need not be passed while using a custom retriever
- instead of local qdrant path usage, use it with docker, the local one keeps losing connections and does not work asynchronously.
---
---
> chore: update retriever cookbooks

- cookbook/evals/accuracy/accuracy_basic.py
- cookbook/evals/accuracy/accuracy_with_given_answer.py
Small cookbooks clarification 
- Add `num_iterations` on the basic cookbook
- Remove `num_iterations` on the `run_with_output` cookbook as it's not used/relevant there
> chore: clarify eval cookbooks

- cookbook/models/openai/chat/custom_role_map.py
- libs/agno/agno/models/openai/chat.py
Allow using a custom role map with the `OpenAIChat` class. 
Adding this because default role map fails for some OpenAI-like APIs, like Mistral's.
- [ x ] New feature
---
> feat: allow custom role map for OpenAIChat

- libs/agno/agno/vectordb/qdrant/qdrant.py
- libs/agno/tests/unit/vectordb/test_qdrantdb.py
This PR adds support for hybrid searches when using Qdrant as the vector store.
[qdrant/fastembed](https://github.com/qdrant/fastembed)'s BM25 is used for sparse embeddings by default(Customizable).
Qdrant's hybrid search reference:
https://qdrant.tech/documentation/concepts/hybrid-queries/#hybrid-search
---------
---
---
> feat: Qdrant hybrid search

- libs/agno/agno/vectordb/pgvector/pgvector.py
use reproducible content_hash in upsert as id
---
---
> fix: use content hash as id in upsert

- cookbook/models/mistral/structured_output_with_tool_use.py
- libs/agno/agno/models/mistral/mistral.py
- libs/agno/tests/integration/models/mistral/test_tool_use.py
Fixed an issue where Mistral failed to parse structured output with tool calls
---
---
> fix: Add mistral structured output and tool use parsing

- libs/agno/agno/models/google/gemini.py
- libs/agno/agno/models/openai/chat.py
- libs/agno/agno/models/openai/responses.py
- libs/agno/agno/utils/gemini.py
- libs/agno/agno/utils/models/openai_responses.py
- libs/agno/agno/utils/models/schema_utils.py
- libs/agno/agno/utils/whatsapp.py
- libs/agno/agno/workspace/helpers.py
- libs/agno/tests/integration/models/google/test_structured_response.py
- libs/agno/tests/integration/models/openai/chat/test_structured_response.py
- libs/agno/tests/integration/models/openai/responses/test_structured_response.py
- libs/agno/tests/unit/utils/test_gemini_dict_support.py
- libs/agno/tests/unit/utils/test_openai_responses.py
- libs/agno/tests/unit/utils/test_schema_utils.py
We had a user that needed to use a Dict type in structured outputs.
https://discord.com/channels/965734768803192842/1374774799351677009/1376519071910203473
The user was testing with Gemini, but I found the same issue in OpenAI.
**Problem:**
Pydantic models with Dict[str, int] fields (and other Dict types) were failing when used as response_schema for both OpenAI and Gemini models due to schema format incompatibilities.
**OpenAI Issue**
Error: "Extra required key 'rating' supplied"
Root Cause: The sanitize_response_schema function was incorrectly adding Dict fields to the required array, but OpenAI's structured outputs don't expect Dict fields (which use additionalProperties) to be listed as required
Solution: Modified sanitize_response_schema to exclude Dict fields from the required array …
> fix: Gemini type fix for integers

- libs/agno/agno/agent/agent.py
- libs/agno/agno/team/team.py
- libs/agno/tests/integration/agent/test_agent_with_storage_and_memory.py
Session name is incorrectly cleared on the first call. This fixes that and ensures proper management of run and session state variables.
---
---
> fix: session name persistance

- cookbook/tools/searxng_tools.py
- libs/agno/agno/models/base.py
- libs/agno/agno/tools/searxng.py
Updated import from `from agno.tools.toolkit import Toolkit` to `from agno.tools import Toolkit` since it was causing the incorrect initialization of the tool causing an `AttributeError: 'Searxng' object has no attribute 'include_tools'`
Fixes an issue I talked about in #3423 also
---
---
> [fix] searxng toolkit import for tool initialization

- libs/agno/agno/eval/accuracy.py
We were missing some logic to handle monitoring when evaluating Teams in the run function of AccuracyEval
> fix: accuracy evals monitoring

- libs/agno/agno/tools/mcp.py
When running MCP with stdio, the environment variables passed to the server/client should not include the whole environment of the caller, as it creates a serious security issue.
The `mcp` client implementation already addressed the issue: https://github.com/modelcontextprotocol/python-sdk/issues/99.
The simplest solution is to just use their utility function for filtering the environment instead of dumping the whole `os.environ` to the MCP client.
---
> fix: Do not leak the full host env vars into MCP tools

- libs/agno/agno/utils/string.py
- libs/agno/tests/unit/utils/test_string.py
Fixes a critical bug in `parse_response_model_str` where field names were incorrectly converted to lowercase during the cleanup phase, especially when JSON values included quotes. This impacted models relying on mixed-case field names (e.g., `Supplier_name`, `newData`) and broke structured output parsing. The bug was traced to the `escape_quotes_in_values` function in `string.py`, which called `.lower()` on keys unnecessarily.
issue number: #3493 
---
---
Ran:
```bash
python3 -m pytest tests/unit/utils/test_string.py -v
> fix: preserve field name case in structured output parsing

- libs/agno/agno/agent/agent.py
- libs/agno/agno/memory/v2/memory.py
- libs/agno/agno/team/team.py
Agents/teams that are in teams have to work from a copy of memory. This is required to ensure consistent management of sessions.
This however does break a few cases for agents/teams that are used standalone. This change fixes those case.
In that case where teams are used, then memory has to be access from the actual team/agent instance.
---
---
> Fix: agents deepcopy memory

- libs/agno/agno/team/team.py
- libs/agno/tests/unit/team/test_team.py
Ensure that teams will still work if the user doesn't supply an agent/team ID or name to members.
---
---
> fix: Teams - Ensure we use UUID as a backup member_id

- libs/agno/agno/tools/exa.py
Currently, `ExaTools` is using `json.dumps` with its default `ensure_ascii=True` option, which renders non-ASCII characters as something like \uffff, unnecessarily burdening the LLM to parse those characters.
This PR fixes that in [2127cf5](https://github.com/agno-agi/agno/pull/3732/commits/2127cf568cda354ae8ffa3dee0e41dbfc793d358)
---
- [ NOT APPLICABLE ] Documentation updated (comments, docstrings)
- [ NOT APPLICABLE ]  Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
- [ NOT APPLICABLE ]  Tests added/updated (if applicable)
---
> fix: display non-ascii chars correctly in ExaTools result

- libs/agno/agno/embedder/fastembed.py
Fix a Bug. The raw **embedding_list** is a numpy **ndarray**, but the function need return a  **List[float]**, so need to convert ndarry to normal list[float]
---
changed file is agno.embedder.fastembed.FastEmbedEmbedder
> fix get_embedding function return value not List[float] bug

- cookbook/agent_concepts/tool_concepts/custom_tools/tool_hook_with_state.py
- cookbook/evals/performance/team_response_with_memory_multi_user.py
- cookbook/evals/performance/team_response_with_memory_simple.py
- libs/agno/agno/eval/performance.py
- libs/agno/agno/memory/v2/db/redis.py
- libs/agno/pyproject.toml
- libs/agno/tests/integration/agent/test_user_confirmation_flows.py
- libs/agno/tests/integration/agent/test_user_input_flows.py
- libs/agno/tests/integration/teams/test_memory_impact.py
- **Memory Growth on Performance Evals**: Added `memory_growth_tracking` as an attribute on `PerformanceEval` to enable additional debug logs for memory growth.
- **Gemini 2.5 Metrics:** Fixed Gemini metrics to correctly include “thinking” tokens.
- **Claude tool calling:** Fixed a bug related to parsing function call responses when using Claude models
> chore: Release 1.7.2

- libs/agno/agno/agent/agent.py
- libs/agno/tests/integration/agent/test_metrics.py
The calculate_metrics method was counting historical messages from previous runs, causing inflated token counts. Added check to exclude history messages to match the behavior of aggregate_metrics_from_messages.
Fixed a bug where session metrics were counting tokens from historical messages multiple times. 
When add_history_to_messages=True is enabled, the calculate_metrics method was including messages
from previous runs, causing session metrics to show about 2x the actual token usage.
The fix adds a check to exclude historical messages, matching how aggregate_metrics_from_messages already works. 
Please, let me know if I understood the problem wrong.
---
- [X ] Self-review completed
---
How to reproduce the bug:
1. Create an agent with …
> [fix] Fix session metrics counting history messages multiple times

- libs/agno/agno/document/reader/base.py
- libs/agno/agno/team/team.py
Don't send expected output if team member already has it set
#3910 
#3903 
---
---
> fix: Team expected output don't override member

- cookbook/tools/mem0_tools.py
- cookbook/workflows/async_blog_post_generator.py
- libs/agno/agno/models/litellm/chat.py
- libs/agno/agno/tools/linkup.py
- libs/agno/agno/workflow/workflow.py
- libs/agno/tests/integration/models/litellm/test_tool_use.py
- libs/agno/tests/integration/workflows/test_async_workflows.py
When Agno is run through LiteLLM against OpenAI chat models (eg. GPT4.1), multiple streamed tool_calls lose their individual argument streams. Each call’s index arrives correctly from OpenAI, but Agno drops that index while converting LiteLLM deltas, so every chunk is treated as index: 0. The argument strings for different tools are then concatenated, producing invalid JSON.
Example to test-
```py
import asyncio
from agno.agent import Agent
from agno.models.litellm import LiteLLM
from agno.tools.exa import ExaTools
agent = Agent(
tools=[ExaTools()],
model=LiteLLM(
id="gpt-4.1-2025-04-14",
),
add_history_to_messages=False,
stream_intermediate_steps=True,
show_tool_calls=True,
debug_mode=True,
markdown=True,
)
asyncio.run(
agent.aprint_response(
"Write a detailed analysis on Trumps tariffs. …
```
> fix: mangled litellm multiple streaming tool calls

- libs/agno/agno/embedder/openai.py
fixes: https://github.com/agno-agi/agno/issues/3991
OpenAIEmbedder() wrong dimensions for text-embedding-3-large
---
---
> fix: openai embedder dim len

- libs/agno/agno/agent/agent.py
- libs/agno/agno/team/team.py
- libs/agno/tests/unit/agent/test_agent_knowledge.py
- libs/agno/tests/unit/team/test_team.py
Fixed the issue where the default value of `num_documents` was not set before calling the retriever. Previously, the default value assignment for `num_documents` was misplaced, which could cause the retriever function to receive an incorrect parameter value in some cases.
Key changes:
- Moved the logic for setting the default value of `num_documents` before the retriever call
- Ensured both synchronous and asynchronous methods in Agent and Team classes handle the default value correctly
- Added corresponding unit tests to verify the fix
---
---
**Problem Description:**
In the `get_relevant_docs_from_knowledge` and `aget_relevant_docs_from_knowledge` methods of the `Agent` and `Team` classes, the default value assignment for the `num_documents` parameter was misplaced. The previous …
> fix: set num_documents default before retriever calls

- libs/agno/agno/utils/response.py
Our `format_tool_calls` was dropping tool calls with no args. Ultimately this means users couldn't see those calls when using `show_tool_calls=True`.
This is how it no-args calls look like now:
> fix: show tool calls with no args on print and aprint

- libs/agno/agno/tools/function.py
(#3790)
Instead we now gracefully handle this conflict and log it for reference.
- Fixed comment to accurately reflect code logic: now mentions both async generators and coroutines
- Fixed incorrect usage of isasyncgen() vs isasyncgenfunction() when checking function objects
- Fixed incorrect usage of isgenerator() vs isgeneratorfunction() when checking function objects
- Added missing imports for iscoroutinefunction and isgeneratorfunction
- Removed unused isasyncgen import in _build_nested_execution_chain_async
These fixes ensure proper type checking for async/generator functions and improve cache handling logic.[修复] 修正函数异步类型检查错误并更新注释，并改进了缓存处理逻辑。
These fixes ensure proper type checking for async/generator functions and improve cache handling logic.
- [ *] Bug fix
---
- [*] Code complies …
> fix: incorrect async type checking and pydantic version conflict in function.py

- libs/agno/agno/team/team.py
- libs/agno/pyproject.toml
- libs/agno/tests/integration/teams/test_event_streaming.py
- libs/agno/tests/integration/teams/test_team_session_state.py
- **Output model**: Added support for `output_model` on Agents and Teams to generate the final response from `output_model` instead of `model`
- **Support for OpenAI Flex Processing**: Added `service_tier` to `OpenAIChat` and `OpenAIResponses`.
- **Print Response:**
- Fixed `show_member_responses` not working correctly on `Team`
- Fixed printing of MCP responses on streamable HTTP
- **Session State on Team**: Fixed precedence for session state from sessions DB.
- **`YouTubeTranscriptApi` has no attribute `get_transcript` :**
- The `YoutubeTranscriptApi` is updated and now uses `.fetch(video_id)` for getting transcripts.
- **HITL streaming:**
- Added the required attributes- `tools_requiring_confirmation`, `tools_requiring_user_input`, `tools_awaiting_external_execution` on the class …
> chore: Release 1.7.8

- cookbook/agent_concepts/rag/agentic_rag_with_reranking.py
- libs/agno/agno/vectordb/pgvector/pgvector.py
- libs/agno/tests/integration/teams/test_event_streaming.py
- libs/agno/tests/integration/teams/test_team_session_state.py
add missing reranker in pgvector hybrid search
---
---
> fix: add reranker in pgvector hybrid search

- libs/agno/agno/team/team.py
Receiving a list of `Message` as input of `Team.arun` was valid based on the type signature, but broke when getting the user message
> fix: handle receiving a list of Message as input for team arun

- cookbook/agent_concepts/user_control_flows/external_tool_execution_async_responses.py
- libs/agno/agno/models/openai/responses.py
- libs/agno/tests/integration/models/openai/responses/test_tool_use.py
- libs/agno/tests/unit/models/openai/test_openai_responses_id_handling.py
Normalizes tool call IDs to Responses API call_id (fixes gpt-4.1-mini external tool execution).
- Normalize tool call identifiers to use call_id consistently in OpenAIResponses.
- Apply normalization in:
- _format_messages: set both id and call_id from call_id (fallback to id).
- parse_provider_response: set tool call id to call_id.
- _process_stream_response (streaming): set tool call id to call_id.
- The Responses API expects function_call_output to reference the prior call_id. We were using a different ID (fc_...) leading to:
> 400 “No tool output found for function call …” with gpt-4.1-mini.
---
---
> Feat: Normalize tool call identifiers

- libs/agno/agno/tools/github.py
- libs/agno/tests/unit/tools/test_github.py
Fixes IndexError in GitHub Tools search_code function when processing pagination with empty results. The issue occurred when PyGithub's PaginatedList slicing operation failed on empty search results, causing the search functionality to crash.
Fixes #4242
---
---
**Issue:** 
The original implementation used list slicing `code_results[:50]` which failed when search results were empty, causing an IndexError that crashed the search functionality.
**Solution:**
- Implemented explicit page-by-page iteration using the `get_page()` method
- Added proper error handling for empty result sets
- Maintains existing functionality while improving reliability (still gets the same number of results up to 60 but won't crash)
**Testing:**
Updated test mocks to properly simulate pagination behavior. The test …
> [fix] GitHub tool search_code pagination IndexError with empty results

- libs/agno/agno/models/openai/chat.py
feat(openai): support both httpx.Client and httpx.AsyncClient in OpenAIChat
Updated OpenAIChat to allow passing either httpx.Client or httpx.AsyncClient to the `http_client` parameter. This improves flexibility and aligns behavior with the official OpenAI client, where sync clients can accept both sync and async httpx clients.
Maintains backward compatibility. Users can now pass either sync or async httpx clients depending on their needs.
> [feat] allow OpenAIChat to accept both httpx.Client and httpx.AsyncClient

- libs/agno/agno/media.py
- `from_artifact()` of `Image` was missing content in its return along with url, so if the generated image is not a url but a encoded content this would fail, or vice-versa. 
---
---
> fix: media artifact validation error

- libs/agno/agno/tools/e2b.py
Update the E2BTools class to use Sandbox.create() from the latest e2b_code_interpreter SDK, replacing the deprecated Sandbox() initialization. No other functionality changed.
---
---
> [refactor] Update E2B tool to use Sandbox.create

- cookbook/agent_concepts/other/location_instructions.py
- libs/agno/agno/team/team.py
- libs/agno/agno/utils/location.py
The Team class was missing the time zone identifier feature from the Agent class, so I added it by copying the implementation.
Additionally, the default API used in get_location() had strange limitations that blocked my VPS IP without explanation (I suspect running LLM agents was flagged as “strange activity”). I replaced it with a more stable API, which allows about 45 queries per minute (though I may be mistaken about the exact limit).
---
---
> [fix] Add missing time zone feature to Team and update default API for get_location

- libs/agno/agno/workflow/v2/workflow.py
running workflow v2 like this shows this error-
```py
import asyncio
from typing import AsyncIterator, Union
from agno.workflow.v2.workflow import Step, StepInput, StepOutput, Workflow, WorkflowRunResponseEvent
class TestWorkflow:
def __init__(self):
self.workflow = Workflow(
name="Test Workflow",
description="Test workflow",
steps=[Step(
name="Test Step",
executor=self.test_step, # <--
)],
)
async def test_step(step_input: StepInput) -> AsyncIterator[Union[WorkflowRunResponseEvent, StepOutput]]:
yield StepOutput(content="Test Step")
async def run(self):
await self.workflow.aprint_response(
message="Test",
markdown=True,
stream=True,
stream_intermediate_steps=True,
)
async def main():
test_workflow = TestWorkflow()
await test_workflow.run()
if __name__ == "__main__":
asyncio.run(main()) …
```
> fix: workflow session state error 

- libs/agno/agno/utils/models/claude.py
Claude models were incorrectly marking all optional MCP tool parameters as required,
causing validation errors when Claude generated invalid default values in the args
Removed the faulty auto-requirement logic in `format_tools_for_model()` function in
`agno/utils/models/claude.py` that was making all non-nullable parameters required when no
explicit required parameters existed.
- **File**: `agno/utils/models/claude.py`
- **Lines**: 310-316
- **Type**: Removed 7 lines of buggy logic
- Verified Claude agents now work correctly with MCP tools
- Tool calls no longer include invalid default parameters
- Schema now respects original tool author's intent for optional vs required parameters
- [V] Bug fix
---
- [V] Code complies with style guidelines
- [V] Ran format/validation scripts …
> fix: removed code that caused claude send all mcp tool args as required

- libs/agno/agno/team/team.py
I was hitting an issue where "history" was and empty array []. But since we are checking for None here, it was passing the empty array in instead of the member task - this results in a bug where member task isn't actually being passed in
> [fix] fix history check in member task run

- libs/agno/agno/agent/agent.py
- libs/agno/agno/team/team.py
- We shouldn't raise in `get_messages_for_session` if the session is not found - that's expected in some cases
> fix: dont raise if no session when getting chat history

- libs/agno_infra/agno/aws/app/streamlit/streamlit.py
The Streamlit class uses `@dataclass` decorator while inheriting from AwsApp (a Pydantic model), causing initialization conflicts that prevent recognition of inherited parameters like `ecs_cluster`.
Users get: `TypeError: Streamlit.__init__() got an unexpected keyword argument 'ecs_cluster'`
- AwsApp is a Pydantic model with its own field validation system
- `@dataclass` generates its own __init__ method that conflicts with Pydantic's initialization
- This prevents inherited AwsApp fields from being recognized
- Remove `@dataclass` decorator from Streamlit class
- Use regular class inheritance like FastApi already does
- Maintains all existing functionality while fixing parameter inheritance
---
---
Add any important context (deployment instructions, screenshots, security considerations, …
> [fix] Remove @dataclass decorator from Streamlit class to resolve AwsApp parameter inheritance

- cookbook/agent_os/interfaces/whatsapp/readme.md
For the new whatsapp interface the correct address of the webhook should be "your-domain/whatsapp/webhhok"
---
---
> fix:whatsapp documentation change

- libs/agno/agno/tools/googlesearch.py
This PR fixes a parameter name issue in the Google search function. The change updates the parameter from num to num_results when calling the search function from the googlesearch-python package, which is the correct parameter name according to the library's API. This small but important fix prevents potential runtime errors when using Google search functionality and ensures compatibility with the googlesearch library.
This PR fixes the issue, issue number: #4593
---
---
> [fix] update parameter name in Google search function for consistency

- libs/agno/agno/agent/agent.py
Updates type definition of `tools` argument of `Agent` constructor and `Agent.set_tools()` method to follow type annotation best practices.
Addresses: https://github.com/agno-agi/agno/issues/4643
---
---
My first commit, consider me clueless and dangerous :) I ran `format.sh` and `validate.sh` but no other tests.
> Change List[] (invariant) annotation to Sequence[] (covariant) for Agent tools

- cookbook/agent_os/mcp/enable_mcp_example.py
- cookbook/agent_os/mcp/mcp_tools_advanced_example.py
- cookbook/agent_os/mcp/mcp_tools_example.py
- cookbook/agent_os/mcp/mcp_tools_existing_lifespan.py
Ensures agentos mcp examples use sqlite and removed mastra mcp in example in favour of brave search mcp
---
---
> fix: Remove mastra mcp from example and move to sqlite

- libs/agno/agno/models/base.py
This is a patch
We are overwriting tool call ids, probably an issue with parallelization specifically - anyway this ensures we don't.
---
---
> fix: Don't overwrite tool call ids each time - this is a patch for now as the issue is annoying

- libs/agno/agno/agent/agent.py
- libs/agno/agno/models/base.py
- libs/agno/agno/team/team.py
fixes: https://github.com/agno-agi/agno/issues/4670
we currently use the `send_media_to_model` flag for the case where the input image to agent is to be accessed by a tool and should not be available to the model.
In this usecase if we use a tool to generate an image (custom or dalle) and using a non multimodal model, so in this case case we append the tool generated media now as a user message to model, we can also use the same `send_media_to_model` to decide to not send to model, otherwise the non multimodal model throws error.
---
---
> fix: improve functionality of send_media_to_model flag

- libs/agno/agno/os/utils.py
fixes: https://github.com/agno-agi/agno/issues/4726
The `/sessions/<session_id>/runs` endpoint does not return `run_input` in case of error as it references it from `step_executor_runs` and its empty if the workflow hasn't run yet, so in this case we fallback to directly get it from `input`.
---
---
> fix: run_input not being populated in session runs endpoint if workflow raises error

- libs/agno/agno/workflow/workflow.py
fixes: https://github.com/agno-agi/agno/issues/4742
early stop functionality in workflow was not updating the last output properly for non stream cases
Before: 
After: 
---
---
> fix: early stop in workflow to return correct last output

- libs/agno/agno/run/base.py
- libs/agno/tests/unit/run/test_run_events.py
Fixes a bug on Agent OS when output schema includes a non serializable type 
---
---
> fix: agentos datetime serialization

- libs/agno/agno/db/in_memory/in_memory_db.py
We were wrongly returning an outdated session in the `upsert_session` method of `InMemoryDb`
Fixes https://github.com/agno-agi/agno/issues/4844
> fix: session upsert for InMemoryDB

- libs/agno/agno/models/openai/responses.py
Currently supported values of reasoning_effort are minimal, low, medium, and high
https://platform.openai.com/docs/api-reference/chat/create#chat-create-reasoning_effort
---
> chore: update reasoning_effort options to include 'low'

- libs/agno/agno/run/base.py
- libs/agno/agno/utils/serialize.py
- libs/agno/agno/workflow/types.py
Issue: `WebSocketHandler.handle_event()` and `handle_dict()` methods in `types.py` failed to serialize datetime/date objects when sending workflow events via WebSocket, causing "Object of type datetime is not JSON serializable" errors.
Before:
After:
---
---
> fix: json serialize issue in websocket

- libs/agno/agno/models/anthropic/claude.py
- libs/agno/agno/utils/streamlit.py
- libs/agno/tests/integration/models/anthropic/test_multimodal.py
- libs/agno/tests/integration/models/anthropic/test_prompt_caching.py
Updates the default Anthropic Claude model from `claude-3-5-sonnet-20241022` to `claude-sonnet-4-5-20250929`.
- Updated `Claude` class default model ID to `claude-sonnet-4-5-20250929` (line 62 in `claude.py`)
- Updated Streamlit helper to include the new model ID in the default list
- Fixed integration tests to use supported Claude 4 model IDs:
- `test_multimodal.py`: Now uses `claude-sonnet-4-20250514` (Claude Sonnet 4)
- `test_prompt_caching.py`: Now uses `claude-sonnet-4-5-20250929` (Claude Sonnet 4.5)
Claude Sonnet 4.5 is Anthropic's latest model released on September 29, 2025. According to [Anthropic's official documentation](https://docs.anthropic.com/en/docs/about-claude/models), it is "our best model for complex agents and coding, with the highest intelligence across most tasks." …
> feat: default Claude agents to Sonnet 4.5

- libs/agno/agno/os/utils.py
- `session_name` is coming empty in the api `sessions?type=workflow` when first step is a custom function for workflows where events are not yielded
---
---
> fix: custom function step workflows empty session name

- libs/agno/agno/os/app.py
- libs/agno/agno/os/mcp.py
- libs/agno/tests/integration/os/test_custom_fastapi_app.py
This updates how we handle MCP lifespans in the OS, fixing multiple problems:
- MCP tools work with AgentOS with a base_app
- Fixes https://github.com/agno-agi/agno/issues/4942
- `enable_mcp_server` works with AgentOS with a base_app
- MCP tools work inside our AgentOS MCP server
> feat: better handle of MCP lifecycle in the AgentOS
