phi/knowledge/base.py
phi/knowledge/website.py

wiki function fix

---

cookbook/ollama/who_are_you.py

Refactor `who_are_you.py` to simplify code and adding temperature.

Refactor `who_are_you.py` to simplify code and adding temperature.

---

CONTRIBUTING.md

This  guides outlines the essential steps for adding a new vector database to the project, from setting up the environment to submitting a pull request for review.

documentation

---

cookbook/knowledge/text.py

This pull request adds a Text KnowledgeBase Cookbook to the repository. The cookbook includes code snippets and explanations on how to use the TextKnowledgeBase class, initialize the Assistant with the knowledge base, load the knowledge base, and use the assistant to get responses from the knowledge base.

Add Text KnowledgeBase Cookbook

---

phi/cli/console.py
phi/cli/entrypoint.py
pyproject.toml

- Auto initialize phi if it doesnt exist

Auto initialize phi

---

cookbook/knowledge/arxiv.py

Add ArXiv KnowledgeBase Cookbook

---

cookbook/knowledge/wikipedia_assistant.py

This PR creates the `wikipedia_assistant.py` file in the `cookbook/knowledge` directory to serve as an example for users using the WikipediaKnowledgeBase.
Issue: https://github.com/phidatahq/phidata/issues/91

Create Wikipedia cookbook

---

cookbook/hermes2/exa_kg.py
phi/tools/exa.py

Adds [ExaTools](https://exa.ai) and example of how it can be used within `phidata`
To reproduce:
- `ollama run adrienbrault/nous-hermes2pro:Q8_0 'what is autopoietic ergodicity and embodied gradualism'`
- sign up get your API key here https://dashboard.exa.ai/overview
- set `EXA_API_KEY` environment variable to the key you generate
- from repository root run `cookbook/hermes2/exa_kg.py`

ExaTool and example

---

phi/tools/exa.py

Update `ExaTools` to include `search_exa_with_contents`
Tested by running `python cookbook/hermes2/exa_kg.py`
https://github.com/phidatahq/phidata/assets/22579644/e1f762f0-caee-4a30-8ff0-72cb76b62f75
cc: @bmorphism

Update ExaTools to include `search_exa_with_contents`

---

.gitignore
phi/file/local/txt.py

Add local text file to pair with csv file.

add text local file

---

cookbook/knowledge/json.py

This pull request adds a Cookbook for using the JSON knowledge base in the project. The Cookbook provides an example of how to initialize the JSONKnowledgeBase, load the knowledge base, and use the Assistant with the knowledge base.

Add Cookbook for JSON knowledge base

---

cookbook/mistral/app.py

Fixes [issue](https://github.com/phidatahq/phidata/issues/167)
cc: [arw357](https://github.com/arw357)

Fix mistral cookbook

---

cookbook/integrations/pinecone/assistant.py
phi/vectordb/pineconedb/pineconedb.py

Fixed upsert and search issues with pinecone assitant

Bug pinecone assistant

---

cookbook/llms/gemini/assistant.py

The Gemini model used in the `assistant.py` file has been upgraded from `gemini-1.0-pro-vision` to `gemini-1.5-pro-preview-0409`. This change likely brings improvements or new features to the language model.

feat(gemini): upgrade Gemini model version

---

phi/llm/ollama/chat.py

Added more detailed metrics to logger that help characterize an LLM's performance.

More detailed LLM performance metrics added to Logger.

---

phi/cli/auth_server.py

add check_port to get_port_for_auth_server

---

phi/embedder/voyageai.py
pyproject.toml

This adds support for using voyageai's embedding models as an embedder.

Add voyageai embedder

---

phi/tools/searxng.py

This PR adds a tool to allow assistants to use a [SearXNG](https://github.com/searxng/searxng) instance to search the web for information from various sources.

Add SearXNG tool

---

cookbook/llm_os/README.md

Fix typo in README.md (llm_os)

Fix typo in README.md (llm_os)

---

phi/tools/pubmed.py

To test:
phidata\cookbook\tools\pubmed.py

switch http client packages

---

phi/assistant/assistant.py

https://github.com/phidatahq/phidata/issues/259

fix get_chat_history type error

---

cookbook/tools/exa_tools.py
phi/tools/exa.py

Adding a feature to ExaTools. Users would like to use Exa's default domain checker.

update exa tool to include domains

---

phi/vectordb/qdrant/qdrant.py

fix: error message

---

phi/tools/postgres.py

Added a read-only tool for Assistants to connect to a PostgreSQL database. This is based on the DuckDbTools, sans write operations.

Basic PostgreSQL Tool

---

phi/embedder/azure.py
tests/test_azure_openai_embedder.py

1. embedder: support azure openai deployment
2. tests: add test_azure_openai_embedder

 add-azure-openai-embedder

---

phi/storage/assistant/singlestore.py
phi/vectordb/singlestore/s2vectordb.py
phi/vectordb/singlestore/s2vectordb2.py

Resolved the Unicode errors we were getting while spinning up the RAG Assistant due to storage classes. I added doc strings where needed.

Corrected SingleStore vector and conversation storage files

---

phi/tools/spider.py

This PR is inspired by #239, and adds [Spider](https://github.com/spider-rs/spider) search functionality to provide more options for developers when they need agents to use a search engine.
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

Add Spider Tool

---

cookbook/llms/cohere/assistant.py
phi/llm/cohere/chat.py

**Cohere Class Update**
**Changes:**
**Updated to Latest API Specifications:**
- The Cohere class has been updated to align with the latest Cohere API specifications.
**Default Model Configuration:**
- The command-r-plus model is now set as the default model for Cohere.
**Metrics Storage:**
- Added functionality to store metrics such as `input_tokens` and `output_tokens` for better tracking and analysis.
**Data Type Enhancements:**
- Updated data types to comply with the latest Cohere version, ensuring compatibility.

cohere-llm-fix-phi-888

---

cookbook/assistants/vision.py

- change image_url value to object from string

fix: change image_url value to object from string

---

cookbook/tools/googlesearch_1.py
phi/tools/googlesearch.py

Add a "Google Search Tool" based on the googlesearch-python scraper.
+ add an example on cookbok.

Google Search tool + cookbook example.

---

cookbook/tools/spider_tools.py
phi/tools/spider.py

[Screencast from 2024-07-15 09-01-13.webm](https://github.com/user-attachments/assets/b016d48f-69f6-4976-9b8b-f5fef11d6334)
With docs in this PR https://github.com/phidatahq/phidata-docs/pull/42
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

Add Scrape & Crawl tools to SpiderTools

---

evals/.gitignore
evals/llms/openai/calculator.py

Run `python evals/llms/openai/calculator.py`
https://github.com/user-attachments/assets/af4d3d60-890a-4dc2-9a12-262b5df18462

Evals: Calculator

---

cookbook/advanced_rag/pinecone_hybrid_search/01_download_text.py
cookbook/advanced_rag/pinecone_hybrid_search/02_upsert_pinecone.py
cookbook/advanced_rag/pinecone_hybrid_search/03_hybrid_search.py
cookbook/advanced_rag/pinecone_hybrid_search/README.md
cookbook/advanced_rag/pinecone_hybrid_search/requirements.txt

A powerful AI stack that includes Phidata Asistant, LlamaIndex Advanced RAG, and Pinecone Vector Database.
This empowers the Phidata Assistant a way to search its knowledge base using keywords and semantic search.

add pc-hybrid-search

---

phi/llm/groq/groq.py

Solves #1065
See explanation in #1065

fix: ignore output_model when using tools with groq

---

cookbook/examples/scraping/app.py
phi/tools/jina_tools.py

Fix jina tools

---

phi/playground/playground.py

Feat: get all sessions and session by id endpoint

---

phi/playground/playground.py

First merge #1134  into this PR

Feat: playground agent rename endpoint

---

cookbook/agents/agent.py
phi/vectordb/base.py
phi/vectordb/lancedb/lancedb.py

- I saw there aren't any existing testing suite for vdbs so I just manually tested on a cookbook example by replacing the vdb
- Not yet. I was planning to make a separate PR to this repo https://github.com/phidatahq/ai-cookbook
- How do I update the docs?

Add hybrid search and reranking support in LanceDB vectorstore

---

cookbook/providers/openai/structured_output.py
phi/agent/agent.py
phi/playground/playground.py

Changes:
- Fixes the response when`output_model` is provided to this Agent

fix-agent-output-model-phi-1236

---

phi/playground/playground.py

Improvement: Add title content to /sessions/all endpoint

---

phi/api/user.py
phi/cli/operator.py

Use existing auth token instead of generating a new one on cli auth

Use existing auth token instead of generating a new one on cli auth

---

cookbook/agents/structured_output.py
cookbook/agents/telemetry.py
phi/agent/agent.py
phi/agent/response.py
phi/memory/agent.py
phi/model/base.py
phi/model/openai/chat.py
phi/model/response.py

- Add a response model instead of output model
- Stream intermediate events in runs
- OpenAI structured outputs

Agent class updates

---

cookbook/knowledge/website_pinecone_kb.py
phi/vectordb/pineconedb/pineconedb.py

updating pinecone with new sdk

update pinecone integration

---

CONTRIBUTING.md
scripts/_utils.bat
scripts/create_venv.bat
scripts/format.bat
scripts/install.bat

'print_heading' was not found + erratic behaviour
+ replace 'echo' with 'print_heading' in 'create_venv.bat'
+ fix doc:  'create_venv_win.bat' to 'create_venv.bat

fix batch scripts

---

phi/llm/cohere/chat.py

Changes:
- Updated the CohereChat streaming data types to the latest SDK

fix-cohere-llm-data-types-phi-1256

---

cookbook/llms/deepseek/README.md
cookbook/llms/deepseek/pydantic_output.py
cookbook/llms/deepseek/tool_call.py
phi/llm/deepseek/__init__.py
phi/llm/deepseek/deepseek.py

Inspired by #178 
Makes `from phi.llm.deepseek import DeepSeekChat` possible (just like it is done in #178)
[deepseek.webm](https://github.com/user-attachments/assets/6b158a37-9bd6-4eba-8800-a866db7290d8)
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

Add deepseek support

---

phi/llm/ollama/chat.py

Fix: append correct latest user message when using Ollama

---

cookbook/llms/claude/prompt_caching.py
phi/llm/anthropic/claude.py

Changes:
- Ability to cache system prompt using Claude LLM
- Cookbook to showcase prompt caching

system-prompt-caching-claude-llm-phi-1299

---

phi/app/base.py

chore: update base.py

---

cookbook/tools/apify_tools.py
cookbook/tools/arxiv_tools.py
cookbook/tools/calculator_tools.py
cookbook/tools/crawl4ai_tools.py
cookbook/tools/csv_tools.py
cookbook/tools/duckdb_tools.py
cookbook/tools/duckduckgo.py
cookbook/tools/email_tools.py
cookbook/tools/exa_tools.py
cookbook/tools/file_tools.py
cookbook/tools/firecrawl_tools.py
cookbook/tools/googlesearch_tools.py
cookbook/tools/hackernews.py
cookbook/tools/newspaper4k_tools.py
cookbook/tools/pubmed.py
cookbook/tools/python_tools.py
cookbook/tools/resend_tools.py
cookbook/tools/serpapi_tools.py
cookbook/tools/shell_tools.py
cookbook/tools/spider_tools.py
cookbook/tools/sql_tools.py
cookbook/tools/tavily_tools.py
cookbook/tools/website_tools.py
cookbook/tools/wikipedia_tools.py
cookbook/tools/yfinance_tools.py
cookbook/tools/youtube_tools.py
cookbook/tools/zendesk_tools.py
phi/tools/crawl4ai_tools.py
phi/tools/newspaper_tools.py

Changes:
- Tool cookbooks added for Agent class

agent-tools-update-phi-1487

---

cookbook/providers/claude/structured_output.py
cookbook/providers/google/structured_output.py
cookbook/providers/ollama/README.md
cookbook/providers/ollama/agent.py
cookbook/providers/ollama/agent_stream.py
cookbook/providers/ollama/basic.py
cookbook/providers/ollama/basic_stream.py
cookbook/providers/ollama/data_analyst.py
cookbook/providers/ollama/finance_agent.py
cookbook/providers/ollama/structured_output.py
cookbook/providers/ollama/web_search.py
phi/model/anthropic/claude.py
phi/model/ollama/__init__.py
phi/model/ollama/chat.py

Changes:
- Ollama Model Class
- Ollama Cookbook
- Small improvements to Claude
Notes:
- Ollama Class has been developed to work best with llama models. (llama 3.2, llama 3.1) using tool call support of [Ollama](https://ollama.com/blog/tool-support)

ollama-models-phi-1215

---

phi/llm/openai/chat.py

Fixing https://github.com/phidatahq/phidata/issues/988 for OpenAiChat.

Replace if temperatures with if temperature is not None

---

cookbook/examples/research/app.py
cookbook/examples/research/assistants.py

Improve error handling for issue #1054 (1) and improve UI feedback on research assistant (2)
1. error handling for issue #1054:
https://github.com/user-attachments/assets/17e62e3b-d6ba-4de5-95ec-7ad1f7c34659
2. Arxiv summaries with authors displayed in table:
https://github.com/user-attachments/assets/3604719c-5344-4413-b8bb-0858e5506fd8
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

improve: research assistant UI & better error handling

---

cookbook/tools/calculator_tools.py
cookbook/tools/composio_tools.py
cookbook/tools/crawl4ai_tools.py
cookbook/tools/csv_tools.py
cookbook/tools/email_tools.py
cookbook/tools/exa_tools.py
cookbook/tools/firecrawl_tools.py
cookbook/tools/github_tools.py
cookbook/tools/googlesearch_tools.py
cookbook/tools/hackernews.py
cookbook/tools/jinareader_tools.py
cookbook/tools/jira_tools.py
cookbook/tools/newspaper4k_tools.py
cookbook/tools/newspaper_tools.py
cookbook/tools/postgres_tools.py
cookbook/tools/pubmed.py
cookbook/tools/python_tools.py
cookbook/tools/resend_tools.py
cookbook/tools/serpapi_tools.py
cookbook/tools/spider_tools.py
cookbook/tools/sql_tools.py
cookbook/tools/yfinance_tools.py
cookbook/tools/youtube_tools.py
cookbook/tools/zendesk_tools.py
phi/tools/github.py
phi/tools/jira_tools.py
phi/tools/postgres.py

Changes:
- Tool cookbook update
- Github Tools update
- Jira Tools update

tools-cookbook-update-phi-1566

---

cookbook/knowledge/README.md
cookbook/knowledge/arxiv_kb.py
cookbook/knowledge/custom_references.py
cookbook/knowledge/json_kb.py
cookbook/knowledge/langchain.py
cookbook/knowledge/llamaindex.py
cookbook/knowledge/pdf.py
cookbook/knowledge/pdf_url.py
cookbook/knowledge/text.py
cookbook/knowledge/website_kb.py
cookbook/knowledge/website_pinecone_kb.py
cookbook/knowledge/wikipedia_kb.py

Changes:
- Agent knowledge base cookbooks

kb-cookbooks-phi-1641

---

cookbook/tools/twitter_tools.py
phi/tools/twitter.py

- Can create a tweet
- Reply to a tweet
- Get information about you
- Get information about any user
- Send DM (paid api keys)
- Get Timeline (paid api key)

Created a Twitter tool

---

cookbook/async/basic.py
cookbook/async/basic_stream_off.py
cookbook/async/data_analyst.py
cookbook/async/duck_db_agent.py
cookbook/async/finance_agent.py
cookbook/async/hackernews.py
cookbook/async/movie_agent.py
cookbook/async/structured_output.py
cookbook/async/web_search.py

Changes:
- Agent Async Cookbook

agent-async-cookbook-phi-1644

---

README.md

Added Badges in Readme to show more information. Also added the star history graph.

chore: added Badges and Star history graph 

---

cookbook/examples/dynamodb_as_storage/agent.py
cookbook/storage/dynamodb_storage.py
cookbook/storage/postgres_storage.py
cookbook/storage/singlestore_storage.py
cookbook/storage/sqlite_storage.py
cookbook/tools/github_tools.py
cookbook/tools/twitter_tools.py
phi/storage/agent/dynamodb.py
phi/tools/twitter.py

Changes:
- Storage cookbooks
- Formatting updates to Twitter Tools and DynadoDb

storage-cookbooks-phi-1703

---

phi/tools/googlesearch.py

Fix issue with googlesearch

---

cookbook/tools/aws_lambda_tool.py
phi/tools/aws_lambda.py
phi/tools/slack.py

This tool allows you to list all the lambda functions and also invoke lambda functions in your AWS account

Feat: AWS Lambda tool

---

cookbook/playground/azure_openai_agents.py
phi/model/azure/openai_chat.py

Enable `AzureOpenAIChat` usage in Playground, similar to `OpenAIChat`
https://github.com/phidatahq/phidata/issues/1382
Run `cookbook/playground/azure_openai_agents.py`
This issue might be resolved by injecting `async_client` externally without making changes

Enable AzureOpenAIChat usage in Playground

---

cookbook/embedder/Qdrant_fastembed.py
phi/embedder/fastembed.py
pyproject.toml

**Overview**
Qdrant FastEmbed is a lightweight, efficient embedding library optimized for fast inference and limited dependencies. Some if its advantages include:
1. High-Speed Embedding Generation: (50% faster) than traditional PyTorch-based transformers, making it ideal for real-time applications.
2. Resource Efficiency: With model quantization and ONNX Runtime integration, FastEmbed minimizes memory and CPU use.
3. Enhanced Retrieval with Prefix-Based Embeddings: FastEmbed supports specialized input prefixes like "query" and "Passage" which allows model to generate differentiated embeddings for queries and documents, optimizing retrieval accuracy and semantic search.
Included FastEmbed example for demonstration of embedding a simple recipe document with FastEmbedEmbedder class.

Integrated Qdrant FastEmbed to Phidata embedder options with Examples

---

cookbook/providers/huggingface/agent_stream.py
cookbook/providers/huggingface/basic_llama_inference.py
phi/model/huggingface/__init__.py
phi/model/huggingface/hf.py

```py
from phi.agent import Agent
from phi.model.huggingface import HuggingFaceChat
import os
from getpass import getpass
os.environ['HF_TOKEN'] = getpass("Enter your HuggingFace Access token")
agent = Agent(
model = HuggingFaceChat(
id="mistralai/Mistral-7B-Instruct-v0.2",
max_tokens=4096,
temperature=0
),
description="What is meaning of life",
)
agent.print_response("What is meaning of life and then recommend 5 best books for the same",stream=True)
```

[feat_add: New LLM] HuggingFace Model Support

---

cookbook/providers/xai/README.md
cookbook/providers/xai/agent.py
cookbook/providers/xai/agent_stream.py
cookbook/providers/xai/basic.py
cookbook/providers/xai/basic_stream.py

Changes:
- xAI cookbook update

models-test-update-xai-phi-1781

---

cookbook/providers/nvidia/basic.py
cookbook/providers/nvidia/basic_stream.py
phi/model/nvidia/nvidia.py

models-test-update-nvidia-phi-1775

---

cookbook/providers/sambanova/basic.py
cookbook/providers/sambanova/basic_stream.py
phi/model/sambanova/sambanova.py

Changes:
- Formatting updates to `Sambanova`

models-test-update-sambanova-phi-1779

---

cookbook/tools/models_lab_tool.py

Add models labs cookbook phi 1871

---

cookbook/embedders/gemini_embedder.py
cookbook/embedders/qdrant_fastembed.py

Add gemini embedder cookbook and fix the name of qdrant fast embed cookbook file

Add gemini embedder cookbook

---

cookbook/tools/sleep_tool.py
phi/tools/sleep.py

This PR fixes the sleep tool and also adds a cookbook to showcase the use of it

Fix sleep tool and add cookbook

---

cookbook/tools/dalle_tools.py

We have a dalle tool but no cookbook for it. This PR adds a cookbook to showcase the use of Dalle

Add Dalle tool cookbook

---

cookbook/providers/google_openai/README.md
cookbook/providers/google_openai/basic.py
cookbook/providers/google_openai/basic_stream.py
phi/model/google/__init__.py
phi/model/google/gemini_openai.py

Changes:
- Added support for Gemini OpenAILike
Notes:
Function calling and Structured output is not fully supported as Gemini OpenAI compatibility is still in beta. Read more here: https://ai.google.dev/gemini-api/docs/openai

gemini-openai-like-phi-1943

---

cookbook/providers/google/README.md
cookbook/providers/google/data_analyst.py
phi/tools/duckdb.py

Changes:
- Updates to `duckdb-tool` for compatibility with Gemini

duckdb-tool-for-gemini-not-working-phi-1734

---

cookbook/providers/deepseek/README.md
cookbook/providers/deepseek/agent.py
cookbook/providers/deepseek/agent_stream.py
cookbook/providers/deepseek/basic.py
cookbook/providers/deepseek/basic_stream.py
cookbook/providers/deepseek/data_analyst.py
cookbook/providers/deepseek/finance_agent.py
cookbook/providers/deepseek/structured_output.py
cookbook/providers/deepseek/web_search.py
phi/model/deepseek/deepseek.py

Changes:
- Formatting updates to Deepseek

models-test-update-deepseek-phi-1770

---

cookbook/providers/hermes/README.md
cookbook/providers/hermes/agent.py
cookbook/providers/hermes/agent_stream.py
cookbook/providers/hermes/basic.py
cookbook/providers/hermes/basic_stream.py
cookbook/providers/hermes/data_analyst.py
cookbook/providers/hermes/finance_agent.py
cookbook/providers/hermes/structured_output.py
cookbook/providers/hermes/web_search.py
phi/model/ollama/__init__.py
phi/model/ollama/chat.py
phi/model/ollama/hermes.py

Changes:
- Custom Hermes Ollama Class to support tool call streaming with `hermes3` models

hermes-ollama-class-phi-1944

---

cookbook/tools/zoom_tools.py
phi/tools/zoom.py

made zoom tools cookbook
- added delete meetings functionality
- added get meetings details functionality
- added get all meetings functionality
- added get meeting recordings functionality
[https://developers.zoom.us/docs/api/meetings/#tag/meetings/POST/meetings/{meetingId}/registrants](https://developers.zoom.us/docs/api/meetings/#tag/meetings/POST/meetings/%7BmeetingId%7D/registrants)
https://developers.zoom.us/docs/internal-apps/s2s-oauth/

Add zoom cookbook phi 1874

---

cookbook/tools/phi_tool.py
phi/tools/phi.py

Fix the phi tool to incorporate the new templates and add a cookbook to showcase its use

Fix phi tool and add a cookbook

---

cookbook/tools/twilio_tools.py
phi/tools/twilio.py

Implements https://github.com/phidatahq/phidata/issues/1334
PTAL @manthanguptaa @ysolanky

Added Twilio as a tool

---

phi/model/google/gemini.py

Changes:
- Fixed the bug causing Gemini runs to not log
- Made tool call streaming more robust

fix-logging-for-gemini-phi-1989

---

pyproject.toml

Validation fix

---

cookbook/integrations/qdrant/README.md

The Qdrant integration readme was incorrect and mentioned pinecone instead of qdrant

Fix Qdrant integration readme

---

cookbook/providers/ollama_tools/README.md
cookbook/providers/ollama_tools/agent.py
cookbook/providers/ollama_tools/agent_stream.py
cookbook/providers/ollama_tools/agent_team.py
cookbook/providers/ollama_tools/basic.py
cookbook/providers/ollama_tools/basic_stream.py
cookbook/providers/ollama_tools/data_analyst.py
cookbook/providers/ollama_tools/finance_agent.py
cookbook/providers/ollama_tools/knowledge.py
cookbook/providers/ollama_tools/storage.py
cookbook/providers/ollama_tools/structured_output.py
cookbook/providers/ollama_tools/web_search.py
phi/model/ollama/__init__.py
phi/model/ollama/tools.py

Changes:
- New OllamaTools Class that uses XML tags in the system prompt to declare Tools
- OllamaTools Cookbook

ollamatools-phi-1991

---

cookbook/providers/openai/o1/basic.py
cookbook/providers/openai/o1/basic_stream.py

Changes:
- `OpenAIChat` o1 model cookbook

o1-cookbook-init-phi-2005

---

phi/model/InternLM/internlm.py
phi/model/xai/xai.py

Changes:
- `InternLM` model class
Notes:
- `InternLM` uses OpenAI spec but this class has not been tested as obtaining an API key requires a Chinese mobile number

feature-request-internlm25-phi-1828

---

cookbook/knowledge/s3_pdf.py
cookbook/knowledge/s3_text.py

Changes:
- S3 knowledge cookbooks

s3-knowledge-cookbooks-phi-2020

---

cookbook/embedders/azure_embedder.py
cookbook/embedders/fireworks_embedder.py
cookbook/embedders/gemini_embedder.py
cookbook/embedders/huggingface_embedder.py
cookbook/embedders/mistral_embedder.py
cookbook/embedders/ollama_embedder.py
cookbook/embedders/openai_embedder.py
cookbook/embedders/qdrant_fastembed.py
cookbook/embedders/sentence_transformer_embedder.py
cookbook/embedders/together_embedder.py
phi/embedder/huggingface.py

Changes:
- Updates to embedder cookbooks

add-azureembedder-cookbook-example-phi-1918

---

cookbook/providers/openai/storage.py
phi/agent/agent.py

Changes:
- Sync the monitoring of Reasoning Agent with Main Agent

reasoning-agent-monitoring-update-phi-2087

---

cookbook/tools/discord_tools.py
phi/tools/discord_tools.py
pyproject.toml

Add Discord bot functionality to phi tools with async support. Includes basic channel and message management capabilities.
- Send/delete messages
- Get channel history
- List channels and info
- Example usage in cookbook
this fixes #1330

feat: add Discord integration tool

---

cookbook/tools/baidusearch_tools.py
phi/tools/baidusearch.py

**Pull Request Description**:  
This PR introduces the `BaiduSearch` toolkit and an example of its usage in a Phidata `Agent`. The code has passed all formatting and validation checks, ensuring readiness for integration.
1. **Implemented `BaiduSearch` Toolkit**:
- Located in `phi/tools/baidusearch.py`.
- Enables Baidu search functionality with options for:
- Maximum results.
- Language settings (with auto-conversion using `pycountry`).
- Custom headers, proxy, and timeout.
- Handles missing dependencies (`baidusearch`, `pycountry`) with clear error messages and installation guidance.
- Outputs search results in JSON format, including title, URL, abstract, and ranking.
2. **Added Example in `cookbook/tools/baidusearch_tools.py`**:
- Demonstrates integration of the `BaiduSearch` tool in a …

Add Baidu Search Tool for Phidata

---

cookbook/providers/ollama_tools/knowledge.py

Added `"psycopg[binary]"` in Install Command.

Update knowledge.py: Added 'psycopg[binary]' in install command.

---

cookbook/providers/vertexai/README.md
cookbook/providers/vertexai/agent.py
cookbook/providers/vertexai/agent_stream.py
cookbook/providers/vertexai/basic.py
cookbook/providers/vertexai/basic_stream.py
cookbook/providers/vertexai/data_analyst.py
cookbook/providers/vertexai/finance_agent.py
cookbook/providers/vertexai/knowledge.py
cookbook/providers/vertexai/storage.py
cookbook/providers/vertexai/structured_output.py
cookbook/providers/vertexai/web_search.py
phi/model/google/gemini.py
phi/model/vertexai/__init__.py
phi/model/vertexai/gemini.py

Changes:
- Vertex AI Gemini Model Class
- Vertex AI Gemini Cookbook

google-model-vertex-ai-phi-1412

---

phi/workflow/workflow.py

Changes:
- Sync session_id of Agents in a Workflow to the Workflow session_id

Workflow sessions

---

cookbook/vectordb/lance_db.py
phi/model/google/gemini.py
phi/model/vertexai/gemini.py

Changes:
- Logging updates to Gemini

models-test-update-google-phi-1772

---

phi/llm/ollama/chat.py

Solves #1203 and potentially #1178 
Also, seems to be what https://github.com/phidatahq/phidata/pull/1095 was trying to do. I think my solution is in line with what @CorrM suggested there.

fix #1203 ollama tools usage always returns empty responses

---

cookbook/agents/43_generate_replicate_video.py
cookbook/agents/44_generate_replicate_image.py
cookbook/assistants/llms/vertexai/samples/multimodal.py
cookbook/assistants/llms/vertexai/samples/text_stream.py
phi/agent/agent.py
phi/llm/google/gemini.py
phi/llm/vertexai/gemini.py
phi/model/content.py
phi/model/google/gemini.py
phi/model/vertexai/gemini.py
phi/run/response.py
phi/tools/dalle.py
phi/tools/models_labs.py
phi/tools/replicate.py
pyproject.toml

- This adds the replicate toolkit for generating videos and images

[PHI-2155] Add replicate toolkit

---

cookbook/providers/google/agent.py
cookbook/providers/google/agent_stream.py
phi/model/google/gemini.py

Changes:
- Update to the Gemini Class to support Gemini2

gemini-2-flash-phi-2171

---

cookbook/examples/agents/02_movie_recommedation.py

Movie Recommendation Agent

---

cookbook/vectordb/qdrant_db.py

Add a qdrant example with an Agentic rag using SqlAgentStorage for memory and WebsiteKnowledgeBase

cookbook vectordb: Qdrant

---

cookbook/providers/vertexai/agent.py
cookbook/providers/vertexai/agent_stream.py
cookbook/providers/vertexai/basic.py
cookbook/providers/vertexai/basic_stream.py
cookbook/providers/vertexai/data_analyst.py
cookbook/providers/vertexai/finance_agent.py
cookbook/providers/vertexai/knowledge.py
cookbook/providers/vertexai/storage.py
cookbook/providers/vertexai/structured_output.py
cookbook/providers/vertexai/web_search.py
phi/model/vertexai/gemini.py

Changes:
- Gemini 2 support added for Vertex AI

vertex-ai-gemini-2-update-phi-2172

---

phi/model/ollama/chat.py

Changes:
- Ollama structured output fix

ollama-structured-output-fix-phi-2164

---

cookbook/providers/google/audio_agent.py
cookbook/providers/google/audio_agent_file_upload.py
phi/model/google/gemini.py
phi/model/message.py

Changes:
- Gemini Audio input fix

Gemini audio fix phi 2202

---

cookbook/vectordb/chroma_db.py

Adds missing chroma vector db cookbook

Add chromadb vectordb cookbook

---

phi/tools/crawl4ai_tools.py

Fixes #1556 
Crawl4ai has deprecated their synchronous webcrawler.  This switches to using the AsyncWebCrawler.
In future when we support async tool calling, we can use it more directly.
** This works best with crawl4ai>=0.4.1 **

Switch to crawl4ai async to fix issues with webcrawler

---

phi/tools/youtube_tools.py

Changes:
- Proxy param added to youtube tools
Addresses: https://github.com/phidatahq/phidata/issues/1567

Youtubetools proxy param phi 2208

---

phi/model/openai/chat.py

The `audio` property on `ChatCompletionMessage` was only added with openai release 1.52.0. This checks and warns the user that some of our functionality won't work if they don't upgrade.

Add version checker for openai

---

cookbook/storage/json_storage.py
cookbook/storage/yaml_storage.py
phi/storage/agent/json.py
phi/storage/agent/yaml.py

Change the `path` param to `dir_path`

Fix: path param to dir_path

---

cookbook/tools/confluence_tools.py
phi/tools/confluence.py
phi/tools/eleven_labs_tools.py
pyproject.toml

Makes some clarifications on the confluence cookbook to make it more reliable

Make confluence cookbook more clear

---

phi/workflow/workflow.py

Worfklow and Worflow being fixed to workflow
- **Summary of changes**: Fixing two trivial typos
- **Related issues**: No related issues
- **Motivation and context**: Fixing my OCD
- **Environment or dependencies**: None
- **Impact on AI/ML components**: (If applicable) None
Sorry if this is silly

Fix typos in debug output

---

cookbook/integrations/clickhouse/README.md
cookbook/integrations/clickhouse/agent.py
cookbook/integrations/clickhouse/agentic_rag_agent_ui.py
cookbook/run_clickhouse.sh
phi/vectordb/clickhouse/__init__.py
phi/vectordb/clickhouse/clickhousedb.py
phi/vectordb/clickhouse/index.py
pyproject.toml
scripts/install.sh

#1326: Add clickhouse as a VectorDb.

---

cookbook/assistants/examples/worldbuilding/assistant.py

chore: update assistant.py

---

cookbook/examples/agents/08_legal_agent.py

Added a Legal Advisor Agent

---

cookbook/workflows/self_evaluation_workflow.py

This PR shows a self evaluation loop example of how the agent can improve the content from feedback by another agent

Self evaluation workflow example

---

phi/vectordb/lancedb/lance_db.py

Adds custom `deepcopy` function for LanceDb 

lance-db-deepcopy-phi-2239

---

phi/embedder/google.py

The latest pydantic v2.10.x rejects functions as types and the previous type wasn't correct regardless as we were assigning a module.
Fixes #1672 

Fix gemini client type 

---

phi/embedder/huggingface.py

Implements Huggingface embedder's `get_embedding_and_usage` method.
Fixes #1654 

fixed HuggingFace Embedder #1654

---

phi/embedder/ollama.py

Removed redundancy in **Ollama embedder** (`OllamaEmbedder`) class.

Refactor ollama get_embedding_and_usage to use get_embedding method

---

phi/vectordb/lancedb/lance_db.py

Adds support for accessing an existing database table in LanceDb 
Fixes https://github.com/phidatahq/phidata/issues/1435

lancedb-fix-phi-2240

---

cookbook/storage/mongodb_storage.py
phi/knowledge/base.py

fix knowledge

---

libs/agno/agno/document/reader/s3/pdf.py
libs/agno/agno/document/reader/s3/text.py
libs/agno/agno/embedder/mistral.py
libs/agno/agno/knowledge/s3/base.py
libs/agno/agno/models/aws/bedrock.py
libs/agno/agno/models/cohere/chat.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/models/mistral/mistral.py
libs/agno/agno/models/ollama/chat.py
libs/agno/agno/models/vertexai/gemini.py
libs/agno/agno/playground/operator.py
libs/agno/agno/playground/router.py
libs/agno/agno/tools/calcom.py
libs/agno/agno/tools/zoom.py

validation-fix

---

pyproject.toml

- **Image-to-Image Generation Support:** Extended FalTools to support image-to-image generation.
- **MongoDB Integrations:** Added MongoDB support across agent storage, agent knowledgebase, agent memory, and workflow storage.
- **Download Image Utility:** Introduced a utility to download agent-generated images directly for enhanced workflows.
Improvements:
- **Audio Transcript Handling:** Refined the handling of audio transcripts to ensure accurate message output when processing audio files
- **Optimized Chunking**: Enhanced fixed and recursive chunking methods to improve document processing performance.
- **HuggingFace Embedder**: Resolved compatibility issues with HuggingFace embedder for better reliability.
- **Ollama Embedder**: Upgraded the Ollama embedder for more robust and …

Release 2.7.7

---

phi/agent/agent.py

This warning confuses users whereas it is really just internal since we resolve it.
x

Remove unnecessary warning that confuses users

---

pyproject.toml

Our Pypi releases did not include our license. This includes it.

Make sure license is added to pypi release

---

cookbook/workflows/personalized_marketing.py
pyproject.toml

Uses an HTML template to better format the email
Personalized marketing workflow cookbook

marketing workflow

---

cookbook/providers/deepseek/web_search.py
cookbook/providers/fireworks/agent.py
cookbook/providers/fireworks/agent_stream.py
cookbook/providers/fireworks/basic.py
cookbook/providers/fireworks/basic_stream.py
cookbook/providers/fireworks/data_analyst.py
cookbook/providers/fireworks/finance_agent.py
cookbook/providers/fireworks/structured_output.py
cookbook/providers/fireworks/web_search.py
cookbook/providers/nvidia/basic.py
cookbook/providers/nvidia/basic_stream.py
phi/model/fireworks/fireworks.py
phi/model/nvidia/nvidia.py
phi/model/openai/chat.py
phi/model/openai/like.py

The OpenAI implementation to cast system roles to "developer" broke some implementations of OpenAILike. This addresses those.
Fixes #1747 #1757 #1770 

Fix OpenAILike roles

---

cookbook/playground/test.py
phi/playground/router.py
requirements.txt

Fix imports of docx being required for the playground.
Fixes #1738

Fix 1738/docx import

---

libs/agno/agno/models/google/__init__.py
libs/agno/agno/workflow/workflow.py

Changes:
- Move `update_run_method` fn to init

fix-workflows

---

cookbook/providers/openai/o1/o1.py
cookbook/providers/openai/o1/o1_stream.py

This adds some basic cookbooks to show o1 working.

Add basic cookbooks for o1

---

libs/agno/agno/reasoning/step.py
libs/agno/agno/run/response.py

Fix json validation error

---

cookbook/playground/demo.py
cookbook/playground/multimodal_agents.py

- Fix image send in markdown
- Improve structure.

Fix image in markdown

---

cookbook/embedders/openai_embedder.py
cookbook/providers/azure_openai/knowledge.py
phi/embedder/azure_openai.py
phi/embedder/openai.py
phi/model/azure/openai_chat.py

Address inefficiencies in the AzureOpenAIEmbedder
Updated the default model for both Azure and OpenAI embedders to `text-embedding-3-small` as it is cheaper than
`ada-002`

Fix AzureOpenAIEmbedder to work with AzureOpenAIChat

---

cookbook/agent_concepts/knowledge/embedders/openai_embedder.py
cookbook/agent_concepts/tools/reddit_tools.py
cookbook/models/anthropic/knowledge.py
libs/agno/agno/agent/agent.py
libs/agno/agno/embedder/azure_openai.py
libs/agno/agno/memory/agent.py
libs/agno/agno/memory/manager.py
libs/agno/agno/memory/memory.py
libs/agno/agno/memory/summary.py
libs/agno/agno/models/base.py
libs/agno/agno/models/openai/chat.py
libs/agno/agno/models/openai/like.py
libs/agno/agno/tools/reddit.py
libs/agno/agno/utils/safe_formatter.py

- There was a bug introduced by changing the system_role to developer for openai models
- We add a `override_system_role` param in the Model class that helps the agent change the role, instead of the model format message step

Fix a bug introduced by changing the system role to "developer"

---

libs/agno/agno/memory/agent.py
libs/agno/agno/memory/manager.py
libs/agno/agno/memory/memory.py
libs/agno/agno/memory/summary.py

Revert some changes from https://github.com/phidatahq/phidata/pull/1825

---

cookbook/providers/azure_openai/knowledge.py
cookbook/providers/claude/storage.py
cookbook/tools/reddit_tools.py
cookbook/tools/trello_tools.py
phi/model/anthropic/claude.py
phi/playground/router.py
phi/tools/slack.py

We stored the Claude TextBlock in memory to make it easier for history, but this meant our memory wasn't nice and clean for users to interact with. 
This fixes that by making sure we translate correctly back and forth.

Fix claude text block in memory

---

cookbook/tools/telegram_tools.py
phi/tools/telegram.py

This adds the TelegramTools and examples of how to send message to telegram chat.

Add telegram tool

---

cookbook/playground/multimodal_agents.py

Remove hindi audio agent as its unreliable 

fix: remove

---

cookbook/README.md
cookbook/scripts/README.md
libs/agno/agno/models/base.py
libs/infra/agno_docker/agno/docker/app/celery/__init__.py
libs/infra/agno_docker/agno/docker/app/celery/worker.py

Fixes an error where we were not showing tool calls, introduced [here](https://github.com/phidatahq/phidata/pull/1823/files#r1922916825)

Fix show tool calls error

---

CODEOWNERS

add-codeowners-phi-2438

---

cookbook/examples/streamlit/paperpal/app.py
cookbook/examples/streamlit/paperpal/technical_writer.py

Fix streamlit paperpal cookbook

---

phi/tools/function.py
phi/tools/slack.py
phi/utils/json_schema.py

A change in 2.7.7 broke function parsing for custom functions.
Fixes #1836 

Fix function parsing for custom functions

---

cookbook/agent_concepts/async/data_analyst.py
cookbook/agent_concepts/tools/csv_tools.py
cookbook/agent_concepts/tools/duckdb.py

PHI-2422 Update S3 buckets

---

cookbook/examples/streamlit/llm_os/app.py

fix llmos streaming ,duplicate, ordering

---

cookbook/agent_concepts/README.md
cookbook/examples/README.md

Update Agent concepts readme

---

cookbook/playground/demo.py

Change table name of simple agent

fix: table name

---

cookbook/agent_concepts/teams/hackernews_team.py
cookbook/agent_concepts/teams/news_agency_team.py
cookbook/agent_concepts/teams/respond_directly.py
cookbook/examples/streamlit/medical_imaging/medical_agent.py
libs/agno/agno/models/ollama/chat.py

Changes:
- Ollama streaming fix

ollama-streaming-fix-phi-2510

---

cookbook/playground/groq_agents.py

`llama3-groq-70b-8192-tool-use-preview` is deprecated and replaced it with llama-3.3-70b-versatile

fix: change model from deprecated model

---

cookbook/use_cases/apps/game_generator/README.md
cookbook/use_cases/apps/llm_os/Readme.md
cookbook/use_cases/apps/medical_imaging/README.md
cookbook/use_cases/apps/paperpal/README.md

fixes readme of streamlit apps

fix streamlit app readme

---

cookbook/examples/streamlit/geobuddy/app.py
cookbook/examples/streamlit/geobuddy/geography_buddy.py
cookbook/examples/streamlit/geobuddy/readme.md
cookbook/examples/streamlit/geobuddy/requirements.txt
pyproject.toml

GeoBuddy is an AI-powered geography agent that analyzes images to predict locations based on visible cues like landmarks, architecture, and cultural symbols.
- Location Identification: Predicts location details from uploaded images.
- Detailed Reasoning: Explains predictions based on visual cues.
- User-Friendly UI: Built with Streamlit for an intuitive experience.
- [ X ] My code follows Phidata's style guidelines and best practices
- [ X ] I have performed a self-review of my code
- [ X ] I have added docstrings and comments for complex logic
- [ X ] My changes generate no new warnings or errors
- [ X ] I have updated requirements.txt/pyproject.toml (if needed)
- [ X ] I have verified my changes in a clean environment

Geobuddy Agent

---

cookbook/examples/streamlit/llm_os/app.py
pyproject.toml

- **ClickUp Tool**: Added support for managing tasks on ClickUp.
- **Postgres custom table schema:** Add custom table schema parameter for Postgres tools
- **LLM-OS v1:** Add a streamlit application example for LLM-OS. A application that uses an LLM with advanced operating-system level capabilities.
- **GeoBuddy:**  An AI-powered geography agent that analyzes images to predict locations based on visible cues like landmarks, architecture, and cultural symbols.
- **Text Search Compatibility:** Resolved an issue where Text Search was not forward-compatible with recent versions.
- **Custom Function Parsing:** Fixed an issue where function parsing for custom functions did not pass all parameters to the AI.
- **Claude Memory Handling:** Addressed an issue in Claude where memory was not …

Release 2.7.10

---

CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md
cookbook/agent_concepts/knowledge/readers/firecrawl_reader.py
cookbook/agent_concepts/knowledge/youtube_kb.py
cookbook/examples/apps/game_generator/app.py
cookbook/examples/apps/geobuddy/app.py
cookbook/examples/apps/llm_os/Readme.md
cookbook/examples/apps/llm_os/app.py
cookbook/examples/apps/llm_os/os_agent.py
cookbook/examples/apps/medical_imaging/app.py
cookbook/examples/apps/paperpal/app.py
cookbook/examples/tbd/content_creator/readme.md
cookbook/examples/tbd/readme_generator.py
cookbook/models/deepseek/tool_use.py
cookbook/models/google/gemini/storage_and_memory.py
cookbook/tools/composio_tools.py
cookbook/tools/crawl4ai_tools.py
cookbook/tools/github_tools.py
cookbook/tools/jinareader_tools.py
cookbook/tools/twitter_tools.py
libs/agno/agno/workspace/operator.py
tests/unit/utils/test_string.py

Update more instances where phidata is used instead of agno

update phidata to agno

---

cookbook/playground/azure_openai_agents.py

Update instructions not to send image in response body

fix: update instructions not to send image in response body

---

libs/agno/agno/tools/eleven_labs.py

Remove voice id arg from eleven labs tts function

fix: remove voice id

---

cookbook/workflows/blog_post_generator.py
cookbook/workflows/investment_report_generator.py
libs/agno/agno/workflow/workflow.py

Changes:
- Use class attribute for description

workflow-description-update-ag-2541

---

cookbook/playground/demo.py
libs/agno/agno/agent/agent.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/workflow/workflow.py

Fix rename and delete regressions

---

cookbook/examples/apps/game_generator/README.md
cookbook/examples/apps/geobuddy/readme.md
cookbook/examples/apps/medical_imaging/README.md

fix examples apps readme 

---

libs/agno/pyproject.toml

This is a major refactor to be coupled with the launch of Agno AI.
- `phi.model.x` → `agno.models.x`
- `phi.knowledge_base.x` → `agno.knowledge.x` (applies to all knowledge bases)
- `phi.document.reader.xxx` → `agno.document.reader.xxx_reader` (applies to all document readers)
- All Agno toolkits are now suffixed with `Tools`. E.g. `DuckDuckGo` → `DuckDuckGoTools`
- Multi-modal interface updates:
- `agent.run(images=[])` and `agent.print_response(images=[])` is now of type `Image`
```python
class Image(BaseModel):
url: Optional[str] = None  # Remote location for image
filepath: Optional[Union[Path, str]] = None  # Absolute local location for image
content: Optional[Any] = None  # Actual image bytes content
detail: Optional[str] = None # low, medium, high or auto (per OpenAI spec …
```

Release 1.0.0 (Agno)

---

CODEOWNERS
CONTRIBUTING.md
README.md
cookbook/agent_concepts/knowledge/readers/firecrawl_reader.py
cookbook/examples/agents/readme_generator.py
cookbook/examples/apps/game_generator/app.py
cookbook/examples/apps/geobuddy/app.py
cookbook/examples/apps/llm_os/Readme.md
cookbook/examples/apps/llm_os/app.py
cookbook/examples/apps/medical_imaging/app.py
cookbook/examples/apps/paperpal/app.py
cookbook/tools/composio_tools.py
cookbook/tools/crawl4ai_tools.py
cookbook/tools/github_tools.py
cookbook/tools/jinareader_tools.py
cookbook/workflows/content_creator/readme.md
libs/agno/agno/workspace/operator.py

- Replace `agno-agi` links with `AgnoAgi`

Replace `agno-agi` links with `AgnoAgi`

---

cookbook/models/mistral/mistral_small.py
libs/agno/agno/models/mistral/mistral.py
libs/agno/agno/playground/settings.py

- Cache mistral models
---
---
- [xk] Formatting and validation: You have run `./scripts/format.sh` and `./scripts/validate.sh` to ensure code is formatted and linted.
---

Cache mistral models

---

cookbook/examples/apps/chess_team/main.py
cookbook/examples/apps/chess_team/requirements.txt

Change the model to o3-mini in chess team agent for better game and less illegal moves
---
---

fix: change model to o3-mini

---

libs/agno/pyproject.toml

- Aws and docker extras added to the project
---
---
---

Infra dependencies ag 2568

---

cookbook/models/openai/reasoning/reasoning_effort.py

- added reasoning effort example
---
---

o3-mini reasoning effort example

---

libs/agno/agno/models/openai/chat.py
libs/agno/pyproject.toml

- **Gmail Tools →** Add tools for Gmail, including mail search, sending mails, etc.
- **Exa Toolkit Upgrade →** Added `find_similar` to `ExaTools`
- **Claude Async** → Claude models can now be used with `await agent.aprint_response()` and `await agent.arun()`.
- **Mistral Vision** → Mistral vision models are now supported. Various examples were added to illustrate.

Release 1.0.5

---

cookbook/tools/github_tools.py
libs/agno/agno/tools/github.py
libs/agno/tests/unit/tools/test_github.py
libs/agno/tests/unit/tools/test_zoom_tools.py

Pagination wasn't done correctly for github tools. This fixes that and adds tests.
Fixes #1993 
---
---
---

Fix pagination in github tools and add tests

---

evals/performance/other/crewai_instantiation.py
evals/performance/other/pydantic_ai_instantiation.py
evals/performance/other/smolagents_instantiation.py

This updates the evaluation scripts for Smolagents, CrewAI and Pydantic AI

Update performance evals for other frameworks

---

cookbook/agent_concepts/knowledge/readers/url_reader.py
cookbook/examples/agents/deep_knowledge.py
libs/agno/agno/document/reader/url_reader.py
libs/agno/agno/knowledge/url.py
libs/agno/pyproject.toml

Deep knowledge

---

cookbook/models/cohere/async/basic.py
cookbook/models/cohere/async/basic_stream.py
cookbook/models/cohere/async/structured_output.py
cookbook/models/cohere/async/tool_use.py
libs/agno/agno/models/cohere/chat.py
libs/agno/tests/unit/tools/test_zoom_tools.py

This adds async capabilities to cohere model
---
---
---

Async Cohere

---

cookbook/agent_concepts/knowledge/custom/retriever.py
cookbook/agent_concepts/knowledge/vector_dbs/weaviate_db.py
libs/agno/agno/agent/agent.py

- Custom retriever example
- Add search knowledge base tool if retriever is provided

Add custom retriever

---

cookbook/models/perplexity/README.md
cookbook/models/perplexity/basic.py
cookbook/models/perplexity/basic_stream.py
cookbook/models/perplexity/knowledge.py
cookbook/models/perplexity/memory.py
cookbook/models/perplexity/structured_output.py
cookbook/models/perplexity/tool_use.py
libs/agno/agno/models/perplexity/__init__.py
libs/agno/agno/models/perplexity/perplexity.py

AG-2323 Add perplexity model

---

cookbook/models/openai/storage.py
libs/agno/agno/agent/agent.py
libs/agno/agno/memory/agent.py
libs/agno/agno/models/message.py

- Fixes a bug with duplication of `run_messages.messages` for every run in storage 
- To test, run `cookbook/models/openai/storage.py` with agent.cli_app()
---
---
---

fix-memory-ag-2662

---

libs/agno/pyproject.toml

- **Perplexity Model**: We now support [[Perplexity](https://www.perplexity.ai/)](https://www.perplexity.ai/) as a model provider.
- **Todoist Toolkit:** Added a toolkit for managing tasks on Todoist.
- **JSON Reader**: Added a JSON file reader for use in knowledge bases.
- **LanceDb**: Implemented `name_exists` function for LanceDb
- **Storage growth bug:** Fixed a bug with duplication of `run_messages.messages` for every run in storage

Release 1.0.8

---

cookbook/agent_concepts/knowledge/langchain_kb.py
cookbook/agent_concepts/knowledge/llamaindex_kb.py

update langchain modules

---

cookbook/tools/googlesearch_tools.py
cookbook/workflows/startup_idea_validator.py
libs/agno/agno/tools/googlesearch.py

- Update `GoogleSearchTools` to match the naming convention
Fixes #2008 
---
---
---

google-search-tool-update-ag-2659

---

libs/agno/agno/tools/firecrawl.py

- **Summary of changes**: Added functionality of getting api key from env file in firecrawl tools.
---
---
---

Get api key from env file

---

libs/agno/agno/models/message.py
libs/agno/agno/playground/operator.py

With the new model refactor playground session name was breaking. This PR fixes that issue
---
---
---

Fix Playground session name

---

libs/agno/agno/agent/agent.py

If you had a team member with a name like "News Reporter &", it would break.
Fixes #2082 
---
---
---

Fix for teams with weird names

---

libs/agno/pyproject.toml

- **Models Refactor**: A complete overhaul of our models implementation to improve on performance and to have better feature parity across models.
- This improves metrics and visibility on the Agent UI as well.
- All models now support async-await, with the exception of `AwsBedrock`.
- **Azure AI Foundry**: We now support all models on Azure AI Foundry. Learn more [[here](https://learn.microsoft.com/azure/ai-services/models)](https://learn.microsoft.com/azure/ai-services/models).
- **AWS Bedrock Support**: Our redone AWS Bedrock implementation now supports all Bedrock models. It is important to note [[which models support which features](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-supported-models-features.html)](https://docs.aws.amazon.com/bedrock/latest/us …

Release 1.1.0 - Models Refactor and Cloud Support

---

cookbook/tools/elevenlabs_tools.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/base.py
libs/agno/agno/run/response.py
libs/agno/agno/tools/eleven_labs.py

This fixes audio being missing on playground responses.
---
---
---

Fix audio on responses

---

libs/agno/agno/agent/agent.py

Fix reasoning logic
---
---
---

reasoning-fix-ag-2692

---

cookbook/models/google/gemini/structured_output.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/models/groq/groq.py

Adds `supports_structured_outputs: bool = True` to Gemini since they support structured outputs in some cases. 
---
---
---

Make Gemini return structured outputs

---

cookbook/agent_concepts/multimodal/audio_to_text.py

added audio to text example

---

cookbook/agent_concepts/multimodal/audio_sentiment_analysis.py

added audio sentimental analysis example

---

libs/agno/agno/agent/agent.py

fix case where memory is None when you get the system message

---

cookbook/models/ollama_tools/async_tool_use_stream.py
libs/agno/agno/models/google/gemini.py
libs/agno/tests/integration/model/openai/test_sync.py

Fix issue with Gemini and functions with no params

---

cookbook/agent_concepts/async/delay.py
cookbook/hackathon/multimodal_examples/audio_podcast_generator.py

Example on how to use gather with a delay
---
---
---

async_delay

---

libs/agno/agno/document/chunking/agentic.py

Even though someone put another model OpenAI was said to be installed. This PR fixed that issue
Fixes https://community.agno.com/t/agentic-chunking/614/3
---
---
---

Fix Agentic Chunking

---

cookbook/examples/apps/agentic_rag/agentic_rag.py
cookbook/examples/apps/agentic_rag/app.py
cookbook/tools/gmail_tools.py
libs/agno/agno/agent/agent.py
libs/agno/agno/memory/manager.py
libs/agno/agno/memory/summarizer.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/playground/playground.py
libs/agno/agno/tools/gmail.py
libs/agno/agno/vectordb/chroma/chromadb.py
libs/agno/tests/integration/model/google/test_basic.py
libs/agno/tests/integration/model/openai/test_basic.py

This fixes an issue with using Gemini in the memory summarizer. 
Fixes #2164 
---
---
---

Update how memory summarizer works

---

cookbook/models/groq/reasoning/demo_deepseek_qwen.py
cookbook/playground/agno_assist.py

Update agno assist

---

cookbook/models/groq/reasoning/demo_deepseek_qwen.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/ollama/chat.py
libs/agno/agno/models/openai/chat.py
libs/agno/agno/tools/function.py
libs/agno/tests/integration/teams/test_structured_output.py

Fix regression for how Ollama parses tools with optional parameters.
Fixes #2161 
Fixes #2158 
---
---
---

Fix how tools are parsed for Ollama

---

cookbook/models/aws/bedrock/README.md
cookbook/models/aws/claude/README.md
libs/agno/agno/models/aws/bedrock.py
libs/agno/agno/models/aws/claude.py

- **Summary of changes**: Adding support for boto3 session when using an AWS Bedrock or AWS Claude client
- **Related issues**: [Issue 2176](https://github.com/agno-agi/agno/issues/2176)
- **Motivation and context**: In some instances env params are not the way to generate a session with AWS, this allows the user to create the session in any way that is relevant to their infrastructure.
One example is through profile_name.
- **Environment or dependencies**: Added a check that boto3 is installed for the AWS Claude client as well.
- **Impact on metrics**: I don't know.
[Issue 2176](https://github.com/agno-agi/agno/issues/2176)
---
---
---
Include any deployment notes, performance implications, security considerations, or other …

support boto session for AWS

---

libs/agno/agno/agent/agent.py
libs/agno/pyproject.toml
libs/agno/tests/unit/reader/test_text_reader.py

- **Summary of changes**: Include memory in the fields to copy
---
---
---

playground-memory-fix-ag-2740

---

libs/agno/pyproject.toml

- Add support for claude 3.7
- Fix bug with claude tool use + content in same block

Release 1.1.6

---

libs/agno/pyproject.toml

- **Audio File Upload on Playground**: You can now upload audio files and have a model interpret the audio, do sentiment analysis, provide an audio transcription, etc.

Release 1.1.7

---

evals/performance/other/autogen_instantiation.py
scripts/perf_setup.sh

---
---
The performance is superb.
---

add autogen performance test

---

cookbook/models/huggingface/tool_use.py
libs/agno/agno/models/huggingface/huggingface.py
libs/agno/tests/integration/models/huggingface/test_basic.py
libs/agno/tests/integration/models/huggingface/test_tool_use.py

This PR fixes huggingface
---
---
---

Add tests and fix huggingface

---

libs/agno/agno/models/google/gemini.py

- **Summary of changes**: Bug fix in `_format_messages` function
---
---
---

gemini-bug-fix-ag-2777

---

libs/agno/pyproject.toml

- **Video File Upload on Playground**: You can now upload video files and have a model interpret the video. This only works with certain Gemini models that support video.
- **Huggingface**: Fixed multiple bugs with the huggingface model integration. It now supports tool calling for non-streaming cases.
- **Gemini:** Fixed issue with manually setting the assistant role and tool call result metrics.
- **OllamaEmbedder**: Fixed issue where no embeddings were returned.

Release 1.1.8

---

cookbook/models/groq/deep_knowledge.py

- **Summary of changes**: Deep knowledge seach with llama 3.3 70b
---
---
---

deep knowledge search with llama

---

cookbook/examples/apps/chess_team/app.py
libs/agno/agno/vectordb/lancedb/lance_db.py

fix: remove llama

---

libs/agno/pyproject.toml

Release 1.1.9

---

cookbook/playground/basic.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/sync_router.py

- **Summary of changes**: Made `user_id` optional for all Playground routes
---
---
---

playground-update-ag-2797

---

libs/agno/agno/models/base.py
libs/agno/agno/models/deepinfra/deepinfra.py
libs/agno/agno/models/lmstudio/lmstudio.py
libs/agno/agno/models/nvidia/nvidia.py
libs/agno/agno/models/openrouter/openrouter.py
libs/agno/agno/models/perplexity/perplexity.py
libs/agno/agno/models/together/together.py

Fixes issue where debug logs would be showing the "default" model ID instead of the set model ID, which confuses users.
Fixes #2343 
---
---
---

Fix ID incorrect on model logging

---

cookbook/models/openai/responses/async_tool_use.py
cookbook/models/openai/responses/generate_images.py
cookbook/models/openai/responses/image_agent.py
cookbook/models/openai/responses/image_agent_bytes.py
cookbook/models/openai/responses/image_agent_with_memory.py
cookbook/models/openai/responses/knowledge.py
cookbook/models/openai/responses/memory.py
cookbook/models/openai/responses/storage.py
cookbook/models/openai/responses/structured_output.py
cookbook/models/openai/responses/tool_use.py
cookbook/models/openai/responses/tool_use_stream.py

cookbook examples

---

cookbook/playground/demo.py
libs/agno/agno/tools/todoist.py
libs/agno/tests/unit/tools/test_todoist_tools.py

Todoist update function + validation fixes

---

libs/agno/pyproject.toml

- **OpenAI Responses**: Added a new model implementation that supports OpenAI’s Responses API. This includes support for their [“websearch”](https://platform.openai.com/docs/guides/tools-web-search#page-top) built-in tool.
- **Openweather API Tool**: Added tool to get real-time weather information.
- **Storage Refactor:** Merged agent and workflow storage classes to align storage better for agents, teams and workflows. This change is backwards compatible and should not result in any disruptions.

Release 1.1.11

---

cookbook/models/cohere/async_basic.py
cookbook/models/cohere/async_basic_stream.py
cookbook/models/cohere/async_structured_output.py
cookbook/models/cohere/async_tool_use.py
cookbook/models/cohere/basic.py
cookbook/models/cohere/basic_stream.py
cookbook/models/cohere/knowledge.py
cookbook/models/cohere/memory.py
cookbook/models/cohere/storage.py
cookbook/models/cohere/structured_output.py
cookbook/models/cohere/tool_use.py
libs/agno/agno/models/cohere/chat.py

- **Summary of changes**: Cohere Command a update
---
---
---

cohere-command-a-ag-2886

---

libs/agno/pyproject.toml

- **OpenAIResponses File Search**: Added support for the built-in [“File Search”](https://platform.openai.com/docs/guides/tools-file-search) function from OpenAI. This automatically uploads `File` objects attached to the agent prompt.
- **OpenAIReponses web citations**: Added support to extract URL citations after usage of the built-in “Web Search” tool from OpenAI.
- **Anthropic document citations**: Added support to extract document citations from Claude responses when `File` objects are attached to agent prompts.
- **Cohere Command A**: Support and examples added for Coheres new flagship model
- **Ollama tools**: Fixed issues with tools where parameters are not typed.
- **Anthropic Structured Output**: Fixed issue affecting Anthropic and Anthropic via Azure where structured output …

Release 1.1.13

---

scripts/dev_setup.bat

added dev_setup.bat script for windows
---
---
---

Add Windows development setup script

---

libs/agno/agno/memory/summarizer.py

PR https://github.com/agno-agi/agno/pull/2167 fixed the summarizer for models that require at least one user message, but did it only for the sync method. This PR simply applies the same fix to the async method.
Fixes #2440.
---
---

Fix summarizer for async run as well

---

cookbook/tools/mcp/github.py
libs/agno/agno/models/google/gemini.py

Fix for issue where gemini array property doesn't have items.
---
---
---

Fix issue with Gemini array property

---

cookbook/hackathon/README.md

Add Windows setup instructions to hackathon README.md

---

libs/agno/agno/models/aws/__init__.py
libs/agno/agno/models/azure/__init__.py
libs/agno/agno/models/azure/openai_chat.py
libs/agno/agno/models/litellm/chat.py

- **Summary of changes**: Small import fixes 
---
---
---

azure-import-fix-ag-2900

---

cookbook/agent_concepts/other/cache_tool_calls.py
cookbook/examples/apps/llama_tutor/agents.py
cookbook/examples/apps/llama_tutor/app.py
cookbook/examples/apps/vision_ai/app.py
cookbook/examples/apps/vision_ai/utils.py
libs/agno/agno/tools/duckduckgo.py
libs/agno/agno/tools/exa.py
libs/agno/agno/tools/firecrawl.py
libs/agno/agno/tools/googlesearch.py
libs/agno/agno/tools/hackernews.py
libs/agno/agno/tools/newspaper.py
libs/agno/agno/tools/newspaper4k.py
libs/agno/agno/tools/website.py
libs/agno/agno/tools/yfinance.py
libs/agno/agno/utils/functions.py

This should greatly speed up common testing, avoid unnecessary costs, etc. This is only intended for testing.
---
---
---

Add caching for tools

---

cookbook/agent_concepts/reasoning/thinking/finance_agent.py
libs/agno/agno/models/anthropic/claude.py
libs/agno/agno/tools/thinking.py
libs/agno/pyproject.toml

- **Summary of changes**: Adds the **Think** tool following this [guide](https://www.anthropic.com/engineering/claude-think-tool)
---
---
---

Thinking Tools

---

libs/agno/agno/agent/agent.py
libs/agno/agno/api/agent.py
libs/agno/agno/models/base.py
libs/agno/agno/models/message.py
libs/agno/agno/team/team.py

Fix a few qol debug logs
- Remove new lines, especially after system/user/tool call messages which made it look like there was a an extra line in the prompt
- Remove extra spaces " "

Improve Debug Logs

---

libs/agno/agno/models/azure/ai_foundry.py

- **Summary of changes**: This is a tiny fix for Azure AI Foundry, it fixes an incorrect import.
- **Related issues**: #2489 
- **Motivation and context**: This is a tiny bug fixes, it makes sure that Pydantic BaseModel is used instead of Anthropic BaseModel.
- **Environment or dependencies**: N/A
- **Impact on metrics**: N/A
#2489
---
---

Use the right BaseModel for response format

---

libs/agno/agno/team/team.py

Fix issue in teams markdown

---

cookbook/examples/apps/chess_team/app.py
cookbook/examples/apps/llama_tutor/app.py
cookbook/examples/apps/tic_tac_toe/app.py
cookbook/examples/apps/vision_ai/app.py
cookbook/teams/memory/02_persistent_memory.py
cookbook/teams/memory/03_user_memories.py
libs/agno/agno/team/team.py
libs/agno/agno/utils/json_schema.py

- **Summary of changes**: Update team context
---
---
---

context-update-ag-2909

---

cookbook/teams/modes/route.py
libs/agno/agno/run/team.py
libs/agno/agno/team/team.py

This adds tool call panels for team runs.
---
---
---

Show tool calls for Teams

---

cookbook/teams/memory/01_builtin_memory.py
cookbook/teams/memory/04_agentic_context.py
libs/agno/agno/models/openai/chat.py

- **Summary of changes**: Improve OpenAIChat error handling
---
---
---

improve-openaichat-error-handling-ag-2910

---

libs/agno/pyproject.toml
libs/agno/tests/integration/models/aws/bedrock/test_tool_use.py

- **Teams Memory:** Fixed issues related to memory not persisting correctly across multiple sessions.

Release 1.2.2

---

cookbook/examples/teams/route/multi_language_team.py
cookbook/examples/teams/route/simple.py
cookbook/teams/memory/01_builtin_memory.py
cookbook/teams/memory/04_agentic_context.py
cookbook/teams/modes/route.py
libs/agno/agno/team/team.py

Fix: Teams

---

cookbook/playground/teams_demo.py
libs/agno/agno/agent/agent.py
libs/agno/agno/api/playground.py
libs/agno/agno/api/routes.py
libs/agno/agno/api/team.py
libs/agno/agno/memory/team.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/operator.py
libs/agno/agno/playground/playground.py
libs/agno/agno/playground/schemas.py
libs/agno/agno/playground/sync_router.py
libs/agno/agno/storage/base.py
libs/agno/agno/team/team.py

Add teams playground endpoints

---

cookbook/playground/teams_demo.py
libs/agno/agno/agent/agent.py
libs/agno/agno/api/agent.py
libs/agno/agno/api/playground.py
libs/agno/agno/cli/settings.py
libs/agno/agno/memory/team.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/schemas.py
libs/agno/agno/playground/sync_router.py
libs/agno/agno/team/team.py

Teams playground updates

---

cookbook/examples/apps/chess_team/app.py
cookbook/examples/apps/llama_tutor/app.py
cookbook/examples/apps/tic_tac_toe/app.py
cookbook/examples/apps/vision_ai/app.py
cookbook/playground/teams_demo.py
cookbook/teams/memory/02_persistent_memory.py
cookbook/teams/memory/03_user_memories.py
cookbook/teams/memory/04_agentic_context.py
cookbook/teams/memory/05_team_history.py
cookbook/teams/modes/route.py
cookbook/tools/todoist_tools.py
libs/agno/agno/agent/agent.py
libs/agno/agno/api/agent.py
libs/agno/agno/api/playground.py
libs/agno/agno/memory/team.py
libs/agno/agno/models/aws/claude.py
libs/agno/agno/models/azure/ai_foundry.py
libs/agno/agno/models/groq/groq.py
libs/agno/agno/models/openai/responses.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/operator.py
libs/agno/agno/playground/schemas.py
libs/agno/agno/playground/sync_router.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/todoist.py
libs/agno/pyproject.toml

Fixes an issue which makes the Todoist tools unable to be parsed by some model providers like Gemini.
Fixes #2529 
---
---
---

Fix the update_task for todoist

---

libs/agno/pyproject.toml

- **Tool Choice on Teams**: Made `tool_choice` configurable.
- **Sessions not created**: Made issue where sessions would not be created in existing tables without a migration be more visible.
- **Todoist fixes**: Fixed `update_task` on `TodoistTools`.

Release 1.2.4

---

cookbook/models/anthropic/tool_use.py
libs/agno/agno/models/message.py

- **Summary of changes**: Improves formatting for 2 or more tool calls
Before: 
After:
---
---
---

Improve tool call logs ag 2919

---

cookbook/agent_concepts/knowledge/search_type/hybrid_search.py
cookbook/agent_concepts/knowledge/search_type/keyword_search.py
cookbook/agent_concepts/knowledge/search_type/vector_search.py

#2442 Added Cookbooks for PgVector Search Types
Added examples for vector, keyword, and hybrid search types.
---
---
---

feat: add cookbooks for search types

---

cookbook/models/google/gemini/tool_use_stream.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/models/message.py

**Summary of changes**: 
- Updates tool call result role to "tool" as per Gemini spec
- Update the Tool call logging to remove "Unknown"
Fixes #2298 
---
---
---

gemini-tool-role-fix-ag-2920

---

cookbook/tools/mcp/README.md
cookbook/tools/mcp/include_exclude_tools.py
cookbook/tools/mcp/sequential_thinking.py
libs/agno/agno/tools/mcp.py

This helps where MCP servers are really big. It helps to be able to control which tools are actually added to the model.
---
---
---

Add ability to include/exclude tools in MCP

---

cookbook/agent_concepts/knowledge/search_type/hybrid_search.py
cookbook/agent_concepts/knowledge/search_type/keyword_search.py
cookbook/agent_concepts/knowledge/search_type/vector_search.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/sync_router.py

Fix for [2557](https://github.com/agno-agi/agno/issues/2557)
---
---
---

Bug fix for Workflow session retrieval

---

libs/agno/agno/playground/schemas.py

Add Team to Team members response definition

---

README.md

- **Summary of changes**: Fixed incorrect instantiation of agent team from `Agent` to `Team`, resolving runtime errors using example code.
- **Related issues**: Resolves TypeError due to incorrect class usage.
- **Motivation and context**: The previous example incorrectly instantiated an agent team using the `Agent` class, causing a runtime error because the `Agent` class does not accept the `mode` argument. Using the correct `Team` class resolves this issue.
- **Environment or dependencies**: No changes required.
- **Impact on metrics**: Not applicable.
---
---
---
- Error before fix:
```python
Traceback (most recent call last):
File "/home/anthony/Téléchargements/langchain/b.py", line 27, in <module>
agent_team = Agent(
TypeError: …
```

fix: multi agent teams example

---

libs/agno/agno/agent/agent.py

- **Summary of changes**: Default reasoning bug fix and logging improvement 
Fixes # 2572
---
---
---

reasoning-fix-ag-2923

---

libs/agno/agno/playground/sync_router.py

Add sync router version of multimodal run

---

libs/agno/agno/models/google/gemini.py
libs/agno/agno/playground/sync_router.py

- **Summary of changes**: Fix bug with Function call results for Gemini and also implement proper role mapping
Fixes #2589 
---
---
---

fix-gemini-fc-result-ag-2926

---

libs/agno/pyproject.toml

Release 1.2.6

---

.github/pull_request_template.md
evals/performance/simple_response.py

This PR updates the PR template.

Update PR template

---

.github/pull_request_template.md

pr_template_update

---

cookbook/examples/teams/coordinate/content_team.py
cookbook/playground/mcp_demo.py

This shows how to use an MCP tool in an agent in a playground app.
---
---
---

MCP playground example

---

libs/agno/agno/agent/agent.py
libs/agno/agno/playground/sync_router.py

- **Summary of changes**: Indentation fix for print response 
Fixes #2585 
---
---
---

reasoning-fix-ag-2924

---

cookbook/agent_concepts/knowledge/csv_kb.py
cookbook/agent_concepts/knowledge/csv_kb_async.py
cookbook/agent_concepts/knowledge/csv_url_kb_async.py
libs/agno/agno/document/reader/base.py
libs/agno/agno/document/reader/csv_reader.py
libs/agno/agno/knowledge/csv.py
libs/agno/agno/knowledge/csv_url.py
libs/agno/agno/utils/http.py
libs/agno/pyproject.toml
libs/agno/tests/integration/knowledge/test_csv_knowledge_base.py
libs/agno/tests/integration/knowledge/test_csv_url_knowledge_base.py
libs/agno/tests/unit/reader/test_csv_reader.py

add `csv` and `csv url` reader and kb with tests
---
---

async support for csv reader and kb with tests

---

libs/agno/agno/run/response.py
libs/agno/agno/tools/function.py
libs/agno/agno/utils/http.py

Async generators can not be awaited, this fixes that.
---
---

Fix issue with async generators

---

libs/infra/agno_aws/agno/aws/resource/elasticache/cluster.py

follwing -> following
---
---
---

chore: update cluster.py

---

libs/agno/agno/agent/agent.py

- Provide more informative feedback when structured outputs are supported but not enabled
- Provide feedback when a model does not support structured or JSON schema outputs
---
---

updated logging messages in Agent class

---

cookbook/agent_concepts/knowledge/embedders/gemini_embedder.py
libs/agno/agno/embedder/google.py

This also allows us to change the output dimension.
---
---

Make the default embedder the latest model from Gemini

---

libs/agno/agno/tools/function.py

the required/additionalProperties fields are not carried over correctly. This fixes it.
---
---

Fix cases where tools passed to internal agents fail

---

cookbook/examples/agents/thinking_finance_agent.py
cookbook/reasoning/tools/claude_finance_agent.py
libs/agno/agno/agent/agent.py
libs/agno/agno/tools/function.py
libs/agno/agno/tools/thinking.py
libs/agno/agno/tools/toolkit.py

Add instructions for toolkits
---
---

Toolkit Instructions

---

cookbook/tools/mcp/airbnb.py
cookbook/tools/mcp/filesystem.py
cookbook/tools/mcp/include_exclude_tools.py
cookbook/tools/mcp/multiple_servers.py
libs/agno/agno/tools/mcp.py
libs/agno/agno/utils/mcp.py

This adds an alternative way to use MCP tools for a simpler design.
---
---

MCPTools Simpler command flow

---

cookbook/tools/mcp/README.md
cookbook/tools/mcp/airbnb.py
cookbook/tools/mcp/filesystem.py
cookbook/tools/mcp/github.py
cookbook/tools/mcp/include_exclude_tools.py
cookbook/tools/mcp/include_tools.py
cookbook/tools/mcp/multiple_servers.py
cookbook/tools/mcp/sequential_thinking.py
libs/agno/agno/tools/mcp.py
libs/agno/agno/utils/mcp.py

MCP Cleanups

---

libs/agno/agno/models/google/gemini.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/mcp.py
libs/agno/pyproject.toml
libs/agno/tests/integration/models/aws/bedrock/test_multimodal.py
libs/agno/tests/integration/teams/test_route.py

- **Simpler MCP Interface**: Added `MultiMCPTools` to support multiple server connections and simplified the interface to only allow `command` to be passed. See [these examples](https://github.com/agno-agi/agno/blob/382667097c31fbb9f08783431dcac5eccd64b84a/cookbook/tools/mcp) of how to use it.

Release 1.2.9

---

cookbook/reasoning/agents/finance_agent.py
cookbook/reasoning/tools/claude_finance_agent.py
libs/agno/agno/agent/agent.py

Fix structured outputs
---
---

Fix: structured outputs

---

cookbook/agent_concepts/other/datetime_instructions.py

Cookbook showing use of `add_datetime_to_instructions` and `timezone_identifier`.
---
---

datetime-cookbook-ag-2962

---

cookbook/agent_concepts/other/datetime_instructions.py
cookbook/reasoning/tools/openai_reasoning_tools.py
cookbook/tools/mcp/stripe.py
libs/agno/agno/agent/agent.py
libs/agno/agno/knowledge/website.py
libs/agno/agno/tools/reasoning.py

Improve Reasoning Instructions and make instructions and add_few_shot optional

Improve Reasoning Instructions

---

libs/agno/agno/vectordb/chroma/chromadb.py

fixes #2692
---
---
to replicate : 
-> upgrade to chromadb to latest version and run this cookbook  `cookbook/agent_concepts/knowledge/vector_dbs/chroma_db.py`
-> https://docs.trychroma.com/docs/querying-collections/query-and-get#choosing-which-data-is-returned

chroma db remove IncludeEnums dependency

---

libs/agno/agno/models/openai/responses.py
libs/agno/agno/reasoning/step.py
libs/agno/tests/integration/models/openai/responses/test_basic.py

Fix structured outputs for OpenAI Response

---

libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/schemas.py
libs/agno/agno/playground/sync_router.py

imports error fix

---

cookbook/teams/memory/01_chat_history.py
cookbook/teams/memory/03_user_memories.py
cookbook/teams/memory/04_agentic_context.py
cookbook/teams/memory/05_team_manages_memory.py
cookbook/teams/memory/06_team_session_summaries.py
cookbook/teams/memory/utils.py
libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/schemas.py
libs/agno/agno/playground/sync_router.py
libs/agno/tests/unit/memory/test_memory.py

Import fixes

---

cookbook/agent_concepts/memory/04_agentic_memory_different_models.py
cookbook/agent_concepts/memory/05_memory_search.py
cookbook/agent_concepts/memory/07_agent_creates_memories.py
cookbook/agent_concepts/memory/13_multi_user_multi_session_chat_concurrent.py
cookbook/agent_concepts/memory/db/postgres.py
libs/agno/agno/agent/agent.py
libs/agno/agno/memory/v2/db/postgres.py
libs/agno/agno/memory/v2/manager.py
libs/agno/agno/memory/v2/memory.py

Memory Update

---

cookbook/examples/apps/sql_agent/app.py
libs/agno/agno/models/openai/responses.py
libs/agno/agno/utils/models/openai_responses.py
libs/agno/tests/integration/models/openai/chat/test_basic.py
libs/agno/tests/integration/models/openai/responses/test_basic.py

Update OpenAIResponses response format structure. The `required` list is pre populated and does not need to be created again
---
---

structured-outputs-fix-ag-2966

---

README.md
libs/agno/agno/playground/playground.py

This will address issues where playground apps don't work on initialise because the agent hasn't run yet.
---
---

Add default IDs for agent/team/workflow in playground apps

---

cookbook/examples/apps/sql_agent/app.py
cookbook/reasoning/agents/capture_reasoning_content_default_COT.py
libs/agno/agno/agent/agent.py
libs/agno/agno/run/response.py
libs/agno/tests/integration/agent/test_reasoning_content_default_COT.py

add reasoning_content on run_response
Loom walkthrough-
https://www.loom.com/share/90e776db659d470692adc55d3f64cc42?sid=26cf9ad3-2c6f-4c22-a4b9-078db7d13df3
---
- [] Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
---

add reasoning_content on run_response

---

cookbook/examples/apps/sql_agent/app.py
cookbook/reasoning/tools/capture_reasoning_content_reasoning_tools.py
libs/agno/agno/agent/agent.py
libs/agno/agno/run/response.py
libs/agno/agno/tools/reasoning.py
libs/agno/tests/integration/agent/test_reasoning_content.py
libs/agno/tests/integration/agent/test_reasoning_content_tools.py

ThinkingTools/Reasoningtools set reasoning_content
Loom walkthrough- https://www.loom.com/share/9775709b6fcd41c0a9156302af81842b?sid=a38c796e-0df2-4d57-98f4-51ea895c64e9
Cookbook to see if `reasoning_content` is being populated-
---
---

ThinkingTools/Reasoningtools set reasoning_content

---

libs/agno/agno/agent/agent.py

fix reasoning step tool
---
---

fix reasoning step tool

---

cookbook/README.md

PR to fix reasoning cookbooks link.
---
---

Update reasoning cookbooks link

---

libs/agno/agno/agent/agent.py

Update thinking tools reasoning completed event

---

libs/agno/agno/agent/agent.py

Fix duplication for reasoning

---

cookbook/examples/apps/sql_agent/app.py
cookbook/reasoning/tools/gemini_reasoning_tools.py
cookbook/tools/confluence_tools.py
libs/agno/agno/memory/v2/db/redis.py
libs/agno/agno/storage/redis.py
libs/agno/agno/tools/confluence.py
libs/agno/pyproject.toml
libs/agno/tests/unit/tools/test_confluence.py

Add ability to bypass ssl verification on custom confluence servers.
---
---

Confluence bypass ssl

---

cookbook/examples/apps/sql_agent/app.py
evals/performance/memory_response.py
libs/agno/agno/eval/perf.py
libs/agno/agno/memory/v2/db/redis.py
libs/agno/agno/storage/redis.py

fix-perf-evals-ag-2985

---

libs/agno/agno/tools/e2b.py
libs/agno/tests/unit/tools/test_e2b.py

fixes https://discord.com/channels/965734768803192842/965734768803192845/1359726850003177503
---
---

fix true and false lowercase issue

---

cookbook/models/google/gemini/pdf_input_file_upload.py
cookbook/models/google/gemini/pdf_input_url.py
libs/agno/agno/media.py
libs/agno/agno/models/google/gemini.py

Updates to Gemini file upload including ability to directly provide a Gemini File object to the Agent
---
---

gemini-file-update-ag-2994

---

cookbook/models/ollama/set_temperature.py

Ollama temperature example cookbook

---

libs/agno/agno/storage/dynamodb.py

Remove `'team_session_id` from agent attributes
Tested satisfactorily after removal.
(If applicable, issue number: #2797 )
---
- [X ] Code complies with style guidelines
- [X ] Ran format/validation scripts (`./scripts/format.sh` and `./scripts/validate.sh`)
- [X ] Self-review completed
- [X ] Documentation updated (comments, docstrings)
- [X ] Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
- [X ] Tested in clean environment
- [ X] Tests added/updated (if applicable)
---

fix: DynamoDBStorage #2797

---

cookbook/agent_concepts/context/add_context.py
cookbook/agent_concepts/context/agent_context.py
cookbook/agent_concepts/state/session_state.py
cookbook/agent_concepts/state/state_in_prompt.py
libs/agno/agno/embedder/azure_openai.py
libs/agno/agno/models/base.py
libs/agno/agno/models/deepseek/deepseek.py
libs/agno/agno/utils/pprint.py
libs/agno/tests/integration/agent/test_agent_with_storage_and_memory.py

Examples for session state

---

cookbook/agent_concepts/state/session_state_storage.py
cookbook/workflows/simple_cache_workflow.py
libs/agno/agno/agent/agent.py

Give db session state preference

Give db session state preference

---

libs/agno/agno/tools/reasoning.py

fix formatting

---

libs/agno/agno/eval/accuracy.py

Fix accuracy eval

---

libs/agno/agno/tools/firecrawl.py

Issue link- https://github.com/agno-agi/agno/issues/2883
---
---

fix: firecrawl scrape api

---

libs/agno/agno/agent/agent.py
libs/agno/agno/api/schemas/agent.py
libs/agno/agno/api/schemas/team.py
libs/agno/agno/team/team.py

Api registrations team fix

---

cookbook/demo/sql/agents.py
cookbook/reasoning/models/azure_ai_foundry/reasoning_model_deepseek.py
libs/agno/agno/agent/agent.py
libs/agno/agno/reasoning/azure_ai_foundry.py

Adds models via AzureAI Foundry for reasoning.
Fixes #2860 
---
---

Add azure AI foundry for reasoning

---

libs/agno/agno/agent/agent.py

agent.py fix

---

cookbook/agent_concepts/memory/15_memory_demo.py
libs/agno/agno/agent/agent.py

Fix: memory hydration

---

libs/agno/agno/embedder/huggingface.py

fix-hf-embedder-ag-3016

---

libs/agno/agno/storage/dynamodb.py

Previously, credentials were directly passed or default credentials were used for DynamoDB access. This update allows using an AWS named profile for authentication, enhancing flexibility and alignment with AWS best practices.
[#2984](https://github.com/agno-agi/agno/issues/2984)
---
---

feat(dynamodb): Add support for AWS profile-based authentication.

---

libs/agno/agno/agent/agent.py

Fix a bug with Session Metrics not getting populated
#2962 
---
---

fix-session-metrics-ag-3024

---

libs/agno/agno/run/response.py
libs/agno/agno/run/team.py

Currently using perplexity model with playground is breaking the streaming.
https://community.agno.com/t/i-am-getting-json-citation-error-on-sonar-pro/1075/2?u=monali
Here is an agent config to test - 
```python
perplexity_agent = Agent(
name="Perplexity Agent",
agent_id="perplexity-agent",
model=Perplexity(id="sonar-pro"),
debug_mode=True,
storage=SqliteStorage(
table_name="perplexity_agent",
db_file=agent_storage_file,
auto_upgrade_schema=True,
),
)
```
Before - 
After -

fix: perplexity citations handling for playground

---

libs/agno/agno/reasoning/openai.py

o4-mini support for reasoning.
Issue number: #2990
---
---

[Reasoning model] Added support for o4-mini and probably o4 when released. Closes #2990

---

cookbook/agents_from_scratch/simple_agent.py
cookbook/playground/teams_demo.py
libs/agno/agno/agent/agent.py
libs/agno/agno/api/app.py
libs/agno/agno/api/routes.py
libs/agno/agno/api/schemas/app.py
libs/agno/agno/playground/playground.py
libs/agno/agno/team/team.py

app registration

---

libs/agno/pyproject.toml

Version 1.4.3 with Llama API Model class and general improvements

Release-1.4.3

---

libs/agno/agno/models/meta/llama_openai.py

Llama OpenAI tool call streaming update
---
---

llama-api-update-ag-3035

---

cookbook/models/meta/README.md
cookbook/models/meta/llama/async_basic.py
cookbook/models/meta/llama/async_basic_stream.py
cookbook/models/meta/llama/async_knowledge.py
cookbook/models/meta/llama/async_tool_use.py
cookbook/models/meta/llama/async_tool_use_stream.py
cookbook/models/meta/llama/basic.py
cookbook/models/meta/llama/knowledge.py
cookbook/models/meta/llama/storage.py
cookbook/models/meta/llama/structured_output.py
cookbook/models/meta/llama_openai/async_basic.py
cookbook/models/meta/llama_openai/async_basic_stream.py
cookbook/models/meta/llama_openai/async_tool_use.py
cookbook/models/meta/llama_openai/async_tool_use_stream.py
libs/agno/agno/models/meta/llama.py
libs/agno/agno/models/meta/llama_openai.py
libs/agno/pyproject.toml

Few updates:
metrics coming now for both stream and non-stream cases-
structured output-
---
---

llama api fixes and updates

---

cookbook/agent_concepts/knowledge/custom/async_retriever.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/meta/llama_openai.py
libs/agno/tests/unit/tools/test_github.py

add support for async retriever
---
---

add support for async retriever

---

libs/agno/agno/memory/v2/memory.py

Existence check for memories_id was missing, failed in RLS tests.
- [x ] Bug fix
---
- [x ] Code complies with style guidelines
- [x ] Self-review completed
- [x ] Tested in clean environment
---

delete_user_memory missing existence check

---

cookbook/models/google/gemini/video_input_local_file_upload.py
cookbook/models/google/gemini/video_input_youtube.py
libs/agno/agno/media.py
libs/agno/agno/models/google/gemini.py

Support for video URL input
Issue number: #2937 2937
---
---

gemini-video-url-ag-3017

---

cookbook/models/google/gemini/async_basic.py
cookbook/models/google/gemini/async_basic_stream.py
cookbook/models/google/gemini/async_tool_use.py
cookbook/models/google/gemini/basic.py
cookbook/models/google/gemini/basic_stream.py
cookbook/models/google/gemini/knowledge.py
cookbook/models/google/gemini/storage.py
cookbook/models/google/gemini/storage_and_memory.py
cookbook/models/google/gemini/structured_output.py
cookbook/models/google/gemini/tool_use.py
cookbook/models/google/gemini/tool_use_stream.py
cookbook/models/google/gemini/vertexai.py
cookbook/reasoning/models/xai/reasoning_effort.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/team/team.py
libs/agno/pyproject.toml
libs/agno/tests/integration/agent/test_reasoning_content_knowledge_tools.py
libs/agno/tests/integration/models/google/test_multimodal.py
libs/agno/tests/integration/models/google/test_tool_use.py
libs/agno/tests/integration/models/meta/llama/test_multimodal.py
libs/agno/tests/integration/models/openai/responses/test_tool_use.py
libs/agno/tests/integration/models/xai/test_basic.py
libs/agno/tests/integration/models/xai/test_multimodal.py
libs/agno/tests/integration/models/xai/test_tool_use.py
libs/agno/tests/integration/storage/test_json_storage_workflow.py
libs/agno/tests/integration/storage/test_sqlite_storage_workflow.py
libs/agno/tests/integration/storage/test_yaml_storage_workflow.py
libs/agno/tests/integration/teams/test_team_metrics.py

- **OpenAI File Support:** Added support for `File` attached to prompts for agents with `OpenAIChat` models.
- **Llama API:** Various improvements for Llama and LlamaOpenAI model classes including structured output and image input.  
- **Async Custom Retriever**: The `retriever` parameter can now be an `async` function to be used with `agent.arun` and `agent.aprint_response`.
- **Gemini Video URL Input**: Added support for `Video(url=...)` for Gemini.
- **OpenAI Responses o3 / o4 Tools**: Fixed broken tool use for advanced reasoning models on `OpenAIResponses`.
- **MCP on CLI Support**: Fixed support for `MCPTools` usage while calling `agent.acli_app`.

Release 1.4.4

---

libs/agno/agno/agent/agent.py
libs/agno/agno/document/reader/website_reader.py

add warning if async is used with run in retriever
---
---

add warning if async is used with run in retriever

---

libs/agno/agno/utils/mcp.py

The tool description is often ignored by tools, but it would fail for mcp servers that do validation. It is not necessary.
Fixes #3071 
---
---

Remove MCP tool description

---

cookbook/agent_concepts/knowledge/embedders/aws_bedrock_embedder.py
cookbook/agent_concepts/memory/16_custom_memory_instructions.py
libs/agno/agno/agent/agent.py
libs/agno/agno/document/chunking/fixed.py
libs/agno/agno/document/reader/base.py
libs/agno/agno/document/reader/firecrawl_reader.py
libs/agno/agno/embedder/aws_bedrock.py
libs/agno/agno/knowledge/agent.py
libs/agno/tests/integration/teams/test_team_metrics.py
libs/agno/tests/unit/reader/test_firecrawl_reader.py
libs/agno/tests/unit/reader/test_url_reader.py

AWS Bedrock embedder- Cohere Embed-multilingual v3
---
---

add aws bedrock embedder

---

cookbook/examples/agents/recipe_rag_image.py

An agent that uses RAG to get recipes and generates images

---

cookbook/storage/mongodb_storage/mongodb_storage_for_team.py
libs/agno/agno/team/team.py

We incorrectly instantiate memory for teams,
---
---

Fix memory for teams

---

libs/agno/agno/playground/async_router.py
libs/agno/agno/playground/playground.py
libs/agno/agno/playground/sync_router.py

New status endpoint to help differentiate between different apps with same endpoints

feat: apps status

---

cookbook/observability/weave_op.py

Observability example with weave
---
---

weave-cookbook-ag-3050

---

cookbook/tools/mcp/notion_mcp_agent.py

An example for Notion MCP
---
---

Notion MCP agent

---

cookbook/observability/weave_op.py
libs/agno/agno/agent/agent.py
libs/agno/tests/integration/agent/test_metrics.py

Prevent cumulation of metrics for messages taken from history 
---
---

metrics-fix-ag-3052

---

libs/agno/agno/embedder/google.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/tools/apify.py
libs/agno/agno/tools/dalle.py
libs/agno/agno/tools/models/gemini.py
libs/agno/agno/tools/models/groq.py
libs/agno/agno/utils/gemini.py
libs/agno/agno/vectordb/clickhouse/clickhousedb.py
libs/agno/tests/integration/models/google/test_basic.py
libs/agno/tests/unit/tools/models/test_gemini.py

Massive tests fix code refactor

---

libs/agno/agno/agent/agent.py

Fix the location of reasoning functions
---
---

agent-reasoning-update-ag-3057

---

cookbook/observability/langfuse_via_openlit.py
libs/agno/pyproject.toml

Basic implementation of Langfuse using OpenLit
---
---

Add cookbook for langfuse via openlit

---

cookbook/reasoning/agents/ibm_watsonx_default_COT.py
cookbook/reasoning/tools/ibm_watsonx_reasoning_tools.py

update reasoning tools cookbook with ibm-watsonx
---
---

update reasoning tools cookbook with ibm-watsonx

---

cookbook/models/anthropic/pdf_input_url.py
cookbook/models/anthropic/web_search.py
cookbook/observability/weave_op.py
libs/agno/agno/models/anthropic/claude.py
libs/agno/tests/integration/agent/test_metrics.py

Web search support for Claude
---
---

feat-claude-web-search-ag-3053

---

cookbook/agent_concepts/state/session_state_user_id.py
cookbook/observability/langfuse_via_openlit.py
libs/agno/agno/agent/agent.py
libs/agno/agno/team/team.py

Keep track of the current user ID and current session ID to use in tools
---
---

[feat] Add current_user_id and current_session_id

---

cookbook/tools/mcp/supabase.py

A Supabase MCP agent eample 
---
---

feat: Supabase MCP app

---

libs/agno/pyproject.toml

chore: Release 1.5.0

---

cookbook/agent_concepts/other/scenario_testing.py
cookbook/reasoning/agents/cerebras_llama_default_COT.py
cookbook/reasoning/tools/cerebras_llama_reasoning_tools.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/openai/responses.py
libs/agno/tests/integration/models/google/test_tool_parsing.py

update cerebras reasoning cookbooks
---
---

chore: update cerebras reasoning cookbooks

---

.github/workflows/pr-lint.yml

Update to PR lint workflow
---
---

chore: update-pr-wf-ag-3172

---

README.md

Update Readme with badges
---
---

chore-readme-update-ag-3190

---

.github/workflows/release.yml
libs/agno/pyproject.toml
libs/infra/agno_aws/LICENSE
libs/infra/agno_aws/README.md
libs/infra/agno_aws/pyproject.toml
libs/infra/agno_docker/LICENSE
libs/infra/agno_docker/README.md

- **Nebius Model Provider**: Added [Nebius](https://studio.nebius.com/) as a model provider.
- **Extended Filters Support on Vector DBs**: Added filtering support for other vector DBs
- pgvector
- Milvus
- Weaviate
- Chroma
- **Redis SSL**: Added the `ssl` parameter to `Redis` storage.
- **Improve release tests workflow:** add a script to do model specific minimal setup installation on release

chore: Release 1.5.1

---

libs/agno/agno/app/whatsapp/async_router.py
libs/agno/agno/app/whatsapp/sync_router.py

Enhance image handling in WhatsApp app

---

cookbook/agent_concepts/other/success_criteria.py
libs/agno/agno/agent/agent.py

feat: add-succes_criteria-to-agent

---

libs/agno/agno/models/litellm/chat.py

Fixed issue with usage in LiteLLM not including cached tokens. Unified it with OpenAI Api code.
---
---
This is bringing LiteLLM usage handling inline with rest of the code.

fix: LiteLLM incomplete usage

---

libs/agno/agno/tools/todoist.py

- Fix get_active_tasks handling of nested list response
- Add attribute existence checks in Task to dict conversion
- Correct Due object datetime attribute handling
- Add default=str to json.dumps for datetime serialization
This PR fixes #3246 by addressing several bugs in the Todoist integration:
**Issues Fixed:**
1. Fixed `get_active_tasks` to properly handle the nested list structure returned by the API
2. Added attribute existence checks when converting Task objects to dictionaries
3. Corrected handling of Due object attributes that were causing errors
4. Added `default=str` parameter to all `json.dumps` calls to handle datetime serialization
**Testing:**
Tested with active Todoist account and verified all functions now work without errors.
---
---
Add any important context …

fix: Fixed few bugs in Todoist integration tools

---

libs/agno/agno/tools/firecrawl.py

---
This pull request updates the `FireCrawl` integration to support the latest API changes and extends functionality by integrating the `map` feature.
Initially, I encountered an error while trying to use the `crawl` function due to deprecated or unsupported API usage. This PR updates the `crawl` logic to comply with the new FireCrawl API.
Additionally, I discovered that FireCrawl now offers a `map` function that can extract internal links from a given URL. I have integrated this capability to enhance link discovery and crawling coverage.
---
---
---
* No breaking changes introduced.
* FireCrawl API changes required adjustments in request formatting and response handling.
* The new `map` feature integration can help extend the scope of scraping without crawling by discovering more pages …

Update FireCrawl: Fix Crawl Bug & Add Map Functionality

---

cookbook/examples/agents/web_extraction_agent.py

Firecrawl web extraction agent
---
---

Firecrawl web extraction agent

---

cookbook/agent_concepts/memory/17_builtin_memory_with_session_summary.py
cookbook/evals/accuracy/accuracy_9_11_bigger_or_9_99.py
cookbook/evals/accuracy/accuracy_basic.py
cookbook/evals/accuracy/accuracy_with_given_answer.py
cookbook/evals/accuracy/accuracy_with_tools.py
libs/agno/agno/eval/accuracy.py

Update Accuracy Eval

---

libs/agno/agno/eval/accuracy.py
libs/agno/pyproject.toml

- Updates to Accuracy Evals
---
---

chore: Release 1.5.3

---

cookbook/observability/teams/langfuse_via_openinference_async_team.py
cookbook/observability/teams/langfuse_via_openinference_team.py

update cookbooks for teams observability
---
---

chore: update cookbooks for teams observability

---

cookbook/observability/teams/langfuse_via_openinference_async_team.py
cookbook/observability/teams/langfuse_via_openinference_team.py
cookbook/tools/firecrawl_tools.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/firecrawl.py
libs/agno/tests/unit/tools/test_firecrawl.py

This adds the newly released firecrawl search to the FirecrawlTools
---
---

feat: Add firecrawl search

---

libs/agno/agno/models/response.py

The user_input_schema field may be None.
---
---

fix user_input_schema

---

cookbook/tools/mcp/pipedream_google_calendar.py
cookbook/tools/mcp/pipedream_linkedin.py
cookbook/tools/mcp/pipedream_slack.py

Add examples on using Pipedream MCP servers

feat: pipedream mcp examples

---

libs/agno/agno/vectordb/mongodb/mongodb.py

Fixed embedding dimensions in mongodb vector store
---
---

fix embedding dimensions key

---

cookbook/agent_concepts/knowledge/vector_dbs/lance_db/lance_db_hybrid_search.py
cookbook/agent_concepts/knowledge/vector_dbs/mongo_db/mongo_db_hybrid_search.py
cookbook/agent_concepts/knowledge/vector_dbs/pgvector_db/pgvector_hybrid_search.py
cookbook/agent_concepts/knowledge/vector_dbs/qdrant_db/qdrant_db_hybrid_search.py
cookbook/agent_concepts/knowledge/vector_dbs/weaviate_db/weaviate_db_hybrid_search.py
cookbook/models/mistral/structured_output_with_tool_use.py
libs/agno/agno/models/mistral/mistral.py
libs/agno/agno/vectordb/couchbase/couchbase.py
libs/agno/agno/vectordb/lancedb/lance_db.py
libs/agno/agno/vectordb/milvus/milvus.py
libs/agno/agno/vectordb/mongodb/mongodb.py
libs/agno/tests/integration/models/mistral/test_tool_use.py

add cookbooks for hybrid search
---
---

chore: add cookbooks for hybrid search

---

cookbook/agent_concepts/user_control_flows/confirmation_required_with_run_id.py
libs/agno/agno/agent/agent.py
libs/agno/agno/app/playground/async_router.py
libs/agno/agno/app/playground/sync_router.py
libs/agno/agno/models/response.py
libs/agno/agno/run/response.py
libs/agno/tests/integration/agent/conftest.py
libs/agno/tests/integration/agent/test_agent_with_storage_and_memory.py
libs/agno/tests/integration/agent/test_user_confirmation_flows.py
libs/agno/tests/integration/agent/test_user_input_flows.py

The behaviour of continueing from a run ID was broken. 
---
---

fix: User confirmation flows with run ID

---

cookbook/agent_concepts/knowledge/filters/filtering_pinecone.py
libs/agno/agno/vectordb/pineconedb/pineconedb.py
libs/agno/tests/integration/agent/test_agent_multimodal.py
libs/agno/tests/integration/conftest.py
libs/agno/tests/integration/teams/test_team_multimodal.py
libs/agno/tests/unit/vectordb/test_pineconedb.py

PineconeDB method search had filters commented out.
---
---
none

fix: enable filters for pinecone 

---

libs/agno/agno/tools/searxng.py
libs/agno/tests/unit/tools/test_searxng.py

Fixes Searxng tool initialization error 
`AttributeError: 'Searxng' object has no attribute 'include_tools'`
Add basic unit tests for the tool
---
---

fix: Searxng tool initialization and add comprehensive unit tests.

---

cookbook/examples/agents/competitor_analysis_agent.py

Competitor analysis agent
---
---

feat: Competitor analysis agent

---

cookbook/apps/fastapi/advanced.py
cookbook/evals/performance/instantiation_agent.py
cookbook/evals/performance/instantiation_agent_with_tool.py
cookbook/evals/performance/instantiation_team.py
cookbook/evals/performance/response_with_memory_updates.py
cookbook/evals/performance/response_with_storage.py
cookbook/evals/performance/simple_response.py
cookbook/evals/reliability/single_tool_calls/google/calculator.py
libs/agno/agno/app/fastapi/app.py
libs/agno/agno/app/fastapi/async_router.py
libs/agno/agno/app/fastapi/sync_router.py
libs/agno/agno/app/playground/app.py

Update to allow FastAPIApp to have multiple agents/teams at the same time.
---
---

feat: Change fastapi app to allow multiple agents/teams

---

libs/agno/agno/agent/agent.py
libs/agno/agno/models/message.py
libs/agno/agno/reasoning/helpers.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/mcp.py
libs/agno/tests/integration/agent/test_agent_custom_retriever.py

Make sure custom retrievers correctly raise exceptions to the top for function runs.
Add `add_references` for team
#3406 
---
---

fix: Raise error from custom retriever

---

libs/agno/agno/app/whatsapp/async_router.py
libs/agno/agno/app/whatsapp/sync_router.py
libs/agno/agno/utils/whatsapp.py

Typing indicator for whatsapp app
issue number: #3437 
---
---

feat: Typing Indicator

---

libs/agno/agno/models/anthropic/claude.py
libs/agno/agno/utils/models/claude.py

Anthropic will sometimes respond with an empty response. We avoid sending these back to anthropic.
#3466 
---
---

fix: Issue empty anthropic responses

---

libs/agno/agno/agent/agent.py
libs/agno/agno/models/base.py
libs/agno/agno/team/team.py
libs/agno/tests/integration/agent/test_agent_state_substitution.py

This fixes cases where there is json embedded in the messages that needs to be maintained.
(If applicable, issue number: #3469 )
---
---

fix: State in message substitution

---

.github/workflows/test_on_release.yml
libs/agno/agno/utils/models/claude.py
libs/agno/pyproject.toml
libs/agno/tests/integration/models/aws/bedrock/test_tool_use.py
libs/agno/tests/integration/models/aws/claude/test_tool_use.py
libs/agno/tests/integration/models/azure/ai_foundry/test_tool_use.py
libs/agno/tests/integration/models/azure/openai/test_tool_use.py
libs/agno/tests/integration/models/cohere/test_tool_use.py
libs/agno/tests/integration/models/google/test_tool_use.py
libs/agno/tests/integration/models/groq/test_tool_use.py
libs/agno/tests/integration/models/ibm/watsonx/test_tool_use.py
libs/agno/tests/integration/models/nvidia/test_tool_use.py
libs/agno/tests/integration/models/ollama/test_tool_use.py
libs/agno/tests/integration/models/openai/chat/test_tool_use.py
libs/agno/tests/integration/models/openai/responses/test_tool_use.py
libs/agno/tests/integration/models/xai/test_tool_use.py
libs/agno/tests/integration/teams/test_coordinate.py

- **Playground File Upload**: We now support file upload via the Agno Playground. This will send PDF, CSV, Docx, etc files directly to the agents/teams for interpretation by the downstream LLMs.  If you have a knowledge base attached to the agent/team, it will upload the file to the knowledge base instead.
- **Exa Research**: Added `research` tool on `ExaTools`. See more on their [docs](https://docs.exa.ai/reference/exa-research) about how research works.
- **Whatsapp Type Indicator**: Add type indicator to Whatsapp responses.
- **State in Messages Fixes**: Fixed issues around nested json inside messages and adding state into messages.

chore: Release 1.5.10

---

libs/agno/agno/app/playground/sync_router.py

revert error response for workflow sync router sessions

---

libs/agno/agno/tools/apify.py

Apify incorrectly implemented tool registration
---
---

fix: Apify Bug

---

libs/agno/agno/app/whatsapp/async_router.py
libs/agno/agno/app/whatsapp/sync_router.py
libs/agno/agno/utils/string.py
libs/agno/tests/unit/utils/test_string.py

Fix multiple image generations, send multiple generated images
(If applicable, issue number: #3510)
---
---

Fix multi Image generations

---

cookbook/tools/cartesia_tools.py
libs/agno/agno/utils/audio.py

Change the save method for cartesia example
---
---

chore: Update file save method

---

cookbook/agent_concepts/knowledge/embedders/nebius_embedder.py
libs/agno/agno/embedder/nebius.py

Adds embedding support via Nebius
Output of cookbook:
`Embeddings: [0.0041656494140625, 0.002140045166015625, -0.005718231201171875, 0.007724761962890625, -0.01416015625]
Dimensions: 4096`
---
---

feat: Add Nebius embedding support

---

cookbook/apps/fastapi/advanced.py
libs/agno/agno/app/base.py
libs/agno/agno/app/fastapi/app.py

feat: Add version on FastAPIApp

---

cookbook/agent_concepts/knowledge/doc_kb_async.py
cookbook/agent_concepts/knowledge/embedders/nebius_embedder.py
libs/agno/agno/agent/agent.py
libs/agno/agno/app/base.py
libs/agno/agno/app/fastapi/app.py
libs/agno/agno/app/fastapi/async_router.py
libs/agno/agno/embedder/nebius.py
libs/agno/agno/utils/json_schema.py
libs/agno/tests/integration/models/google/test_tool_use.py
libs/agno/tests/integration/models/openai/responses/test_tool_use.py

Fixes/adds enum support for custom tools on models. Added lightweight enum detection to the JSON schema generation:
---
---

fix: Enums support on custom tools for all models

---

cookbook/agent_concepts/knowledge/filters/csv/agentic_filtering.py
cookbook/agent_concepts/knowledge/filters/csv/filtering.py
cookbook/agent_concepts/knowledge/filters/csv/filtering_on_load.py
cookbook/agent_concepts/knowledge/filters/csv_url/agentic_filtering.py
cookbook/agent_concepts/knowledge/filters/csv_url/filtering.py
cookbook/agent_concepts/knowledge/filters/csv_url/filtering_on_load.py
libs/agno/agno/knowledge/csv.py
libs/agno/agno/knowledge/csv_url.py
libs/agno/agno/utils/json_schema.py
libs/agno/agno/utils/media.py

Metadata filtering support for `csv` and `csv_url` knowledge bases.
---
---
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210556506662771

feat: csv/csv-url metadata support

---

libs/agno/agno/utils/json_schema.py
libs/agno/agno/vectordb/mongodb/mongodb.py

MongoDB ObjectId serialization issue when using with agent.
---
---

fix: mongodb json searialization issue if object id in metadata

---

cookbook/teams/team_events.py
libs/agno/agno/agent/agent.py
libs/agno/agno/team/team.py
libs/agno/agno/vectordb/mongodb/mongodb.py
libs/agno/pyproject.toml
libs/agno/tests/integration/agent/test_event_streaming.py
libs/agno/tests/integration/knowledge/test_arxiv_knowledge_base.py
libs/agno/tests/integration/knowledge/test_csv_url_knowledge_base.py
libs/agno/tests/integration/knowledge/test_docx_knowledge_base.py
libs/agno/tests/integration/knowledge/test_firecrawl_knowledge_base.py
libs/agno/tests/integration/knowledge/test_json_knowledge_base.py
libs/agno/tests/integration/knowledge/test_md_knowledge_base.py
libs/agno/tests/integration/knowledge/test_pdf_bytes_knowledge_base.py
libs/agno/tests/integration/knowledge/test_pdf_knowledge_base.py
libs/agno/tests/integration/knowledge/test_pdf_url_knowledge_base.py
libs/agno/tests/integration/knowledge/test_text_knowledge_base.py
libs/agno/tests/integration/knowledge/test_url_knowledge_base.py
libs/agno/tests/integration/knowledge/test_website_knowledge_base.py
libs/agno/tests/integration/knowledge/test_youtube_knowledge_base.py

- **User Control Flows on Playground**: The Agno Platform now support user control flows on the playground.
- **Team & Agent Events on RunResponse:** Added `store_events` parameter to optionally add all events that happened during the course of an agent/team run on the `RunResponse`/`TeamRunResponse`.
- **Team Member Responses on Playground**: The Agno Platform now shows member responses during team runs.
- **Behind-the-scenes on Playground**: The Agno Platform now shows what is happening during runs, for both agents and teams.
- **Metadata filtering support for `csv` and `csv_url` knowledge bases:** Add knowledge filters support for these knowledge base types.
- **AG-UI Fix**: Fixed issue related to missing messages when using the Agno AG-UI app.
- **Chat History Fix**: Fixed issue …

chore: Release 1.6.3

---

cookbook/workflows/async_basic_pipeline_workflow.py
cookbook/workflows/async_basic_pipeline_workflow_stream.py
cookbook/workflows/async_custom_execution_function_workflow.py
cookbook/workflows/async_custom_execution_function_workflow_stream.py
cookbook/workflows/basic_custom_execution_function_workflow.py
cookbook/workflows/basic_custom_execution_function_workflow_stream.py
cookbook/workflows/basic_pipeline_workflow.py
cookbook/workflows/basic_pipeline_workflow_stream.py
cookbook/workflows/basic_workflow_shared_state_with_agent.py
cookbook/workflows/basic_workflow_shared_state_with_team.py
cookbook/workflows/pydantic_input_basic_pipeline_workflow.py
cookbook/workflows/selector_for_image_video_generation_pipelines.py
libs/agno/agno/run/v2/workflow.py
libs/agno/agno/workflow/v2/__init__.py
libs/agno/agno/workflow/v2/pipeline.py
libs/agno/agno/workflow/v2/step.py
libs/agno/agno/workflow/v2/types.py
libs/agno/agno/workflow/v2/workflow.py

Details- https://www.notion.so/Workflows-2-0-205733793ba280d782accdeb916f6135?source=copy_link
---
---

feat: workflows revised DX

---

cookbook/models/meta/llama/async_tool_use.py
cookbook/models/meta/llama/async_tool_use_stream.py
cookbook/models/meta/llama/tool_use.py
cookbook/models/meta/llama/tool_use_stream.py
cookbook/models/meta/llama_openai/async_tool_use.py
cookbook/models/meta/llama_openai/async_tool_use_stream.py
cookbook/models/meta/llama_openai/tool_use.py
cookbook/models/meta/llama_openai/tool_use_stream.py
cookbook/teams/team_events_route.py
libs/agno/agno/tools/google_bigquery.py
libs/agno/agno/vectordb/lancedb/lance_db.py

- update lance db upsert method for filter
- meta llama cookbooks update after they fixed- https://github.com/meta-llama/llama-api-python/issues/31
fixes: https://github.com/agno-agi/agno/issues/3577
---
---

chore: update lance db upsert method for filter

---

libs/agno/agno/vectordb/mongodb/mongodb.py

update mongo db hybrid search for filters
fixes: https://github.com/agno-agi/agno/issues/3515
---
---

fix: update mongo db hybrid search for filters

---

libs/agno/agno/eval/accuracy.py

Small fix for monitoring with accuracy evals when evaluating a given output

fix: monitoring fields for accuracy evals with given output

---

libs/agno/agno/tools/github.py

Fixing two bugs in the `github` tool.
issue number: #3636
---
-This is not working for me, all files get changed when I run this with `black` and `isort`... See [this PR](https://github.com/agno-agi/agno/pull/3602) where I shared some printscreens...
---

[fix] Fix GitHub tool create file #3636

---

cookbook/os/demo.py

fix: Update knowledge in os demo

---

libs/agno/agno/models/langdb/langdb.py

This change allows user to define custom langdb cloud API url.
---
---

Make langdb base url configurable

---

libs/agno/agno/models/cohere/chat.py

fix: cohere tool calling

---

cookbook/agent_concepts/other/debug_level.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/anthropic/claude.py
libs/agno/agno/models/aws/bedrock.py
libs/agno/agno/models/aws/claude.py
libs/agno/agno/models/azure/ai_foundry.py
libs/agno/agno/models/cerebras/cerebras.py
libs/agno/agno/models/cerebras/cerebras_openai.py
libs/agno/agno/models/cohere/chat.py
libs/agno/agno/models/google/gemini.py
libs/agno/agno/models/groq/groq.py
libs/agno/agno/models/huggingface/huggingface.py
libs/agno/agno/models/ibm/watsonx.py
libs/agno/agno/models/litellm/chat.py
libs/agno/agno/models/meta/llama.py
libs/agno/agno/models/mistral/mistral.py
libs/agno/agno/models/ollama/chat.py
libs/agno/agno/models/openai/chat.py
libs/agno/agno/models/openai/responses.py
libs/agno/agno/models/perplexity/perplexity.py
libs/agno/agno/models/vllm/vllm.py
libs/agno/agno/reasoning/default.py
libs/agno/agno/reasoning/helpers.py
libs/agno/agno/team/team.py
libs/agno/agno/utils/log.py
libs/agno/agno/utils/string.py
libs/agno/tests/unit/utils/test_string.py

This is to improve control over how verbose debug logs are. For now it is only used to control model logs, but will be used more in future.
---
---

feat: Add debug_level paramater

---

cookbook/models/google/gemini/README.md
cookbook/models/google/gemini/agent_with_thinking_budget.py
libs/agno/agno/models/google/gemini.py

Allow setting a thinking token budget and option to include thinking summary
---
---

feat: Gemini thinking configuration

---

cookbook/knowledge/basic_knowledge_manager.py
cookbook/knowledge/basic_sdk.py
cookbook/os/demo.py
libs/agno/agno/db/base.py
libs/agno/agno/db/postgres/postgres.py
libs/agno/agno/db/postgres/schemas.py
libs/agno/agno/db/schemas/knowledge.py
libs/agno/agno/document/base.py
libs/agno/agno/document/chunking/fixed.py
libs/agno/agno/document/document_v2.py
libs/agno/agno/document/reader/csv_reader.py
libs/agno/agno/document/reader/docx_reader.py
libs/agno/agno/document/reader/json_reader.py
libs/agno/agno/document/reader/pdf_reader.py
libs/agno/agno/document/reader/text_reader.py
libs/agno/agno/knowledge/cloud_storage/cloud_storage.py
libs/agno/agno/knowledge/knowledge.py
libs/agno/agno/os/managers/eval/schemas.py
libs/agno/agno/os/managers/knowledge/router.py
libs/agno/agno/os/managers/knowledge/schemas.py

feat: Knowledge uploads

---

cookbook/tools/serper_tools.py
libs/agno/agno/tools/serper.py
libs/agno/tests/unit/tools/test_serper.py
libs/agno/tests/unit/tools/test_serperdev.py

Add new tools to Serper
---
---
New tools

feat: Add new tools to Serper toolkit

---

libs/agno/agno/models/google/gemini.py

This includes thought tokens in the metrics for output tokens.  Specifically for Gemini 2.5
#3620 
---
---

fix: Correctly count gemini tokens

---

libs/agno/agno/workflow/v2/__init__.py
libs/agno/agno/workflow/v2/condition.py
libs/agno/agno/workflow/v2/loop.py
libs/agno/agno/workflow/v2/parallel.py
libs/agno/agno/workflow/v2/router.py
libs/agno/agno/workflow/v2/step.py
libs/agno/agno/workflow/v2/steps.py
libs/agno/agno/workflow/v2/workflow.py
libs/agno/tests/integration/workflow/test_condition_steps.py
libs/agno/tests/integration/workflow/test_loop_steps.py
libs/agno/tests/integration/workflow/test_parallel_steps.py
libs/agno/tests/integration/workflow/test_router_steps.py
libs/agno/tests/integration/workflow/test_steps.py
libs/agno/tests/integration/workflow/test_streaming_events.py
libs/agno/tests/integration/workflow/test_structured_output_flow.py

Tests for the following:
- checking if events are coming properly for streaming cases.
- tests for checking structured output flow
- cleaning and simplifying tests for primitives
- yielding only if `stream_intermediate_steps=True`
---
---
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210701525939765

feat: workflows tests update

---

cookbook/workflows/workflows_playground.py
libs/agno/agno/app/playground/async_router.py
libs/agno/agno/app/playground/sync_router.py

fix: Workflow streaming on playground

---

libs/agno/agno/models/openai/responses.py
libs/agno/agno/tools/function.py
libs/agno/agno/vectordb/weaviate/weaviate.py
libs/agno/tests/integration/agent/test_user_confirmation_flows.py
libs/agno/tests/unit/tools/test_functions.py

Handle assistant messages correctly in Responses API
#3738 
---
---

fix: Handle assistant messages in responses API

---

cookbook/evals/performance/team_response_with_memory_simple.py
cookbook/models/openai/chat/async_basic_stream.py
libs/agno/agno/agent/agent.py
libs/agno/agno/models/anthropic/claude.py
libs/agno/tests/integration/agent/test_agent_print_response.py

Fix `print_response` and `aprint_response` functions for streaming
Issue number: #3756
---
---

fix: print-response

---

cookbook/scripts/run_mysql.sh
cookbook/storage/mysql_storage/mysql_storage_for_agent.py
cookbook/storage/mysql_storage/mysql_storage_for_team.py
cookbook/storage/mysql_storage/mysql_storage_for_workflow.py
libs/agno/agno/storage/base.py
libs/agno/agno/storage/mysql.py
libs/agno/tests/unit/storage/test_mysql_storage.py

MySQL Storage
(If applicable, issue number: #3763)
---
---

feat: mysql storage

---

libs/agno/scripts/format.bat

fix: Windows formatter script

---

cookbook/examples/agents/startup_analyst_agent.py
libs/agno/agno/tools/scrapegraph.py

Startup analyst example - Scrapegraph
---
---

feat: Startup analyst example - Scrapegraph

---

cookbook/observability/atla_op.py
libs/agno/agno/embedder/langdb.py
libs/agno/agno/models/langdb/langdb.py

Atla Observability example
---

feat: Atla observability example

---

cookbook/workflows_2/async/01_basic_workflows/step_with_function_additional_data.py
cookbook/workflows_2/sync/01_basic_workflows/step_with_function_additional_data.py
libs/agno/agno/workflow/v2/condition.py
libs/agno/agno/workflow/v2/loop.py
libs/agno/agno/workflow/v2/router.py
libs/agno/agno/workflow/v2/steps.py
libs/agno/agno/workflow/v2/types.py
libs/agno/agno/workflow/v2/workflow.py

feat: additional data workflows 2.0

---

cookbook/tools/mcp/stagehand.py

Agent example using Stagehand MCP
---
---

feat: Stagehand MCP example

---

cookbook/agent_concepts/other/dynamic_instructions.py
libs/agno/agno/agent/agent.py

Adding an example for dynamic instructions.
#3723 
---
---

chore: Add example for dynamic instructions

---

cookbook/workflows_2/sync/01_basic_workflows/sequence_of_steps.py
cookbook/workflows_2/sync/01_basic_workflows/sequence_of_steps_stream.py
cookbook/workflows_2/sync/01_basic_workflows/step_with_function.py
cookbook/workflows_2/sync/01_basic_workflows/step_with_function_stream.py
cookbook/workflows_2/sync/06_workflows_advanced_concepts/access_multiple_previous_step_output_stream_2.py
cookbook/workflows_2/sync/06_workflows_advanced_concepts/access_multiple_previous_steps_output_stream_1.py
libs/agno/agno/app/playground/app.py
libs/agno/agno/run/v2/workflow.py
libs/agno/agno/workflow/v2/step.py
libs/agno/agno/workflow/v2/workflow.py

- for custom function we take the function name, very easy through inspection
- for `agent/team` use the name if avl, which many users dont set, in that case we can just do `step_1`, `step_2` etc..
- some comments to initial cookbooks 
---
---

chore: workflows 2 updates

---

libs/agno/tests/integration/models/portkey/test_basic.py
libs/agno/tests/integration/models/portkey/test_tool_use.py

Adds test for Portkey model class
---
---

feat: Add portkey tests

---

cookbook/agent_concepts/knowledge/vector_db/clickhouse_db/clickhouse.py
cookbook/agent_concepts/knowledge/vector_db/weaviate_db/weaviate_db.py
libs/agno/agno/vectordb/clickhouse/clickhousedb.py
libs/agno/agno/vectordb/weaviate/weaviate.py
libs/agno/tests/unit/vectordb/test_clickhousedb.py
libs/agno/tests/unit/vectordb/test_weaviatedb.py

feat: Clickhouse 2.0 DB parity

---

cookbook/agent_concepts/knowledge/vector_db/milvus_db/milvus_db.py
cookbook/agent_concepts/knowledge/vector_db/milvus_db/milvus_db_hybrid_search.py
cookbook/agent_concepts/knowledge/vector_db/weaviate_db/weaviate_db.py
libs/agno/agno/vectordb/milvus/milvus.py
libs/agno/agno/vectordb/weaviate/weaviate.py
libs/agno/tests/unit/vectordb/test_milvusdb.py
libs/agno/tests/unit/vectordb/test_weaviatedb.py

feat: Milvus 2.0 DB parity

---

cookbook/models/litellm/metrics.py
libs/agno/agno/models/litellm/chat.py

Fixes- https://github.com/agno-agi/agno/issues/3939
---
---

fix: litellm metrics aggregation

---

cookbook/agent_concepts/knowledge/vector_db/upstash_db/upstash_db.py
libs/agno/agno/vectordb/upstashdb/upstashdb.py
libs/agno/tests/unit/vectordb/test_upstashdb.py

upstash vector db parity 2.0
---
---

feat: upstash vector db parity 2.0

---

cookbook/scripts/run_cassandra.bat
cookbook/scripts/run_clickhouse.bat
cookbook/scripts/run_couchbase.bat
cookbook/scripts/run_mongodb.bat
cookbook/scripts/run_mysql.bat
cookbook/scripts/run_pgvector.bat
cookbook/scripts/run_qdrant.bat
cookbook/scripts/run_redis.bat
cookbook/scripts/run_singlestore.bat
cookbook/scripts/run_surrealdb.bat
cookbook/scripts/run_weviate.bat

feat: run pg vector script windows

---

cookbook/models/aws/bedrock/async_basic.py
cookbook/models/aws/bedrock/async_basic_stream.py
cookbook/tools/linkup_tools.py
libs/agno/agno/tools/linkup.py
libs/agno/pyproject.toml
libs/agno/tests/integration/models/aws/bedrock/test_basic.py
libs/agno/tests/integration/models/aws/bedrock/test_tool_use.py

Integration of linkup search tool, the best real time researcher
Similarity implementation with Tavily and Exa
-  New feature
---
---

feat: linkup search tool

---

libs/agno/agno/agent/agent.py

Rename vector_store - vector_db

---

.gitignore
cookbook/os/demo.py

fix: add eval manager to cookbook

---

.gitignore
cookbook/os/dbs/json_demo.py
libs/agno/agno/db/json/__init__.py
libs/agno/agno/db/json/json_db.py
libs/agno/agno/db/json/utils.py
libs/agno/agno/db/postgres/postgres.py

feat: add support for json files as db

---

libs/agno/agno/os/schema.py

fix: Run API

---

libs/agno/agno/models/google/gemini.py

feat: Gemini multi part bug fix

---

cookbook/observability/langwatch_op.py

Adds an example for Langwatch observability
---

feat: Langwatch Observability example

---

cookbook/models/meta/llama/async_knowledge.py
cookbook/models/meta/llama/async_tool_use_stream.py
cookbook/models/meta/llama/knowledge.py
cookbook/models/meta/llama/metrics.py
cookbook/models/meta/llama/tool_use_stream.py
cookbook/models/meta/llama_openai/async_tool_use.py
cookbook/models/meta/llama_openai/async_tool_use_stream.py
cookbook/models/meta/llama_openai/knowledge.py
cookbook/models/meta/llama_openai/metrics.py
cookbook/models/meta/llama_openai/tool_use.py
cookbook/models/meta/llama_openai/tool_use_stream.py

chore: Remove show_tool_calls
---

chore: Remove show_tool_calls - 4

---

cookbook_v2/knowledge/vector_db/cassandra_db/async_cassandra_db.py
cookbook_v2/knowledge/vector_db/cassandra_db/cassandra_db.py
cookbook_v2/knowledge/vector_db/chroma_db/async_chroma_db.py
cookbook_v2/knowledge/vector_db/clickhouse_db/async_clickhouse.py
cookbook_v2/knowledge/vector_db/couchbase_db/async_couchbase_db.py
cookbook_v2/knowledge/vector_db/milvus_db/milvus_db.py
cookbook_v2/knowledge/vector_db/milvus_db/milvus_db_hybrid_search.py
cookbook_v2/knowledge/vector_db/mongo_db/async_mongo_db.py
cookbook_v2/knowledge/vector_db/mongo_db/cosmos_mongodb_vcore.py
cookbook_v2/knowledge/vector_db/mongo_db/mongo_db.py
cookbook_v2/knowledge/vector_db/mongo_db/mongo_db_hybrid_search.py
cookbook_v2/knowledge/vector_db/pgvector/async_pg_vector.py
cookbook_v2/knowledge/vector_db/qdrant_db/async_qdrant_db.py
cookbook_v2/knowledge/vector_db/upstash_db/upstash_db.py
cookbook_v2/knowledge/vector_db/weaviate_db/async_weaviate_db.py
cookbook_v2/knowledge/vector_db/weaviate_db/weaviate_db_hybrid_search.py
cookbook_v2/os/demo.py
libs/agno/agno/agent/agent.py
libs/agno/agno/reasoning/default.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/apify.py
libs/agno/tests/integration/agent/test_agent_print_response.py

Remove show_tool_calls from files
---

chore: Remove show_tool_calls - 12

---

libs/agno/agno/db/dynamo/utils.py
libs/agno/agno/db/firestore/utils.py
libs/agno/agno/db/json/utils.py
libs/agno/agno/db/mongo/mongo.py
libs/agno/agno/db/mongo/utils.py
libs/agno/agno/db/mysql/mysql.py
libs/agno/agno/db/mysql/utils.py
libs/agno/agno/db/postgres/postgres.py
libs/agno/agno/db/postgres/utils.py
libs/agno/agno/db/redis/utils.py
libs/agno/agno/db/singlestore/utils.py
libs/agno/agno/db/sqlite/sqlite.py
libs/agno/agno/db/sqlite/utils.py

parity for metrics date fix

---

libs/agno/agno/os/apps/knowledge/router.py
libs/agno/agno/os/apps/knowledge/schemas.py

fix: Fix patch endpoint knowledge

---

libs/agno/agno/document/reader/youtube_reader.py
libs/agno/agno/tools/function.py
libs/agno/tests/unit/reader/test_youtube_reader.py

fix: youtube get_transcript

---

libs/agno/scripts/test.bat
libs/agno/tests/unit/tools/test_google_calendar.py
scripts/test.bat

- Added batch files for running tests suites on Windows
---
---

[feat] Add batch file for running tests on windows

---

libs/agno/agno/tools/aws_lambda.py

adding docstring to AWSLambdaTools

---

libs/agno/agno/knowledge/knowledge.py

fix: Avoid duplicate files content db

---

cookbook/agent_concepts/knowledge/vector_dbs/lance_db/remote_lance_db.py
libs/agno/agno/vectordb/lancedb/lance_db.py
libs/agno/tests/integration/agent/test_output_model.py

Fixes `RemoteDBConnection` with lancedb
(If applicable, issue number: #4123 )
---
---

fix: remote lancedb

---

libs/agno/agno/knowledge/knowledge.py

Lightrag fix

---

libs/agno/pyproject.toml
libs/agno/requirements.txt

Added `packaging` to `pyproject.toml` to resolve ModuleNotFoundError raised during imports in `agno.tools.function`.
- This fixes #4142 
---
---

fix: add 'packaging' dependency and regenerate requirements.txt

---

libs/agno/agno/vectordb/clickhouse/clickhousedb.py

fix: Using clickhouse as a vector database will result in an error (#4134)
fix using clickhouse as a vector database will result in an error
---
---
---

[fix] Using clickhouse as a vector database will result in an error

---

cookbook/agent_concepts/knowledge/vector_dbs/milvus_db/async_milvus_db_hybrid_search.py
libs/agno/agno/vectordb/milvus/milvus.py

Add async support for hybrid search in Milvus integration
- Milvus client throws "Milvus client not initialized" error when using `search_type=SearchType.hybrid` with async agents
- Root cause: Hybrid search functionality lacks async implementation, preventing proper async client initialization
- Added `async_hybrid_search` function to support asynchronous hybrid search operations
- Ensures async client is properly initialized when using hybrid search with async agents
---
---

[feat] Add async hybrid search support for Milvus integration

---

cookbook/agent_concepts/knowledge/vector_dbs/weaviate_db/weaviate_db_upsert.py
cookbook/teams/team_with_nested_shared_state.py
cookbook/tools/trafilatura_tools.py
libs/agno/agno/knowledge/agent.py
libs/agno/agno/tools/github.py
libs/agno/agno/tools/trafilatura.py
libs/agno/pyproject.toml
libs/agno/tests/unit/tools/test_github.py
libs/agno/tests/unit/tools/test_trafilatura.py

- Added TrafilaturaTools SDK for web scraping and text extraction using Trafilatura library
- 15 comprehensive cookbook examples from basic to advanced usage
- Complete unit test suite covering all functionality
(If applicable, issue number: #3899)
---
---

feat: Add Trafilatura to Web Scraping Tools

---

cookbook/apps/fastapi/study_friend.py
libs/agno/agno/app/fastapi/app.py

Added workers parameter to allow running of multiple agent processes in parallel with the fastapi app
---
---

feat: Add workers parameter to fastapi app

---

libs/agno/agno/team/team.py

`Team.arun()` updates `run_messages` (as done in the sync run method).
Fixes #4214 
---

fix: update run_messages in Team.arun()

---

libs/agno/agno/embedder/google.py

Add support for Vertex AI authentication in GeminiEmbedder alongside existing Google AI Studio API key support. This brings consistency with the Gemini LLM model which already supports both authentication methods, eliminating conflicts when using different auth approaches.
(If applicable, issue number: #4222)
---
---
- Added `vertexai`, `project_id`, and `location` parameters to GeminiEmbedder class
- Modified client initialization to check for Vertex AI mode via `GOOGLE_GENAI_USE_VERTEXAI` environment variable
- Maintained full backward compatibility with existing API key authentication
- Follows same pattern as Gemini LLM implementation for consistency

[feat] Add Vertex AI support for GeminiEmbedder

---

libs/agno/agno/db/singlestore/singlestore.py
libs/agno/agno/knowledge/embedder/cohere.py
libs/agno/agno/knowledge/embedder/mistral.py
libs/agno/agno/knowledge/embedder/openai.py
libs/agno/agno/knowledge/knowledge.py
libs/agno/agno/knowledge/reader/reader_factory.py
libs/agno/agno/os/apps/knowledge/router.py
libs/agno/agno/tools/website.py
libs/agno/agno/vectordb/base.py
libs/agno/agno/vectordb/cassandra/cassandra.py
libs/agno/agno/vectordb/chroma/chromadb.py
libs/agno/agno/vectordb/clickhouse/clickhousedb.py
libs/agno/agno/vectordb/couchbase/couchbase.py
libs/agno/agno/vectordb/lancedb/lance_db.py
libs/agno/agno/vectordb/lightrag/lightrag.py
libs/agno/agno/vectordb/milvus/milvus.py
libs/agno/agno/vectordb/mongodb/mongodb.py
libs/agno/agno/vectordb/pineconedb/pineconedb.py
libs/agno/agno/vectordb/qdrant/qdrant.py
libs/agno/agno/vectordb/surrealdb/surrealdb.py
libs/agno/agno/vectordb/weaviate/weaviate.py

fix: style fixes

---

libs/agno/agno/os/schema.py

 Metadata in agent, team and workflow response

---

cookbook/knowledge/vector_db/weaviate_db/async_weaviate_db.py
cookbook/knowledge/vector_db/weaviate_db/weaviate_db.py
cookbook/knowledge/vector_db/weaviate_db/weaviate_db_hybrid_search.py
libs/agno/agno/agent/agent.py
libs/agno/agno/vectordb/weaviate/weaviate.py

Fix weaviate after merge

---

cookbook/knowledge/vector_db/weaviate_db/async_weaviate_db.py
libs/agno/agno/knowledge/reader/pdf_reader.py
libs/agno/agno/vectordb/lancedb/lance_db.py
libs/agno/agno/vectordb/weaviate/weaviate.py
libs/agno/tests/integration/knowledge/test_arxiv_knowledge.py
libs/agno/tests/integration/knowledge/test_csv_knowledge.py
libs/agno/tests/integration/knowledge/test_csv_url_knowledge.py
libs/agno/tests/integration/knowledge/test_docx_knowledge.py
libs/agno/tests/integration/knowledge/test_firecrawl_knowledge.py
libs/agno/tests/integration/knowledge/test_json_knowledge.py
libs/agno/tests/integration/knowledge/test_md_knowledge.py
libs/agno/tests/integration/knowledge/test_pdf_knowledge.py
libs/agno/tests/integration/knowledge/test_pdf_url_knowledge.py
libs/agno/tests/integration/knowledge/test_text_knowledge.py
libs/agno/tests/integration/knowledge/test_website_knowledge.py
libs/agno/tests/integration/knowledge/test_youtube_knowledge.py
libs/agno/tests/integration/vector_dbs/test_lancedb.py

fix: Knowledge tests updates

---

libs/agno/pyproject.toml

- **Teams Collaborate Streaming:** Added support for streaming or teams on `collaborate` mode.
- **OpenAI Verbosity**: Added `verbosity` parameter to `OpenAIChat` and `OpenAIResponses`.
- **Gemini URL Context Tool:** Adds support fior Gemini URL context tool.
- **GCSKnowledgeBase Load:** Fixed cases where `.load()` functioned incorrectly.
- **Youtube Transcripts**: Removed deprecated implementation in `YoutubeTools`.

chore: Release 1.7.12

---

libs/agno/agno/tools/scrapegraph.py

feat: Update scrapegraph.py

---

libs/agno/agno/vectordb/pgvector/pgvector.py
libs/agno/tests/unit/vectordb/test_pgvector.py

- Fixes #4266 by aligning PgVector upsert with insert so it respects an explicit Document.id and falls back to content_hash
only when id is absent.
- Refactors duplicated record construction into a single helper for consistency.
- Merges filters into meta_data while still persisting filters separately.
---
---

[fix] PgVector upsert respects Document.id and unifies record building

---

cookbook/knowledge/readers/pdf_reader_async.py
cookbook/knowledge/vector_db/pgvector/pgvector_db.py
libs/agno/agno/knowledge/knowledge.py
libs/agno/tests/integration/knowledge/test_csv_knowledge.py
libs/agno/tests/integration/knowledge/test_csv_url_knowledge.py
libs/agno/tests/integration/knowledge/test_pdf_knowledge.py
libs/agno/tests/integration/knowledge/test_pdf_url_knowledge.py

fix: Knowledge cookbooks

---

cookbook/workflows/06_advanced_concepts/06_other/store_events_and_events_to_skip_in_a_workflow.py
libs/agno/agno/workflow/workflow.py

- add correct type check and update cookbook
---
---

chore: update workflows store events

---

libs/agno/agno/models/base.py
libs/agno/tests/integration/models/google/test_multimodal.py

fix: update gemini failing tests

---

libs/agno/agno/models/base.py
libs/agno/agno/team/team.py
libs/agno/tests/integration/models/google/test_multimodal.py
libs/agno/tests/integration/tools/test_tool_generated_media.py

- add more integration tests for tools 2.0 media generation check
- same changes for team as in agent.
---
---

feat: teams tools 2 media

---

libs/agno/agno/tools/gmail.py
libs/agno/agno/vectordb/base.py
libs/agno/agno/vectordb/qdrant/qdrant.py

- Added `close()` method to Qdrant class
- Added `async_close()` method to Qdrant class
- Updated VectorDb base class
- updated Gmail toolkit `creds `param for better clarity
fixes #4285 
---
---

feat: Add connection cleanup to Qdrant implementation

---

libs/agno/agno/models/anthropic/claude.py

With Anthropic we were using thinking chunks twice

fix: Double thinking chunks

---

libs/agno/agno/db/firestore/firestore.py
libs/agno/agno/db/gcs_json/gcs_json_db.py
libs/agno/agno/db/json/json_db.py
libs/agno/agno/db/mongo/mongo.py
libs/agno/agno/db/mysql/mysql.py
libs/agno/agno/db/postgres/postgres.py
libs/agno/agno/db/singlestore/singlestore.py
libs/agno/agno/db/sqlite/sqlite.py
libs/agno/agno/os/routers/metrics/metrics.py

feat: metrics table creation fix

---

libs/agno/agno/tools/firecrawl.py
libs/agno/tests/unit/tools/test_firecrawl.py
scripts/dev_setup.sh

- Firecrawl dependency upgrade
---
---

[chore] firecrawl dependency upgrade

---

libs/agno/agno/db/sqlite/sqlite.py

fix sqlite db get sessions filtering for session type 
---
---

fix: sqlite db get sessions filtering for session type

---

libs/agno/agno/tools/mlx_transcribe.py
libs/agno/agno/tools/moviepy_video.py
libs/agno/agno/tools/newspaper.py
libs/agno/agno/tools/zep.py

feat: Tools update fix

---

cookbook/models/azure/ai_foundry/README.md

docs: add url to azure ai foundry portal

---

libs/agno/agno/models/base.py
libs/agno/agno/utils/mcp.py

- `arun_function_calls` was not handling ToolResult properly for media generated from tools
- mcp was not properly handling images conversion
---
---

fix: arun function calls media and mcp image ToolResult

---

libs/agno/agno/knowledge/chunking/strategy.py
libs/agno/agno/knowledge/reader/arxiv_reader.py
libs/agno/agno/knowledge/reader/csv_reader.py
libs/agno/agno/knowledge/reader/docx_reader.py
libs/agno/agno/knowledge/reader/firecrawl_reader.py
libs/agno/agno/knowledge/reader/gcs_reader.py
libs/agno/agno/knowledge/reader/json_reader.py
libs/agno/agno/knowledge/reader/markdown_reader.py
libs/agno/agno/knowledge/reader/pdf_reader.py
libs/agno/agno/knowledge/reader/reader_factory.py
libs/agno/agno/knowledge/reader/s3_reader.py
libs/agno/agno/knowledge/reader/text_reader.py
libs/agno/agno/knowledge/reader/url_reader.py
libs/agno/agno/knowledge/reader/web_search_reader.py
libs/agno/agno/knowledge/reader/website_reader.py
libs/agno/agno/knowledge/reader/wikipedia_reader.py
libs/agno/agno/knowledge/reader/youtube_reader.py
libs/agno/agno/knowledge/utils.py

---
- Updated `get_reader_info` and `get_chunker_info` functions for better naming conventions.
- Modified `ChunkingStrategyType` to use more consistent naming for chunkers.
- fixed `csvReader` to show on config response
- fixed  `MarkdownReader` to support dynamic chunking strategies based on availability.
- updated `ReaderFactory` to manually sort URL readers in the list of available reader keys.
- 
---

feat: readers and chunker updates

---

cookbook/agent_os/dbs/sqlite_demo.py

fix: update

---

libs/agno/agno/db/mongo/mongo.py

…ects
- Updated methods in MongoDb class to exclude the _id field from the result before creating UserMemory instances.
- Ensured consistent handling of the _id field across different methods to prevent potential issues with object creation.
---
---

refactor: fix mongo

---

libs/agno/agno/knowledge/chunking/fixed.py
libs/agno/tests/unit/reader/test_text_reader.py

fix: Update fixedChunking size

---

cookbook/knowledge/readers/csv_reader_custom_encodings.py
cookbook/models/cerebras/oss_gpt.py
cookbook/models/cerebras_openai/oss_gpt.py
cookbook/workflows/_06_advanced_concepts/_06_other/workflow_tools.py
libs/agno/agno/knowledge/reader/base.py
libs/agno/agno/knowledge/reader/csv_reader.py
libs/agno/agno/knowledge/reader/json_reader.py
libs/agno/agno/knowledge/reader/markdown_reader.py
libs/agno/agno/knowledge/reader/s3_reader.py
libs/agno/agno/knowledge/reader/text_reader.py
libs/agno/agno/tools/workflow.py

feat: Support custom encoding on reader class

---

cookbook/teams/memory/01_team_with_memory_manager.py
libs/agno/agno/team/team.py

fix: team memory manager

---

libs/agno/agno/utils/print_response/agent.py

fix: print response stream changes for parser model

---

cookbook/agents/rag/agentic_rag_with_reranking.py
cookbook/agents/rag/rag_sentence_transformer.py
cookbook/tools/duckduckgo_tools.py

fix: Cohere and SentenceTransformer cookbooks

---

cookbook/knowledge/readers/web_search_reader_async.py
libs/agno/agno/os/schema.py

fix: populate reasoning steps on RunSchemas

---

libs/agno/agno/run/workflow.py
libs/agno/agno/workflow/workflow.py

fixes: https://github.com/agno-agi/agno/issues/4619
---
---

feat: store workflow input in db

---

libs/agno/agno/knowledge/embedder/openai.py
libs/agno/agno/vectordb/milvus/milvus.py

- Handle OpenAIEmbedder response exceptions with try-catch
- Skip documents with empty embeddings in Milvus insert
related to #4421
---
---

 fix: multiple issues causing KB load failures in version 2.x.x #4422 

---

libs/agno/agno/workflow/workflow.py

chore: Revert "chore: remove background bool from run in workflow"

---

libs/agno/agno/os/schema.py

feat: Add chat_history field to TeamSessionDetailSchema

---

cookbook/agents/agentic_search/agentic_rag.py
cookbook/agents/agentic_search/agentic_rag_infinity_reranker.py
cookbook/agents/agentic_search/agentic_rag_with_reasoning.py
cookbook/agents/async/data_analyst.py
cookbook/demo/agents/web_search.py
libs/agno/agno/agent/agent.py
libs/agno/agno/session/agent.py
libs/agno/agno/session/team.py
libs/agno/agno/team/team.py

fix: system message role bug fix

---

cookbook/agents/dependencies/access_dependencies_in_tool.py
cookbook/teams/dependencies/access_dependencies_in_tool.py
libs/agno/agno/agent/agent.py
libs/agno/agno/db/migrations/v1_to_v2.py
libs/agno/agno/team/team.py
libs/agno/agno/tools/function.py
libs/agno/tests/unit/knowledge/test_knowledge_encoding.py

make dependencies available on tools
---
---

feat: access dependencies on tool

---

cookbook/agents/dependencies/access_dependencies_in_tool.py
cookbook/teams/dependencies/access_dependencies_in_tool.py
libs/agno/agno/models/ollama/chat.py
libs/agno/tests/integration/models/ollama/test_basic.py

Fix for using correct host for Async client
---

[Fix] async ollama client with different Host not used correctly

---

libs/agno/agno/models/openai/responses.py

fixes: https://github.com/agno-agi/agno/issues/4712
Before:
After:
---
---

fix: remove duplicate messages in OpenAIResponses 

---

libs/agno/agno/models/openai/responses.py

chore: OpenAI responses update

---

cookbook/models/huggingface/tool_use_stream.py
libs/agno/agno/models/huggingface/huggingface.py
libs/agno/tests/integration/models/huggingface/test_tool_use.py

Updates the HF Model class config for streaming tool calls
---
---

fix: huggingface model class

---

libs/agno/agno/models/anthropic/claude.py
libs/agno/agno/utils/models/claude.py
libs/agno/pyproject.toml

- **Anthropic Claude**: Removes legacy tool call formatting

chore: Release 1.8.3

---

libs/agno/agno/workflow/types.py
libs/agno/agno/workflow/workflow.py

- Updated the Workflow class to include a parameter `files` in the async pipeline input creation, enhancing the flexibility of input handling.
---
---

feat: add support for files in async pipeline input

---

libs/agno/agno/models/google/gemini.py

fix: gemini metrics for 2.5 models

---

cookbook/knowledge/filters/agentic_filtering_with_output_schema.py
libs/agno/agno/tools/function.py
libs/agno/tests/integration/knowledge/filters/test_agentic_filtering.py

with a config like this-
```python
agent = Agent(
model=OpenAIChat("gpt-5-mini"),
knowledge=knowledge,
search_knowledge=True,
enable_agentic_knowledge_filters=True,
debug_mode=True,
output_schema=CSVDataOutput,
)
```
when `output_schema` is set with `enable_agentic_knowledge_filters=True` it breaks with this for openai-
```bash
ERROR API status error from OpenAI API: Error code: 400 - {'error':
{'message': "Invalid schema for function
'search_knowledge_base_with_agentic_filters': In context=('properties',
'filters', 'items'), 'additionalProperties' is required to be supplied
and to be false.", 'type': 'invalid_request_error', 'param':
'tools[8].function.parameters', 'code': 'invalid_function_parameters'}}
```
---
---
Add any important context (deployment instructions, screenshots, …

fix: kb filter with output schema

---

.github/workflows/performance.yml
.github/workflows/release.yml
.github/workflows/test_on_release.yml

Added sudo apt-get update and sudo apt-get install -y python3-venv to the dependency installation steps in both langgraph-performance and agno-performance jobs in performance.yml
This ensures required system packages are present before installing Python dependencies.
- [X ] Improvement
---
- [ X] Code complies with style guidelines
- [ X] Ran format/validation scripts (`./scripts/format.sh` and `./scripts/validate.sh`)
- [ X] Self-review completed
- [ X] Documentation updated (comments, docstrings)
- [ X] Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
- [ X] Tested in clean environment
- [ X] Tests added/updated (if applicable)
---
No breaking changes. Improves reliability of workflow setup on Ubuntu runner

feat: Update workflows to install python3-venv and update package lists
